// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: discussion.proto

package discussionrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DiscussionService_ListMessages_FullMethodName         = "/blog.discussion.v1.DiscussionService/ListMessages"
	DiscussionService_GetMessage_FullMethodName           = "/blog.discussion.v1.DiscussionService/GetMessage"
	DiscussionService_CreateMessage_FullMethodName        = "/blog.discussion.v1.DiscussionService/CreateMessage"
	DiscussionService_UpdateMessage_FullMethodName        = "/blog.discussion.v1.DiscussionService/UpdateMessage"
	DiscussionService_BatchDeleteMessages_FullMethodName  = "/blog.discussion.v1.DiscussionService/BatchDeleteMessages"
	DiscussionService_BatchPatchMessages_FullMethodName   = "/blog.discussion.v1.DiscussionService/BatchPatchMessages"
	DiscussionService_ListComments_FullMethodName         = "/blog.discussion.v1.DiscussionService/ListComments"
	DiscussionService_ListCommentReplies_FullMethodName   = "/blog.discussion.v1.DiscussionService/ListCommentReplies"
	DiscussionService_GetComment_FullMethodName           = "/blog.discussion.v1.DiscussionService/GetComment"
	DiscussionService_CreateComment_FullMethodName        = "/blog.discussion.v1.DiscussionService/CreateComment"
	DiscussionService_UpdateComment_FullMethodName        = "/blog.discussion.v1.DiscussionService/UpdateComment"
	DiscussionService_BatchDeleteComments_FullMethodName  = "/blog.discussion.v1.DiscussionService/BatchDeleteComments"
	DiscussionService_BatchPatchComments_FullMethodName   = "/blog.discussion.v1.DiscussionService/BatchPatchComments"
	DiscussionService_GetCommentReplyCount_FullMethodName = "/blog.discussion.v1.DiscussionService/GetCommentReplyCount"
	DiscussionService_LikeComment_FullMethodName          = "/blog.discussion.v1.DiscussionService/LikeComment"
	DiscussionService_GetUserLikeComment_FullMethodName   = "/blog.discussion.v1.DiscussionService/GetUserLikeComment"
	DiscussionService_ListTalks_FullMethodName            = "/blog.discussion.v1.DiscussionService/ListTalks"
	DiscussionService_GetTalk_FullMethodName              = "/blog.discussion.v1.DiscussionService/GetTalk"
	DiscussionService_CreateTalk_FullMethodName           = "/blog.discussion.v1.DiscussionService/CreateTalk"
	DiscussionService_UpdateTalk_FullMethodName           = "/blog.discussion.v1.DiscussionService/UpdateTalk"
	DiscussionService_BatchDeleteTalks_FullMethodName     = "/blog.discussion.v1.DiscussionService/BatchDeleteTalks"
	DiscussionService_LikeTalk_FullMethodName             = "/blog.discussion.v1.DiscussionService/LikeTalk"
	DiscussionService_GetUserLikeTalk_FullMethodName      = "/blog.discussion.v1.DiscussionService/GetUserLikeTalk"
)

// DiscussionServiceClient is the client API for DiscussionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscussionServiceClient interface {
	// 查询留言列表
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
	// 查询留言
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
	// 创建留言
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error)
	// 更新留言
	UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error)
	// 批量删除留言
	BatchDeleteMessages(ctx context.Context, in *BatchDeleteMessagesRequest, opts ...grpc.CallOption) (*BatchDeleteMessagesResponse, error)
	// 部分更新留言（批量）
	BatchPatchMessages(ctx context.Context, in *BatchPatchMessagesRequest, opts ...grpc.CallOption) (*BatchPatchMessagesResponse, error)
	// 查询评论列表
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	// 查询评论回复列表
	ListCommentReplies(ctx context.Context, in *ListCommentRepliesRequest, opts ...grpc.CallOption) (*ListCommentRepliesResponse, error)
	// 查询评论
	GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error)
	// 创建评论
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	// 更新评论
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error)
	// 批量删除评论
	BatchDeleteComments(ctx context.Context, in *BatchDeleteCommentsRequest, opts ...grpc.CallOption) (*BatchDeleteCommentsResponse, error)
	// 部分更新评论（批量）
	BatchPatchComments(ctx context.Context, in *BatchPatchCommentsRequest, opts ...grpc.CallOption) (*BatchPatchCommentsResponse, error)
	// 查询评论回复数量
	GetCommentReplyCount(ctx context.Context, in *GetCommentReplyCountRequest, opts ...grpc.CallOption) (*GetCommentReplyCountResponse, error)
	// 点赞评论
	LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error)
	// 查询用户点赞的评论
	GetUserLikeComment(ctx context.Context, in *GetUserLikeCommentRequest, opts ...grpc.CallOption) (*GetUserLikeCommentResponse, error)
	// 分页查询说说列表
	ListTalks(ctx context.Context, in *ListTalksRequest, opts ...grpc.CallOption) (*ListTalksResponse, error)
	// 查询说说详情
	GetTalk(ctx context.Context, in *GetTalkRequest, opts ...grpc.CallOption) (*GetTalkResponse, error)
	// 创建说说
	CreateTalk(ctx context.Context, in *CreateTalkRequest, opts ...grpc.CallOption) (*CreateTalkResponse, error)
	// 更新说说
	UpdateTalk(ctx context.Context, in *UpdateTalkRequest, opts ...grpc.CallOption) (*UpdateTalkResponse, error)
	// 批量删除说说
	BatchDeleteTalks(ctx context.Context, in *BatchDeleteTalksRequest, opts ...grpc.CallOption) (*BatchDeleteTalksResponse, error)
	// 点赞说说
	LikeTalk(ctx context.Context, in *LikeTalkRequest, opts ...grpc.CallOption) (*LikeTalkResponse, error)
	// 查询用户点赞的说说
	GetUserLikeTalk(ctx context.Context, in *GetUserLikeTalkRequest, opts ...grpc.CallOption) (*GetUserLikeTalkResponse, error)
}

type discussionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscussionServiceClient(cc grpc.ClientConnInterface) DiscussionServiceClient {
	return &discussionServiceClient{cc}
}

func (c *discussionServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	out := new(ListMessagesResponse)
	err := c.cc.Invoke(ctx, DiscussionService_ListMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	out := new(GetMessageResponse)
	err := c.cc.Invoke(ctx, DiscussionService_GetMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error) {
	out := new(CreateMessageResponse)
	err := c.cc.Invoke(ctx, DiscussionService_CreateMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error) {
	out := new(UpdateMessageResponse)
	err := c.cc.Invoke(ctx, DiscussionService_UpdateMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) BatchDeleteMessages(ctx context.Context, in *BatchDeleteMessagesRequest, opts ...grpc.CallOption) (*BatchDeleteMessagesResponse, error) {
	out := new(BatchDeleteMessagesResponse)
	err := c.cc.Invoke(ctx, DiscussionService_BatchDeleteMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) BatchPatchMessages(ctx context.Context, in *BatchPatchMessagesRequest, opts ...grpc.CallOption) (*BatchPatchMessagesResponse, error) {
	out := new(BatchPatchMessagesResponse)
	err := c.cc.Invoke(ctx, DiscussionService_BatchPatchMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, DiscussionService_ListComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) ListCommentReplies(ctx context.Context, in *ListCommentRepliesRequest, opts ...grpc.CallOption) (*ListCommentRepliesResponse, error) {
	out := new(ListCommentRepliesResponse)
	err := c.cc.Invoke(ctx, DiscussionService_ListCommentReplies_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error) {
	out := new(GetCommentResponse)
	err := c.cc.Invoke(ctx, DiscussionService_GetComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, DiscussionService_CreateComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error) {
	out := new(UpdateCommentResponse)
	err := c.cc.Invoke(ctx, DiscussionService_UpdateComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) BatchDeleteComments(ctx context.Context, in *BatchDeleteCommentsRequest, opts ...grpc.CallOption) (*BatchDeleteCommentsResponse, error) {
	out := new(BatchDeleteCommentsResponse)
	err := c.cc.Invoke(ctx, DiscussionService_BatchDeleteComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) BatchPatchComments(ctx context.Context, in *BatchPatchCommentsRequest, opts ...grpc.CallOption) (*BatchPatchCommentsResponse, error) {
	out := new(BatchPatchCommentsResponse)
	err := c.cc.Invoke(ctx, DiscussionService_BatchPatchComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) GetCommentReplyCount(ctx context.Context, in *GetCommentReplyCountRequest, opts ...grpc.CallOption) (*GetCommentReplyCountResponse, error) {
	out := new(GetCommentReplyCountResponse)
	err := c.cc.Invoke(ctx, DiscussionService_GetCommentReplyCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error) {
	out := new(LikeCommentResponse)
	err := c.cc.Invoke(ctx, DiscussionService_LikeComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) GetUserLikeComment(ctx context.Context, in *GetUserLikeCommentRequest, opts ...grpc.CallOption) (*GetUserLikeCommentResponse, error) {
	out := new(GetUserLikeCommentResponse)
	err := c.cc.Invoke(ctx, DiscussionService_GetUserLikeComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) ListTalks(ctx context.Context, in *ListTalksRequest, opts ...grpc.CallOption) (*ListTalksResponse, error) {
	out := new(ListTalksResponse)
	err := c.cc.Invoke(ctx, DiscussionService_ListTalks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) GetTalk(ctx context.Context, in *GetTalkRequest, opts ...grpc.CallOption) (*GetTalkResponse, error) {
	out := new(GetTalkResponse)
	err := c.cc.Invoke(ctx, DiscussionService_GetTalk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) CreateTalk(ctx context.Context, in *CreateTalkRequest, opts ...grpc.CallOption) (*CreateTalkResponse, error) {
	out := new(CreateTalkResponse)
	err := c.cc.Invoke(ctx, DiscussionService_CreateTalk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) UpdateTalk(ctx context.Context, in *UpdateTalkRequest, opts ...grpc.CallOption) (*UpdateTalkResponse, error) {
	out := new(UpdateTalkResponse)
	err := c.cc.Invoke(ctx, DiscussionService_UpdateTalk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) BatchDeleteTalks(ctx context.Context, in *BatchDeleteTalksRequest, opts ...grpc.CallOption) (*BatchDeleteTalksResponse, error) {
	out := new(BatchDeleteTalksResponse)
	err := c.cc.Invoke(ctx, DiscussionService_BatchDeleteTalks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) LikeTalk(ctx context.Context, in *LikeTalkRequest, opts ...grpc.CallOption) (*LikeTalkResponse, error) {
	out := new(LikeTalkResponse)
	err := c.cc.Invoke(ctx, DiscussionService_LikeTalk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) GetUserLikeTalk(ctx context.Context, in *GetUserLikeTalkRequest, opts ...grpc.CallOption) (*GetUserLikeTalkResponse, error) {
	out := new(GetUserLikeTalkResponse)
	err := c.cc.Invoke(ctx, DiscussionService_GetUserLikeTalk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscussionServiceServer is the server API for DiscussionService service.
// All implementations must embed UnimplementedDiscussionServiceServer
// for forward compatibility
type DiscussionServiceServer interface {
	// 查询留言列表
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	// 查询留言
	GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error)
	// 创建留言
	CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error)
	// 更新留言
	UpdateMessage(context.Context, *UpdateMessageRequest) (*UpdateMessageResponse, error)
	// 批量删除留言
	BatchDeleteMessages(context.Context, *BatchDeleteMessagesRequest) (*BatchDeleteMessagesResponse, error)
	// 部分更新留言（批量）
	BatchPatchMessages(context.Context, *BatchPatchMessagesRequest) (*BatchPatchMessagesResponse, error)
	// 查询评论列表
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	// 查询评论回复列表
	ListCommentReplies(context.Context, *ListCommentRepliesRequest) (*ListCommentRepliesResponse, error)
	// 查询评论
	GetComment(context.Context, *GetCommentRequest) (*GetCommentResponse, error)
	// 创建评论
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	// 更新评论
	UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error)
	// 批量删除评论
	BatchDeleteComments(context.Context, *BatchDeleteCommentsRequest) (*BatchDeleteCommentsResponse, error)
	// 部分更新评论（批量）
	BatchPatchComments(context.Context, *BatchPatchCommentsRequest) (*BatchPatchCommentsResponse, error)
	// 查询评论回复数量
	GetCommentReplyCount(context.Context, *GetCommentReplyCountRequest) (*GetCommentReplyCountResponse, error)
	// 点赞评论
	LikeComment(context.Context, *LikeCommentRequest) (*LikeCommentResponse, error)
	// 查询用户点赞的评论
	GetUserLikeComment(context.Context, *GetUserLikeCommentRequest) (*GetUserLikeCommentResponse, error)
	// 分页查询说说列表
	ListTalks(context.Context, *ListTalksRequest) (*ListTalksResponse, error)
	// 查询说说详情
	GetTalk(context.Context, *GetTalkRequest) (*GetTalkResponse, error)
	// 创建说说
	CreateTalk(context.Context, *CreateTalkRequest) (*CreateTalkResponse, error)
	// 更新说说
	UpdateTalk(context.Context, *UpdateTalkRequest) (*UpdateTalkResponse, error)
	// 批量删除说说
	BatchDeleteTalks(context.Context, *BatchDeleteTalksRequest) (*BatchDeleteTalksResponse, error)
	// 点赞说说
	LikeTalk(context.Context, *LikeTalkRequest) (*LikeTalkResponse, error)
	// 查询用户点赞的说说
	GetUserLikeTalk(context.Context, *GetUserLikeTalkRequest) (*GetUserLikeTalkResponse, error)
	mustEmbedUnimplementedDiscussionServiceServer()
}

// UnimplementedDiscussionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDiscussionServiceServer struct {
}

func (UnimplementedDiscussionServiceServer) ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedDiscussionServiceServer) GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedDiscussionServiceServer) CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedDiscussionServiceServer) UpdateMessage(context.Context, *UpdateMessageRequest) (*UpdateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMessage not implemented")
}
func (UnimplementedDiscussionServiceServer) BatchDeleteMessages(context.Context, *BatchDeleteMessagesRequest) (*BatchDeleteMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteMessages not implemented")
}
func (UnimplementedDiscussionServiceServer) BatchPatchMessages(context.Context, *BatchPatchMessagesRequest) (*BatchPatchMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPatchMessages not implemented")
}
func (UnimplementedDiscussionServiceServer) ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedDiscussionServiceServer) ListCommentReplies(context.Context, *ListCommentRepliesRequest) (*ListCommentRepliesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCommentReplies not implemented")
}
func (UnimplementedDiscussionServiceServer) GetComment(context.Context, *GetCommentRequest) (*GetCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComment not implemented")
}
func (UnimplementedDiscussionServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedDiscussionServiceServer) UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedDiscussionServiceServer) BatchDeleteComments(context.Context, *BatchDeleteCommentsRequest) (*BatchDeleteCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteComments not implemented")
}
func (UnimplementedDiscussionServiceServer) BatchPatchComments(context.Context, *BatchPatchCommentsRequest) (*BatchPatchCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPatchComments not implemented")
}
func (UnimplementedDiscussionServiceServer) GetCommentReplyCount(context.Context, *GetCommentReplyCountRequest) (*GetCommentReplyCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentReplyCount not implemented")
}
func (UnimplementedDiscussionServiceServer) LikeComment(context.Context, *LikeCommentRequest) (*LikeCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeComment not implemented")
}
func (UnimplementedDiscussionServiceServer) GetUserLikeComment(context.Context, *GetUserLikeCommentRequest) (*GetUserLikeCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLikeComment not implemented")
}
func (UnimplementedDiscussionServiceServer) ListTalks(context.Context, *ListTalksRequest) (*ListTalksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTalks not implemented")
}
func (UnimplementedDiscussionServiceServer) GetTalk(context.Context, *GetTalkRequest) (*GetTalkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTalk not implemented")
}
func (UnimplementedDiscussionServiceServer) CreateTalk(context.Context, *CreateTalkRequest) (*CreateTalkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTalk not implemented")
}
func (UnimplementedDiscussionServiceServer) UpdateTalk(context.Context, *UpdateTalkRequest) (*UpdateTalkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTalk not implemented")
}
func (UnimplementedDiscussionServiceServer) BatchDeleteTalks(context.Context, *BatchDeleteTalksRequest) (*BatchDeleteTalksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteTalks not implemented")
}
func (UnimplementedDiscussionServiceServer) LikeTalk(context.Context, *LikeTalkRequest) (*LikeTalkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeTalk not implemented")
}
func (UnimplementedDiscussionServiceServer) GetUserLikeTalk(context.Context, *GetUserLikeTalkRequest) (*GetUserLikeTalkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLikeTalk not implemented")
}
func (UnimplementedDiscussionServiceServer) mustEmbedUnimplementedDiscussionServiceServer() {}

// UnsafeDiscussionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscussionServiceServer will
// result in compilation errors.
type UnsafeDiscussionServiceServer interface {
	mustEmbedUnimplementedDiscussionServiceServer()
}

func RegisterDiscussionServiceServer(s grpc.ServiceRegistrar, srv DiscussionServiceServer) {
	s.RegisterService(&DiscussionService_ServiceDesc, srv)
}

func _DiscussionService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_CreateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_UpdateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).UpdateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_UpdateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).UpdateMessage(ctx, req.(*UpdateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_BatchDeleteMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).BatchDeleteMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_BatchDeleteMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).BatchDeleteMessages(ctx, req.(*BatchDeleteMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_BatchPatchMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPatchMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).BatchPatchMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_BatchPatchMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).BatchPatchMessages(ctx, req.(*BatchPatchMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_ListCommentReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentRepliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).ListCommentReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_ListCommentReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).ListCommentReplies(ctx, req.(*ListCommentRepliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_GetComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).GetComment(ctx, req.(*GetCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_BatchDeleteComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).BatchDeleteComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_BatchDeleteComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).BatchDeleteComments(ctx, req.(*BatchDeleteCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_BatchPatchComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPatchCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).BatchPatchComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_BatchPatchComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).BatchPatchComments(ctx, req.(*BatchPatchCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_GetCommentReplyCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentReplyCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).GetCommentReplyCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_GetCommentReplyCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).GetCommentReplyCount(ctx, req.(*GetCommentReplyCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_LikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).LikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_LikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).LikeComment(ctx, req.(*LikeCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_GetUserLikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLikeCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).GetUserLikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_GetUserLikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).GetUserLikeComment(ctx, req.(*GetUserLikeCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_ListTalks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTalksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).ListTalks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_ListTalks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).ListTalks(ctx, req.(*ListTalksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_GetTalk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTalkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).GetTalk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_GetTalk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).GetTalk(ctx, req.(*GetTalkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_CreateTalk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTalkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).CreateTalk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_CreateTalk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).CreateTalk(ctx, req.(*CreateTalkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_UpdateTalk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTalkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).UpdateTalk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_UpdateTalk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).UpdateTalk(ctx, req.(*UpdateTalkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_BatchDeleteTalks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteTalksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).BatchDeleteTalks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_BatchDeleteTalks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).BatchDeleteTalks(ctx, req.(*BatchDeleteTalksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_LikeTalk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeTalkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).LikeTalk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_LikeTalk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).LikeTalk(ctx, req.(*LikeTalkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_GetUserLikeTalk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLikeTalkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).GetUserLikeTalk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_GetUserLikeTalk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).GetUserLikeTalk(ctx, req.(*GetUserLikeTalkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscussionService_ServiceDesc is the grpc.ServiceDesc for DiscussionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscussionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.discussion.v1.DiscussionService",
	HandlerType: (*DiscussionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMessages",
			Handler:    _DiscussionService_ListMessages_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _DiscussionService_GetMessage_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _DiscussionService_CreateMessage_Handler,
		},
		{
			MethodName: "UpdateMessage",
			Handler:    _DiscussionService_UpdateMessage_Handler,
		},
		{
			MethodName: "BatchDeleteMessages",
			Handler:    _DiscussionService_BatchDeleteMessages_Handler,
		},
		{
			MethodName: "BatchPatchMessages",
			Handler:    _DiscussionService_BatchPatchMessages_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _DiscussionService_ListComments_Handler,
		},
		{
			MethodName: "ListCommentReplies",
			Handler:    _DiscussionService_ListCommentReplies_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _DiscussionService_GetComment_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _DiscussionService_CreateComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _DiscussionService_UpdateComment_Handler,
		},
		{
			MethodName: "BatchDeleteComments",
			Handler:    _DiscussionService_BatchDeleteComments_Handler,
		},
		{
			MethodName: "BatchPatchComments",
			Handler:    _DiscussionService_BatchPatchComments_Handler,
		},
		{
			MethodName: "GetCommentReplyCount",
			Handler:    _DiscussionService_GetCommentReplyCount_Handler,
		},
		{
			MethodName: "LikeComment",
			Handler:    _DiscussionService_LikeComment_Handler,
		},
		{
			MethodName: "GetUserLikeComment",
			Handler:    _DiscussionService_GetUserLikeComment_Handler,
		},
		{
			MethodName: "ListTalks",
			Handler:    _DiscussionService_ListTalks_Handler,
		},
		{
			MethodName: "GetTalk",
			Handler:    _DiscussionService_GetTalk_Handler,
		},
		{
			MethodName: "CreateTalk",
			Handler:    _DiscussionService_CreateTalk_Handler,
		},
		{
			MethodName: "UpdateTalk",
			Handler:    _DiscussionService_UpdateTalk_Handler,
		},
		{
			MethodName: "BatchDeleteTalks",
			Handler:    _DiscussionService_BatchDeleteTalks_Handler,
		},
		{
			MethodName: "LikeTalk",
			Handler:    _DiscussionService_LikeTalk_Handler,
		},
		{
			MethodName: "GetUserLikeTalk",
			Handler:    _DiscussionService_GetUserLikeTalk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discussion.proto",
}
