// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: chat.proto

package chatservice

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/chatrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchDeleteChatsRequest  = chatrpc.BatchDeleteChatsRequest
	BatchDeleteChatsResponse = chatrpc.BatchDeleteChatsResponse
	Chat                     = chatrpc.Chat
	CreateChatRequest        = chatrpc.CreateChatRequest
	CreateChatResponse       = chatrpc.CreateChatResponse
	GetChatRequest           = chatrpc.GetChatRequest
	GetChatResponse          = chatrpc.GetChatResponse
	ListChatsRequest         = chatrpc.ListChatsRequest
	ListChatsResponse        = chatrpc.ListChatsResponse
	ListResult               = chatrpc.ListResult
	UpdateChatRequest        = chatrpc.UpdateChatRequest
	UpdateChatResponse       = chatrpc.UpdateChatResponse

	ChatService interface {
		// 查询聊天记录列表
		ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error)
		// 查询聊天记录
		GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*GetChatResponse, error)
		// 创建聊天记录
		CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*CreateChatResponse, error)
		// 更新聊天记录
		UpdateChat(ctx context.Context, in *UpdateChatRequest, opts ...grpc.CallOption) (*UpdateChatResponse, error)
		// 批量删除聊天记录
		BatchDeleteChats(ctx context.Context, in *BatchDeleteChatsRequest, opts ...grpc.CallOption) (*BatchDeleteChatsResponse, error)
	}

	defaultChatService struct {
		cli zrpc.Client
	}
)

func NewChatService(cli zrpc.Client) ChatService {
	return &defaultChatService{
		cli: cli,
	}
}

// 查询聊天记录列表
func (m *defaultChatService) ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error) {
	client := chatrpc.NewChatServiceClient(m.cli.Conn())
	return client.ListChats(ctx, in, opts...)
}

// 查询聊天记录
func (m *defaultChatService) GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*GetChatResponse, error) {
	client := chatrpc.NewChatServiceClient(m.cli.Conn())
	return client.GetChat(ctx, in, opts...)
}

// 创建聊天记录
func (m *defaultChatService) CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*CreateChatResponse, error) {
	client := chatrpc.NewChatServiceClient(m.cli.Conn())
	return client.CreateChat(ctx, in, opts...)
}

// 更新聊天记录
func (m *defaultChatService) UpdateChat(ctx context.Context, in *UpdateChatRequest, opts ...grpc.CallOption) (*UpdateChatResponse, error) {
	client := chatrpc.NewChatServiceClient(m.cli.Conn())
	return client.UpdateChat(ctx, in, opts...)
}

// 批量删除聊天记录
func (m *defaultChatService) BatchDeleteChats(ctx context.Context, in *BatchDeleteChatsRequest, opts ...grpc.CallOption) (*BatchDeleteChatsResponse, error) {
	client := chatrpc.NewChatServiceClient(m.cli.Conn())
	return client.BatchDeleteChats(ctx, in, opts...)
}
