// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: syslog.proto

package server

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/logic/syslogservice"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/syslogrpc"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/svc"
)

type SyslogServiceServer struct {
	svcCtx *svc.ServiceContext
	syslogrpc.UnimplementedSyslogServiceServer
}

func NewSyslogServiceServer(svcCtx *svc.ServiceContext) *SyslogServiceServer {
	return &SyslogServiceServer{
		svcCtx: svcCtx,
	}
}

// 分页查询用户登录日志
func (s *SyslogServiceServer) ListLoginLogs(ctx context.Context, in *syslogrpc.ListLoginLogsRequest) (*syslogrpc.ListLoginLogsResponse, error) {
	l := syslogservicelogic.NewListLoginLogsLogic(ctx, s.svcCtx)
	return l.ListLoginLogs(in)
}

// 创建用户登录日志
func (s *SyslogServiceServer) CreateLoginLog(ctx context.Context, in *syslogrpc.CreateLoginLogRequest) (*syslogrpc.CreateLoginLogResponse, error) {
	l := syslogservicelogic.NewCreateLoginLogLogic(ctx, s.svcCtx)
	return l.CreateLoginLog(in)
}

// 批量删除用户登录日志
func (s *SyslogServiceServer) BatchDeleteLoginLogs(ctx context.Context, in *syslogrpc.BatchDeleteLoginLogsRequest) (*syslogrpc.BatchDeleteLoginLogsResponse, error) {
	l := syslogservicelogic.NewBatchDeleteLoginLogsLogic(ctx, s.svcCtx)
	return l.BatchDeleteLoginLogs(in)
}

// 分页查询操作日志
func (s *SyslogServiceServer) ListOperationLogs(ctx context.Context, in *syslogrpc.ListOperationLogsRequest) (*syslogrpc.ListOperationLogsResponse, error) {
	l := syslogservicelogic.NewListOperationLogsLogic(ctx, s.svcCtx)
	return l.ListOperationLogs(in)
}

// 创建操作日志
func (s *SyslogServiceServer) CreateOperationLog(ctx context.Context, in *syslogrpc.CreateOperationLogRequest) (*syslogrpc.CreateOperationLogResponse, error) {
	l := syslogservicelogic.NewCreateOperationLogLogic(ctx, s.svcCtx)
	return l.CreateOperationLog(in)
}

// 批量删除操作日志
func (s *SyslogServiceServer) BatchDeleteOperationLogs(ctx context.Context, in *syslogrpc.BatchDeleteOperationLogsRequest) (*syslogrpc.BatchDeleteOperationLogsResponse, error) {
	l := syslogservicelogic.NewBatchDeleteOperationLogsLogic(ctx, s.svcCtx)
	return l.BatchDeleteOperationLogs(in)
}

// 分页查询文件上传日志
func (s *SyslogServiceServer) ListUploadLogs(ctx context.Context, in *syslogrpc.ListUploadLogsRequest) (*syslogrpc.ListUploadLogsResponse, error) {
	l := syslogservicelogic.NewListUploadLogsLogic(ctx, s.svcCtx)
	return l.ListUploadLogs(in)
}

// 创建文件上传日志
func (s *SyslogServiceServer) CreateUploadLog(ctx context.Context, in *syslogrpc.CreateUploadLogRequest) (*syslogrpc.CreateUploadLogResponse, error) {
	l := syslogservicelogic.NewCreateUploadLogLogic(ctx, s.svcCtx)
	return l.CreateUploadLog(in)
}

// 批量删除文件上传日志
func (s *SyslogServiceServer) BatchDeleteUploadLogs(ctx context.Context, in *syslogrpc.BatchDeleteUploadLogsRequest) (*syslogrpc.BatchDeleteUploadLogsResponse, error) {
	l := syslogservicelogic.NewBatchDeleteUploadLogsLogic(ctx, s.svcCtx)
	return l.BatchDeleteUploadLogs(in)
}

// 分页查询访问日志
func (s *SyslogServiceServer) ListVisitLogs(ctx context.Context, in *syslogrpc.ListVisitLogsRequest) (*syslogrpc.ListVisitLogsResponse, error) {
	l := syslogservicelogic.NewListVisitLogsLogic(ctx, s.svcCtx)
	return l.ListVisitLogs(in)
}

// 创建访问日志
func (s *SyslogServiceServer) CreateVisitLog(ctx context.Context, in *syslogrpc.CreateVisitLogRequest) (*syslogrpc.CreateVisitLogResponse, error) {
	l := syslogservicelogic.NewCreateVisitLogLogic(ctx, s.svcCtx)
	return l.CreateVisitLog(in)
}

// 批量删除访问日志
func (s *SyslogServiceServer) BatchDeleteVisitLogs(ctx context.Context, in *syslogrpc.BatchDeleteVisitLogsRequest) (*syslogrpc.BatchDeleteVisitLogsResponse, error) {
	l := syslogservicelogic.NewBatchDeleteVisitLogsLogic(ctx, s.svcCtx)
	return l.BatchDeleteVisitLogs(in)
}
