// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: access.proto

package accessservice

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/accessrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Api                       = accessrpc.Api
	BatchDeleteApisRequest    = accessrpc.BatchDeleteApisRequest
	BatchDeleteApisResponse   = accessrpc.BatchDeleteApisResponse
	BatchDeleteMenusRequest   = accessrpc.BatchDeleteMenusRequest
	BatchDeleteMenusResponse  = accessrpc.BatchDeleteMenusResponse
	BatchDeleteRolesRequest   = accessrpc.BatchDeleteRolesRequest
	BatchDeleteRolesResponse  = accessrpc.BatchDeleteRolesResponse
	BatchGetUserRolesRequest  = accessrpc.BatchGetUserRolesRequest
	BatchGetUserRolesResponse = accessrpc.BatchGetUserRolesResponse
	CleanApisRequest          = accessrpc.CleanApisRequest
	CleanApisResponse         = accessrpc.CleanApisResponse
	CleanMenusRequest         = accessrpc.CleanMenusRequest
	CleanMenusResponse        = accessrpc.CleanMenusResponse
	CreateApiRequest          = accessrpc.CreateApiRequest
	CreateApiResponse         = accessrpc.CreateApiResponse
	CreateMenuRequest         = accessrpc.CreateMenuRequest
	CreateMenuResponse        = accessrpc.CreateMenuResponse
	CreateRoleRequest         = accessrpc.CreateRoleRequest
	CreateRoleResponse        = accessrpc.CreateRoleResponse
	GetRoleResourceRequest    = accessrpc.GetRoleResourceRequest
	GetRoleResourceResponse   = accessrpc.GetRoleResourceResponse
	GetUserApisRequest        = accessrpc.GetUserApisRequest
	GetUserApisResponse       = accessrpc.GetUserApisResponse
	GetUserMenusRequest       = accessrpc.GetUserMenusRequest
	GetUserMenusResponse      = accessrpc.GetUserMenusResponse
	ListApisRequest           = accessrpc.ListApisRequest
	ListApisResponse          = accessrpc.ListApisResponse
	ListMenusRequest          = accessrpc.ListMenusRequest
	ListMenusResponse         = accessrpc.ListMenusResponse
	ListQuery                 = accessrpc.ListQuery
	ListResult                = accessrpc.ListResult
	ListRolesRequest          = accessrpc.ListRolesRequest
	ListRolesResponse         = accessrpc.ListRolesResponse
	ListUserRolesRequest      = accessrpc.ListUserRolesRequest
	ListUserRolesResponse     = accessrpc.ListUserRolesResponse
	Menu                      = accessrpc.Menu
	MenuMeta                  = accessrpc.MenuMeta
	Role                      = accessrpc.Role
	SyncApisRequest           = accessrpc.SyncApisRequest
	SyncApisResponse          = accessrpc.SyncApisResponse
	SyncMenusRequest          = accessrpc.SyncMenusRequest
	SyncMenusResponse         = accessrpc.SyncMenusResponse
	UpdateApiRequest          = accessrpc.UpdateApiRequest
	UpdateApiResponse         = accessrpc.UpdateApiResponse
	UpdateMenuRequest         = accessrpc.UpdateMenuRequest
	UpdateMenuResponse        = accessrpc.UpdateMenuResponse
	UpdateRoleApiRequest      = accessrpc.UpdateRoleApiRequest
	UpdateRoleApiResponse     = accessrpc.UpdateRoleApiResponse
	UpdateRoleMenuRequest     = accessrpc.UpdateRoleMenuRequest
	UpdateRoleMenuResponse    = accessrpc.UpdateRoleMenuResponse
	UpdateRoleRequest         = accessrpc.UpdateRoleRequest
	UpdateRoleResponse        = accessrpc.UpdateRoleResponse
	UpdateUserRolesRequest    = accessrpc.UpdateUserRolesRequest
	UpdateUserRolesResponse   = accessrpc.UpdateUserRolesResponse
	UserRoles                 = accessrpc.UserRoles

	AccessService interface {
		// 分页查询 API 列表
		ListApis(ctx context.Context, in *ListApisRequest, opts ...grpc.CallOption) (*ListApisResponse, error)
		// 创建 API
		CreateApi(ctx context.Context, in *CreateApiRequest, opts ...grpc.CallOption) (*CreateApiResponse, error)
		// 更新 API
		UpdateApi(ctx context.Context, in *UpdateApiRequest, opts ...grpc.CallOption) (*UpdateApiResponse, error)
		// 批量删除 API
		BatchDeleteApis(ctx context.Context, in *BatchDeleteApisRequest, opts ...grpc.CallOption) (*BatchDeleteApisResponse, error)
		// 同步 API
		SyncApis(ctx context.Context, in *SyncApisRequest, opts ...grpc.CallOption) (*SyncApisResponse, error)
		// 清空 API
		CleanApis(ctx context.Context, in *CleanApisRequest, opts ...grpc.CallOption) (*CleanApisResponse, error)
		// 分页查询菜单列表
		ListMenus(ctx context.Context, in *ListMenusRequest, opts ...grpc.CallOption) (*ListMenusResponse, error)
		// 创建菜单
		CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*CreateMenuResponse, error)
		// 更新菜单
		UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*UpdateMenuResponse, error)
		// 批量删除菜单
		BatchDeleteMenus(ctx context.Context, in *BatchDeleteMenusRequest, opts ...grpc.CallOption) (*BatchDeleteMenusResponse, error)
		// 同步菜单
		SyncMenus(ctx context.Context, in *SyncMenusRequest, opts ...grpc.CallOption) (*SyncMenusResponse, error)
		// 清空菜单
		CleanMenus(ctx context.Context, in *CleanMenusRequest, opts ...grpc.CallOption) (*CleanMenusResponse, error)
		// 分页查询角色列表
		ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
		// 创建角色
		CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error)
		// 更新角色
		UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error)
		// 批量删除角色
		BatchDeleteRoles(ctx context.Context, in *BatchDeleteRolesRequest, opts ...grpc.CallOption) (*BatchDeleteRolesResponse, error)
		// 更新角色菜单资源
		UpdateRoleMenu(ctx context.Context, in *UpdateRoleMenuRequest, opts ...grpc.CallOption) (*UpdateRoleMenuResponse, error)
		// 更新角色 API 资源
		UpdateRoleApi(ctx context.Context, in *UpdateRoleApiRequest, opts ...grpc.CallOption) (*UpdateRoleApiResponse, error)
		// 查询角色资源
		GetRoleResource(ctx context.Context, in *GetRoleResourceRequest, opts ...grpc.CallOption) (*GetRoleResourceResponse, error)
		// 更新用户角色
		UpdateUserRoles(ctx context.Context, in *UpdateUserRolesRequest, opts ...grpc.CallOption) (*UpdateUserRolesResponse, error)
		// 查询用户 API 权限
		GetUserApis(ctx context.Context, in *GetUserApisRequest, opts ...grpc.CallOption) (*GetUserApisResponse, error)
		// 查询用户菜单权限
		GetUserMenus(ctx context.Context, in *GetUserMenusRequest, opts ...grpc.CallOption) (*GetUserMenusResponse, error)
		// 查询用户角色
		ListUserRoles(ctx context.Context, in *ListUserRolesRequest, opts ...grpc.CallOption) (*ListUserRolesResponse, error)
		// 批量查询用户角色
		BatchGetUserRoles(ctx context.Context, in *BatchGetUserRolesRequest, opts ...grpc.CallOption) (*BatchGetUserRolesResponse, error)
	}

	defaultAccessService struct {
		cli zrpc.Client
	}
)

func NewAccessService(cli zrpc.Client) AccessService {
	return &defaultAccessService{
		cli: cli,
	}
}

// 分页查询 API 列表
func (m *defaultAccessService) ListApis(ctx context.Context, in *ListApisRequest, opts ...grpc.CallOption) (*ListApisResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.ListApis(ctx, in, opts...)
}

// 创建 API
func (m *defaultAccessService) CreateApi(ctx context.Context, in *CreateApiRequest, opts ...grpc.CallOption) (*CreateApiResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.CreateApi(ctx, in, opts...)
}

// 更新 API
func (m *defaultAccessService) UpdateApi(ctx context.Context, in *UpdateApiRequest, opts ...grpc.CallOption) (*UpdateApiResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.UpdateApi(ctx, in, opts...)
}

// 批量删除 API
func (m *defaultAccessService) BatchDeleteApis(ctx context.Context, in *BatchDeleteApisRequest, opts ...grpc.CallOption) (*BatchDeleteApisResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.BatchDeleteApis(ctx, in, opts...)
}

// 同步 API
func (m *defaultAccessService) SyncApis(ctx context.Context, in *SyncApisRequest, opts ...grpc.CallOption) (*SyncApisResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.SyncApis(ctx, in, opts...)
}

// 清空 API
func (m *defaultAccessService) CleanApis(ctx context.Context, in *CleanApisRequest, opts ...grpc.CallOption) (*CleanApisResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.CleanApis(ctx, in, opts...)
}

// 分页查询菜单列表
func (m *defaultAccessService) ListMenus(ctx context.Context, in *ListMenusRequest, opts ...grpc.CallOption) (*ListMenusResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.ListMenus(ctx, in, opts...)
}

// 创建菜单
func (m *defaultAccessService) CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*CreateMenuResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.CreateMenu(ctx, in, opts...)
}

// 更新菜单
func (m *defaultAccessService) UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*UpdateMenuResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

// 批量删除菜单
func (m *defaultAccessService) BatchDeleteMenus(ctx context.Context, in *BatchDeleteMenusRequest, opts ...grpc.CallOption) (*BatchDeleteMenusResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.BatchDeleteMenus(ctx, in, opts...)
}

// 同步菜单
func (m *defaultAccessService) SyncMenus(ctx context.Context, in *SyncMenusRequest, opts ...grpc.CallOption) (*SyncMenusResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.SyncMenus(ctx, in, opts...)
}

// 清空菜单
func (m *defaultAccessService) CleanMenus(ctx context.Context, in *CleanMenusRequest, opts ...grpc.CallOption) (*CleanMenusResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.CleanMenus(ctx, in, opts...)
}

// 分页查询角色列表
func (m *defaultAccessService) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.ListRoles(ctx, in, opts...)
}

// 创建角色
func (m *defaultAccessService) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

// 更新角色
func (m *defaultAccessService) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

// 批量删除角色
func (m *defaultAccessService) BatchDeleteRoles(ctx context.Context, in *BatchDeleteRolesRequest, opts ...grpc.CallOption) (*BatchDeleteRolesResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.BatchDeleteRoles(ctx, in, opts...)
}

// 更新角色菜单资源
func (m *defaultAccessService) UpdateRoleMenu(ctx context.Context, in *UpdateRoleMenuRequest, opts ...grpc.CallOption) (*UpdateRoleMenuResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.UpdateRoleMenu(ctx, in, opts...)
}

// 更新角色 API 资源
func (m *defaultAccessService) UpdateRoleApi(ctx context.Context, in *UpdateRoleApiRequest, opts ...grpc.CallOption) (*UpdateRoleApiResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.UpdateRoleApi(ctx, in, opts...)
}

// 查询角色资源
func (m *defaultAccessService) GetRoleResource(ctx context.Context, in *GetRoleResourceRequest, opts ...grpc.CallOption) (*GetRoleResourceResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.GetRoleResource(ctx, in, opts...)
}

// 更新用户角色
func (m *defaultAccessService) UpdateUserRoles(ctx context.Context, in *UpdateUserRolesRequest, opts ...grpc.CallOption) (*UpdateUserRolesResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.UpdateUserRoles(ctx, in, opts...)
}

// 查询用户 API 权限
func (m *defaultAccessService) GetUserApis(ctx context.Context, in *GetUserApisRequest, opts ...grpc.CallOption) (*GetUserApisResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.GetUserApis(ctx, in, opts...)
}

// 查询用户菜单权限
func (m *defaultAccessService) GetUserMenus(ctx context.Context, in *GetUserMenusRequest, opts ...grpc.CallOption) (*GetUserMenusResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.GetUserMenus(ctx, in, opts...)
}

// 查询用户角色
func (m *defaultAccessService) ListUserRoles(ctx context.Context, in *ListUserRolesRequest, opts ...grpc.CallOption) (*ListUserRolesResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.ListUserRoles(ctx, in, opts...)
}

// 批量查询用户角色
func (m *defaultAccessService) BatchGetUserRoles(ctx context.Context, in *BatchGetUserRolesRequest, opts ...grpc.CallOption) (*BatchGetUserRolesResponse, error) {
	client := accessrpc.NewAccessServiceClient(m.cli.Conn())
	return client.BatchGetUserRoles(ctx, in, opts...)
}
