// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: auth.proto

package authservice

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/authrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetOAuthAuthorizeUrlRequest  = authrpc.GetOAuthAuthorizeUrlRequest
	GetOAuthAuthorizeUrlResponse = authrpc.GetOAuthAuthorizeUrlResponse
	LoginByEmailRequest          = authrpc.LoginByEmailRequest
	LoginByMobileRequest         = authrpc.LoginByMobileRequest
	LoginByOAuthRequest          = authrpc.LoginByOAuthRequest
	LoginByPasswordRequest       = authrpc.LoginByPasswordRequest
	LoginResponse                = authrpc.LoginResponse
	LogoutRequest                = authrpc.LogoutRequest
	LogoutResponse               = authrpc.LogoutResponse
	RegisterRequest              = authrpc.RegisterRequest
	RegisterResponse             = authrpc.RegisterResponse
	ResetPasswordRequest         = authrpc.ResetPasswordRequest
	ResetPasswordResponse        = authrpc.ResetPasswordResponse

	AuthService interface {
		// 密码登录
		LoginByPassword(ctx context.Context, in *LoginByPasswordRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// 邮箱验证码登录
		LoginByEmail(ctx context.Context, in *LoginByEmailRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// 手机验证码登录
		LoginByMobile(ctx context.Context, in *LoginByMobileRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// 第三方平台登录
		LoginByOAuth(ctx context.Context, in *LoginByOAuthRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// 用户注册
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		// 退出登录
		Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
		// 重置密码
		ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
		// 获取第三方OAuth授权地址
		GetOAuthAuthorizeUrl(ctx context.Context, in *GetOAuthAuthorizeUrlRequest, opts ...grpc.CallOption) (*GetOAuthAuthorizeUrlResponse, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

// 密码登录
func (m *defaultAuthService) LoginByPassword(ctx context.Context, in *LoginByPasswordRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := authrpc.NewAuthServiceClient(m.cli.Conn())
	return client.LoginByPassword(ctx, in, opts...)
}

// 邮箱验证码登录
func (m *defaultAuthService) LoginByEmail(ctx context.Context, in *LoginByEmailRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := authrpc.NewAuthServiceClient(m.cli.Conn())
	return client.LoginByEmail(ctx, in, opts...)
}

// 手机验证码登录
func (m *defaultAuthService) LoginByMobile(ctx context.Context, in *LoginByMobileRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := authrpc.NewAuthServiceClient(m.cli.Conn())
	return client.LoginByMobile(ctx, in, opts...)
}

// 第三方平台登录
func (m *defaultAuthService) LoginByOAuth(ctx context.Context, in *LoginByOAuthRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := authrpc.NewAuthServiceClient(m.cli.Conn())
	return client.LoginByOAuth(ctx, in, opts...)
}

// 用户注册
func (m *defaultAuthService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := authrpc.NewAuthServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 退出登录
func (m *defaultAuthService) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	client := authrpc.NewAuthServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// 重置密码
func (m *defaultAuthService) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	client := authrpc.NewAuthServiceClient(m.cli.Conn())
	return client.ResetPassword(ctx, in, opts...)
}

// 获取第三方OAuth授权地址
func (m *defaultAuthService) GetOAuthAuthorizeUrl(ctx context.Context, in *GetOAuthAuthorizeUrlRequest, opts ...grpc.CallOption) (*GetOAuthAuthorizeUrlResponse, error) {
	client := authrpc.NewAuthServiceClient(m.cli.Conn())
	return client.GetOAuthAuthorizeUrl(ctx, in, opts...)
}
