// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: syslog.proto

package syslogrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SyslogService_ListLoginLogs_FullMethodName            = "/blog.syslog.v1.SyslogService/ListLoginLogs"
	SyslogService_CreateLoginLog_FullMethodName           = "/blog.syslog.v1.SyslogService/CreateLoginLog"
	SyslogService_BatchDeleteLoginLogs_FullMethodName     = "/blog.syslog.v1.SyslogService/BatchDeleteLoginLogs"
	SyslogService_ListOperationLogs_FullMethodName        = "/blog.syslog.v1.SyslogService/ListOperationLogs"
	SyslogService_CreateOperationLog_FullMethodName       = "/blog.syslog.v1.SyslogService/CreateOperationLog"
	SyslogService_BatchDeleteOperationLogs_FullMethodName = "/blog.syslog.v1.SyslogService/BatchDeleteOperationLogs"
	SyslogService_ListUploadLogs_FullMethodName           = "/blog.syslog.v1.SyslogService/ListUploadLogs"
	SyslogService_CreateUploadLog_FullMethodName          = "/blog.syslog.v1.SyslogService/CreateUploadLog"
	SyslogService_BatchDeleteUploadLogs_FullMethodName    = "/blog.syslog.v1.SyslogService/BatchDeleteUploadLogs"
	SyslogService_ListVisitLogs_FullMethodName            = "/blog.syslog.v1.SyslogService/ListVisitLogs"
	SyslogService_CreateVisitLog_FullMethodName           = "/blog.syslog.v1.SyslogService/CreateVisitLog"
	SyslogService_BatchDeleteVisitLogs_FullMethodName     = "/blog.syslog.v1.SyslogService/BatchDeleteVisitLogs"
)

// SyslogServiceClient is the client API for SyslogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyslogServiceClient interface {
	// 分页查询用户登录日志
	ListLoginLogs(ctx context.Context, in *ListLoginLogsRequest, opts ...grpc.CallOption) (*ListLoginLogsResponse, error)
	// 创建用户登录日志
	CreateLoginLog(ctx context.Context, in *CreateLoginLogRequest, opts ...grpc.CallOption) (*CreateLoginLogResponse, error)
	// 批量删除用户登录日志
	BatchDeleteLoginLogs(ctx context.Context, in *BatchDeleteLoginLogsRequest, opts ...grpc.CallOption) (*BatchDeleteLoginLogsResponse, error)
	// 分页查询操作日志
	ListOperationLogs(ctx context.Context, in *ListOperationLogsRequest, opts ...grpc.CallOption) (*ListOperationLogsResponse, error)
	// 创建操作日志
	CreateOperationLog(ctx context.Context, in *CreateOperationLogRequest, opts ...grpc.CallOption) (*CreateOperationLogResponse, error)
	// 批量删除操作日志
	BatchDeleteOperationLogs(ctx context.Context, in *BatchDeleteOperationLogsRequest, opts ...grpc.CallOption) (*BatchDeleteOperationLogsResponse, error)
	// 分页查询文件上传日志
	ListUploadLogs(ctx context.Context, in *ListUploadLogsRequest, opts ...grpc.CallOption) (*ListUploadLogsResponse, error)
	// 创建文件上传日志
	CreateUploadLog(ctx context.Context, in *CreateUploadLogRequest, opts ...grpc.CallOption) (*CreateUploadLogResponse, error)
	// 批量删除文件上传日志
	BatchDeleteUploadLogs(ctx context.Context, in *BatchDeleteUploadLogsRequest, opts ...grpc.CallOption) (*BatchDeleteUploadLogsResponse, error)
	// 分页查询访问日志
	ListVisitLogs(ctx context.Context, in *ListVisitLogsRequest, opts ...grpc.CallOption) (*ListVisitLogsResponse, error)
	// 创建访问日志
	CreateVisitLog(ctx context.Context, in *CreateVisitLogRequest, opts ...grpc.CallOption) (*CreateVisitLogResponse, error)
	// 批量删除访问日志
	BatchDeleteVisitLogs(ctx context.Context, in *BatchDeleteVisitLogsRequest, opts ...grpc.CallOption) (*BatchDeleteVisitLogsResponse, error)
}

type syslogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyslogServiceClient(cc grpc.ClientConnInterface) SyslogServiceClient {
	return &syslogServiceClient{cc}
}

func (c *syslogServiceClient) ListLoginLogs(ctx context.Context, in *ListLoginLogsRequest, opts ...grpc.CallOption) (*ListLoginLogsResponse, error) {
	out := new(ListLoginLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_ListLoginLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) CreateLoginLog(ctx context.Context, in *CreateLoginLogRequest, opts ...grpc.CallOption) (*CreateLoginLogResponse, error) {
	out := new(CreateLoginLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_CreateLoginLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) BatchDeleteLoginLogs(ctx context.Context, in *BatchDeleteLoginLogsRequest, opts ...grpc.CallOption) (*BatchDeleteLoginLogsResponse, error) {
	out := new(BatchDeleteLoginLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_BatchDeleteLoginLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) ListOperationLogs(ctx context.Context, in *ListOperationLogsRequest, opts ...grpc.CallOption) (*ListOperationLogsResponse, error) {
	out := new(ListOperationLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_ListOperationLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) CreateOperationLog(ctx context.Context, in *CreateOperationLogRequest, opts ...grpc.CallOption) (*CreateOperationLogResponse, error) {
	out := new(CreateOperationLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_CreateOperationLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) BatchDeleteOperationLogs(ctx context.Context, in *BatchDeleteOperationLogsRequest, opts ...grpc.CallOption) (*BatchDeleteOperationLogsResponse, error) {
	out := new(BatchDeleteOperationLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_BatchDeleteOperationLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) ListUploadLogs(ctx context.Context, in *ListUploadLogsRequest, opts ...grpc.CallOption) (*ListUploadLogsResponse, error) {
	out := new(ListUploadLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_ListUploadLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) CreateUploadLog(ctx context.Context, in *CreateUploadLogRequest, opts ...grpc.CallOption) (*CreateUploadLogResponse, error) {
	out := new(CreateUploadLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_CreateUploadLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) BatchDeleteUploadLogs(ctx context.Context, in *BatchDeleteUploadLogsRequest, opts ...grpc.CallOption) (*BatchDeleteUploadLogsResponse, error) {
	out := new(BatchDeleteUploadLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_BatchDeleteUploadLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) ListVisitLogs(ctx context.Context, in *ListVisitLogsRequest, opts ...grpc.CallOption) (*ListVisitLogsResponse, error) {
	out := new(ListVisitLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_ListVisitLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) CreateVisitLog(ctx context.Context, in *CreateVisitLogRequest, opts ...grpc.CallOption) (*CreateVisitLogResponse, error) {
	out := new(CreateVisitLogResponse)
	err := c.cc.Invoke(ctx, SyslogService_CreateVisitLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syslogServiceClient) BatchDeleteVisitLogs(ctx context.Context, in *BatchDeleteVisitLogsRequest, opts ...grpc.CallOption) (*BatchDeleteVisitLogsResponse, error) {
	out := new(BatchDeleteVisitLogsResponse)
	err := c.cc.Invoke(ctx, SyslogService_BatchDeleteVisitLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyslogServiceServer is the server API for SyslogService service.
// All implementations must embed UnimplementedSyslogServiceServer
// for forward compatibility
type SyslogServiceServer interface {
	// 分页查询用户登录日志
	ListLoginLogs(context.Context, *ListLoginLogsRequest) (*ListLoginLogsResponse, error)
	// 创建用户登录日志
	CreateLoginLog(context.Context, *CreateLoginLogRequest) (*CreateLoginLogResponse, error)
	// 批量删除用户登录日志
	BatchDeleteLoginLogs(context.Context, *BatchDeleteLoginLogsRequest) (*BatchDeleteLoginLogsResponse, error)
	// 分页查询操作日志
	ListOperationLogs(context.Context, *ListOperationLogsRequest) (*ListOperationLogsResponse, error)
	// 创建操作日志
	CreateOperationLog(context.Context, *CreateOperationLogRequest) (*CreateOperationLogResponse, error)
	// 批量删除操作日志
	BatchDeleteOperationLogs(context.Context, *BatchDeleteOperationLogsRequest) (*BatchDeleteOperationLogsResponse, error)
	// 分页查询文件上传日志
	ListUploadLogs(context.Context, *ListUploadLogsRequest) (*ListUploadLogsResponse, error)
	// 创建文件上传日志
	CreateUploadLog(context.Context, *CreateUploadLogRequest) (*CreateUploadLogResponse, error)
	// 批量删除文件上传日志
	BatchDeleteUploadLogs(context.Context, *BatchDeleteUploadLogsRequest) (*BatchDeleteUploadLogsResponse, error)
	// 分页查询访问日志
	ListVisitLogs(context.Context, *ListVisitLogsRequest) (*ListVisitLogsResponse, error)
	// 创建访问日志
	CreateVisitLog(context.Context, *CreateVisitLogRequest) (*CreateVisitLogResponse, error)
	// 批量删除访问日志
	BatchDeleteVisitLogs(context.Context, *BatchDeleteVisitLogsRequest) (*BatchDeleteVisitLogsResponse, error)
	mustEmbedUnimplementedSyslogServiceServer()
}

// UnimplementedSyslogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSyslogServiceServer struct {
}

func (UnimplementedSyslogServiceServer) ListLoginLogs(context.Context, *ListLoginLogsRequest) (*ListLoginLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLoginLogs not implemented")
}
func (UnimplementedSyslogServiceServer) CreateLoginLog(context.Context, *CreateLoginLogRequest) (*CreateLoginLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoginLog not implemented")
}
func (UnimplementedSyslogServiceServer) BatchDeleteLoginLogs(context.Context, *BatchDeleteLoginLogsRequest) (*BatchDeleteLoginLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteLoginLogs not implemented")
}
func (UnimplementedSyslogServiceServer) ListOperationLogs(context.Context, *ListOperationLogsRequest) (*ListOperationLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOperationLogs not implemented")
}
func (UnimplementedSyslogServiceServer) CreateOperationLog(context.Context, *CreateOperationLogRequest) (*CreateOperationLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOperationLog not implemented")
}
func (UnimplementedSyslogServiceServer) BatchDeleteOperationLogs(context.Context, *BatchDeleteOperationLogsRequest) (*BatchDeleteOperationLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteOperationLogs not implemented")
}
func (UnimplementedSyslogServiceServer) ListUploadLogs(context.Context, *ListUploadLogsRequest) (*ListUploadLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUploadLogs not implemented")
}
func (UnimplementedSyslogServiceServer) CreateUploadLog(context.Context, *CreateUploadLogRequest) (*CreateUploadLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUploadLog not implemented")
}
func (UnimplementedSyslogServiceServer) BatchDeleteUploadLogs(context.Context, *BatchDeleteUploadLogsRequest) (*BatchDeleteUploadLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteUploadLogs not implemented")
}
func (UnimplementedSyslogServiceServer) ListVisitLogs(context.Context, *ListVisitLogsRequest) (*ListVisitLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVisitLogs not implemented")
}
func (UnimplementedSyslogServiceServer) CreateVisitLog(context.Context, *CreateVisitLogRequest) (*CreateVisitLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVisitLog not implemented")
}
func (UnimplementedSyslogServiceServer) BatchDeleteVisitLogs(context.Context, *BatchDeleteVisitLogsRequest) (*BatchDeleteVisitLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteVisitLogs not implemented")
}
func (UnimplementedSyslogServiceServer) mustEmbedUnimplementedSyslogServiceServer() {}

// UnsafeSyslogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyslogServiceServer will
// result in compilation errors.
type UnsafeSyslogServiceServer interface {
	mustEmbedUnimplementedSyslogServiceServer()
}

func RegisterSyslogServiceServer(s grpc.ServiceRegistrar, srv SyslogServiceServer) {
	s.RegisterService(&SyslogService_ServiceDesc, srv)
}

func _SyslogService_ListLoginLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoginLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).ListLoginLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_ListLoginLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).ListLoginLogs(ctx, req.(*ListLoginLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_CreateLoginLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoginLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).CreateLoginLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_CreateLoginLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).CreateLoginLog(ctx, req.(*CreateLoginLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_BatchDeleteLoginLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteLoginLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).BatchDeleteLoginLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_BatchDeleteLoginLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).BatchDeleteLoginLogs(ctx, req.(*BatchDeleteLoginLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_ListOperationLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperationLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).ListOperationLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_ListOperationLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).ListOperationLogs(ctx, req.(*ListOperationLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_CreateOperationLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOperationLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).CreateOperationLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_CreateOperationLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).CreateOperationLog(ctx, req.(*CreateOperationLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_BatchDeleteOperationLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteOperationLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).BatchDeleteOperationLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_BatchDeleteOperationLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).BatchDeleteOperationLogs(ctx, req.(*BatchDeleteOperationLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_ListUploadLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUploadLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).ListUploadLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_ListUploadLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).ListUploadLogs(ctx, req.(*ListUploadLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_CreateUploadLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).CreateUploadLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_CreateUploadLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).CreateUploadLog(ctx, req.(*CreateUploadLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_BatchDeleteUploadLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteUploadLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).BatchDeleteUploadLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_BatchDeleteUploadLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).BatchDeleteUploadLogs(ctx, req.(*BatchDeleteUploadLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_ListVisitLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVisitLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).ListVisitLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_ListVisitLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).ListVisitLogs(ctx, req.(*ListVisitLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_CreateVisitLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVisitLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).CreateVisitLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_CreateVisitLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).CreateVisitLog(ctx, req.(*CreateVisitLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyslogService_BatchDeleteVisitLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteVisitLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).BatchDeleteVisitLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyslogService_BatchDeleteVisitLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).BatchDeleteVisitLogs(ctx, req.(*BatchDeleteVisitLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyslogService_ServiceDesc is the grpc.ServiceDesc for SyslogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyslogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.syslog.v1.SyslogService",
	HandlerType: (*SyslogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLoginLogs",
			Handler:    _SyslogService_ListLoginLogs_Handler,
		},
		{
			MethodName: "CreateLoginLog",
			Handler:    _SyslogService_CreateLoginLog_Handler,
		},
		{
			MethodName: "BatchDeleteLoginLogs",
			Handler:    _SyslogService_BatchDeleteLoginLogs_Handler,
		},
		{
			MethodName: "ListOperationLogs",
			Handler:    _SyslogService_ListOperationLogs_Handler,
		},
		{
			MethodName: "CreateOperationLog",
			Handler:    _SyslogService_CreateOperationLog_Handler,
		},
		{
			MethodName: "BatchDeleteOperationLogs",
			Handler:    _SyslogService_BatchDeleteOperationLogs_Handler,
		},
		{
			MethodName: "ListUploadLogs",
			Handler:    _SyslogService_ListUploadLogs_Handler,
		},
		{
			MethodName: "CreateUploadLog",
			Handler:    _SyslogService_CreateUploadLog_Handler,
		},
		{
			MethodName: "BatchDeleteUploadLogs",
			Handler:    _SyslogService_BatchDeleteUploadLogs_Handler,
		},
		{
			MethodName: "ListVisitLogs",
			Handler:    _SyslogService_ListVisitLogs_Handler,
		},
		{
			MethodName: "CreateVisitLog",
			Handler:    _SyslogService_CreateVisitLog_Handler,
		},
		{
			MethodName: "BatchDeleteVisitLogs",
			Handler:    _SyslogService_BatchDeleteVisitLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syslog.proto",
}
