// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CleanMenuReq struct {
}

type CleanMenuResp struct {
	SuccessCount int64 `json:"success_count"` // 清空成功数量
}

type CreateMenuReq struct {
	ParentId  int64            `json:"parent_id"`         // 父id
	Path      string           `json:"path"`              // 路由地址
	Name      string           `json:"name"`              // 路由名字
	Component string           `json:"component"`         // Layout组件
	Redirect  string           `json:"redirect,optional"` // 路由重定向
	Children  []*CreateMenuReq `json:"children,optional"`
	MenuMeta
}

type DeleteMenuReq struct {
	Ids []int64 `json:"ids"` // 主键id
}

type GetMenuReq struct {
	Id int64 `path:"id"` // 主键
}

type MenuVO struct {
	Id        int64  `json:"id,optional"`       // 主键
	ParentId  int64  `json:"parent_id"`         // 父id
	Path      string `json:"path"`              // 路由地址
	Name      string `json:"name"`              // 路由名字
	Component string `json:"component"`         // Layout组件
	Redirect  string `json:"redirect,optional"` // 路由重定向
	MenuMeta
	CreatedAt int64     `json:"created_at"` // 创建时间
	UpdatedAt int64     `json:"updated_at"` // 更新时间
	Children  []*MenuVO `json:"children,optional"`
}

type QueryMenuListReq struct {
	ListQuery
	Name   *string `json:"name,optional"`   // 路由名字
	Title  *string `json:"title,optional"`  // 菜单标题
	Status *int64  `json:"status,optional"` // 状态
}

type SyncMenuReq struct {
	Menus []*CreateMenuReq `json:"menus"`
}

type SyncMenuResp struct {
	SuccessCount int64 `json:"success_count"` // 同步成功数量
}

type UpdateMenuReq struct {
	Id        int64  `path:"id"`                // 主键
	ParentId  int64  `json:"parent_id"`         // 父id
	Path      string `json:"path"`              // 路由地址
	Name      string `json:"name"`              // 路由名字
	Component string `json:"component"`         // Layout组件
	Redirect  string `json:"redirect,optional"` // 路由重定向
	MenuMeta
}
