// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type DeleteMessageReq struct {
	Ids []int64 `json:"ids"`
}

type PatchMessagesReq struct {
	Ids    []int64 `json:"ids"`
	Status int64   `json:"status"`
}

type QueryMessageListReq struct {
	ListQuery
	UserId *string `json:"user_id,optional"`
	Status *int64  `json:"status,optional"`
}
