// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type DeleteCommentReq struct {
	Ids []int64 `json:"ids"`
}

type PatchCommentsReq struct {
	Ids    []int64 `json:"ids"`
	Status int64   `json:"status"`
}

type QueryCommentListReq struct {
	ListQuery
	UserId *string `json:"user_id,optional"`
	Status *int64  `json:"status,optional"`
	Type   *int64  `json:"type,optional"`
}
