// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreatePhotoReq struct {
	AlbumId   int64  `json:"album_id"`
	PhotoName string `json:"photo_name"`
	PhotoDesc string `json:"photo_desc"`
	PhotoSrc  string `json:"photo_src"`
}

type DeletePhotoReq struct {
	Ids []int64 `json:"ids"`
}

type DestroyPhotoReq struct {
	Ids []int64 `json:"ids"`
}

type PhotoVO struct {
	Id        int64  `json:"id,optional"`
	AlbumId   int64  `json:"album_id"`
	PhotoName string `json:"photo_name"`
	PhotoDesc string `json:"photo_desc"`
	PhotoSrc  string `json:"photo_src"`
	IsDelete  int64  `json:"is_delete"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type QueryPhotoListReq struct {
	ListQuery
	AlbumId  *int64 `json:"album_id,optional"`
	IsDelete *int64 `json:"is_delete,optional"`
}

type RestorePhotoReq struct {
	Ids []int64 `json:"ids"`
}

type UpdatePhotoReq struct {
	Id        int64  `path:"id"`
	AlbumId   int64  `json:"album_id"`
	PhotoName string `json:"photo_name"`
	PhotoDesc string `json:"photo_desc"`
	PhotoSrc  string `json:"photo_src"`
}
