// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type NotifyStreamEvent struct {
	Event       string `json:"event"`
	MessageId   int64  `json:"message_id,optional"`
	Title       string `json:"title,optional"`
	Category    string `json:"category,optional"`
	Level       string `json:"level,optional"`
	PublishedAt int64  `json:"published_at,optional"`
}
