// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateNotifyMessageReq struct {
	Title      string `json:"title"`
	Content    string `json:"content"`
	Category   string `json:"category"`
	Level      string `json:"level"`
	TargetType string `json:"target_type"`
	TargetIds  string `json:"target_ids,optional"`
}

type DeleteNotifyMessageReq struct {
	Ids []int64 `json:"ids"`
}

type GetNotifyMessageReq struct {
	Id int64 `path:"id"`
}

type NotifyMessageVO struct {
	Id          int64  `json:"id,optional"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	Category    string `json:"category"`
	Level       string `json:"level"`
	TargetType  string `json:"target_type"`
	TargetIds   string `json:"target_ids"`
	Status      string `json:"status"`
	PublishedAt int64  `json:"published_at"`
	PublishedBy string `json:"published_by"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type PublishNotifyMessageReq struct {
	Id int64 `path:"id"`
}

type QueryNotifyMessageListReq struct {
	ListQuery
	Category   *string `json:"category,optional"`
	Level      *string `json:"level,optional"`
	Status     *string `json:"status,optional"`
	TargetType *string `json:"target_type,optional"`
}

type QueryUndeliveredNotifyMessagesReq struct {
	BeforeSeconds *int64 `json:"before_seconds,optional"`
	Limit         *int64 `json:"limit,optional"`
}

type RedeliverNotifyMessageReq struct {
	Id int64 `path:"id"`
}

type RevokeNotifyMessageReq struct {
	Id int64 `path:"id"`
}

type UpdateNotifyMessageReq struct {
	Id         int64  `path:"id"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	Category   string `json:"category"`
	Level      string `json:"level"`
	TargetType string `json:"target_type"`
	TargetIds  string `json:"target_ids,optional"`
}
