// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type GetArticleStatsResp struct {
	CategoryList      []*CategoryOverviewVO  `json:"category_list"`
	TagList           []*TagOverviewVO       `json:"tag_list"`
	ArticleViewRanks  []*ArticleViewVO       `json:"article_view_ranks"`
	ArticleStatistics []*ArticleStatisticsVO `json:"article_statistics"`
}

type GetGeoStatsReq struct {
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date,optional"`
}

type GetGeoStatsResp struct {
	Users    []*RegionStatVO `json:"users"`
	Visitors []*RegionStatVO `json:"visitors"`
}

type GetStatsDashboardResp struct {
	UserCount      int64           `json:"user_count"`
	ArticleCount   int64           `json:"article_count"`
	MessageCount   int64           `json:"message_count"`
	Today          *DashboardStats `json:"today"`
	UvGrowthRate   float64         `json:"uv_growth_rate"`
	PvGrowthRate   float64         `json:"pv_growth_rate"`
	UserGrowthRate float64         `json:"user_growth_rate"`
}

type GetVisitTrendReq struct {
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date,optional"`
}

type GetVisitTrendResp struct {
	List []*DashboardStats `json:"list"`
}

type Server struct {
	Os   interface{} `json:"os"`
	Cpu  interface{} `json:"cpu"`
	Ram  interface{} `json:"ram"`
	Disk interface{} `json:"disk"`
}
