// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type DeleteLoginLogReq struct {
	Ids []int64 `json:"ids"`
}

type QueryLoginLogListReq struct {
	ListQuery
	UserId    *string `json:"user_id,optional"`
	Status    *int64  `json:"status,optional"` // 登录状态：0-失败 1-成功
	StartDate *string `json:"start_date,optional"`
	EndDate   *string `json:"end_date,optional"`
}
