// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type DeleteOperationLogReq struct {
	Ids []int64 `json:"ids"`
}

type QueryOperationLogListReq struct {
	ListQuery
	UserId    *string `json:"user_id,optional"`
	Module    *string `json:"module,optional"`
	StartDate *string `json:"start_date,optional"`
	EndDate   *string `json:"end_date,optional"`
}
