// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: media.proto

package server

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/logic/mediaservice"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/mediarpc"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/svc"
)

type MediaServiceServer struct {
	svcCtx *svc.ServiceContext
	mediarpc.UnimplementedMediaServiceServer
}

func NewMediaServiceServer(svcCtx *svc.ServiceContext) *MediaServiceServer {
	return &MediaServiceServer{
		svcCtx: svcCtx,
	}
}

// 分页查询照片列表
func (s *MediaServiceServer) ListPhotos(ctx context.Context, in *mediarpc.ListPhotosRequest) (*mediarpc.ListPhotosResponse, error) {
	l := mediaservicelogic.NewListPhotosLogic(ctx, s.svcCtx)
	return l.ListPhotos(in)
}

// 创建照片
func (s *MediaServiceServer) CreatePhoto(ctx context.Context, in *mediarpc.CreatePhotoRequest) (*mediarpc.CreatePhotoResponse, error) {
	l := mediaservicelogic.NewCreatePhotoLogic(ctx, s.svcCtx)
	return l.CreatePhoto(in)
}

// 更新照片
func (s *MediaServiceServer) UpdatePhoto(ctx context.Context, in *mediarpc.UpdatePhotoRequest) (*mediarpc.UpdatePhotoResponse, error) {
	l := mediaservicelogic.NewUpdatePhotoLogic(ctx, s.svcCtx)
	return l.UpdatePhoto(in)
}

// 部分更新照片
func (s *MediaServiceServer) BatchPatchPhotos(ctx context.Context, in *mediarpc.BatchPatchPhotosRequest) (*mediarpc.BatchPatchPhotosResponse, error) {
	l := mediaservicelogic.NewBatchPatchPhotosLogic(ctx, s.svcCtx)
	return l.BatchPatchPhotos(in)
}

// 批量销毁照片（彻底删除，不可恢复）
func (s *MediaServiceServer) BatchDestroyPhotos(ctx context.Context, in *mediarpc.BatchDestroyPhotosRequest) (*mediarpc.BatchDestroyPhotosResponse, error) {
	l := mediaservicelogic.NewBatchDestroyPhotosLogic(ctx, s.svcCtx)
	return l.BatchDestroyPhotos(in)
}

// 分页查询相册列表
func (s *MediaServiceServer) ListAlbums(ctx context.Context, in *mediarpc.ListAlbumsRequest) (*mediarpc.ListAlbumsResponse, error) {
	l := mediaservicelogic.NewListAlbumsLogic(ctx, s.svcCtx)
	return l.ListAlbums(in)
}

// 查询相册详情
func (s *MediaServiceServer) GetAlbum(ctx context.Context, in *mediarpc.GetAlbumRequest) (*mediarpc.GetAlbumResponse, error) {
	l := mediaservicelogic.NewGetAlbumLogic(ctx, s.svcCtx)
	return l.GetAlbum(in)
}

// 创建相册
func (s *MediaServiceServer) CreateAlbum(ctx context.Context, in *mediarpc.CreateAlbumRequest) (*mediarpc.CreateAlbumResponse, error) {
	l := mediaservicelogic.NewCreateAlbumLogic(ctx, s.svcCtx)
	return l.CreateAlbum(in)
}

// 更新相册
func (s *MediaServiceServer) UpdateAlbum(ctx context.Context, in *mediarpc.UpdateAlbumRequest) (*mediarpc.UpdateAlbumResponse, error) {
	l := mediaservicelogic.NewUpdateAlbumLogic(ctx, s.svcCtx)
	return l.UpdateAlbum(in)
}

// 部分更新相册
func (s *MediaServiceServer) BatchPatchAlbums(ctx context.Context, in *mediarpc.BatchPatchAlbumsRequest) (*mediarpc.BatchPatchAlbumsResponse, error) {
	l := mediaservicelogic.NewBatchPatchAlbumsLogic(ctx, s.svcCtx)
	return l.BatchPatchAlbums(in)
}

// 批量销毁相册（彻底删除，不可恢复）
func (s *MediaServiceServer) BatchDestroyAlbums(ctx context.Context, in *mediarpc.BatchDestroyAlbumsRequest) (*mediarpc.BatchDestroyAlbumsResponse, error) {
	l := mediaservicelogic.NewBatchDestroyAlbumsLogic(ctx, s.svcCtx)
	return l.BatchDestroyAlbums(in)
}
