// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: guest.proto

package server

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/logic/guestservice"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/guestrpc"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/svc"
)

type GuestServiceServer struct {
	svcCtx *svc.ServiceContext
	guestrpc.UnimplementedGuestServiceServer
}

func NewGuestServiceServer(svcCtx *svc.ServiceContext) *GuestServiceServer {
	return &GuestServiceServer{
		svcCtx: svcCtx,
	}
}

// 分页查询游客信息列表
func (s *GuestServiceServer) ListGuests(ctx context.Context, in *guestrpc.ListGuestsRequest) (*guestrpc.ListGuestsResponse, error) {
	l := guestservicelogic.NewListGuestsLogic(ctx, s.svcCtx)
	return l.ListGuests(in)
}

// 获取游客环境信息
func (s *GuestServiceServer) GetGuest(ctx context.Context, in *guestrpc.GetGuestRequest) (*guestrpc.GetGuestResponse, error) {
	l := guestservicelogic.NewGetGuestLogic(ctx, s.svcCtx)
	return l.GetGuest(in)
}
