// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	accessapi "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/access/api"
	accessmenu "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/access/menu"
	accessrole "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/access/role"
	accountauth "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/account/auth"
	accountguest "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/account/guest"
	accountme "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/account/me"
	accountuser "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/account/user"
	commonupload "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/common/upload"
	commonwebsocket "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/common/websocket"
	contentarticle "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/content/article"
	contentcategory "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/content/category"
	contenttag "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/content/tag"
	discussioncomment "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/discussion/comment"
	discussionmessage "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/discussion/message"
	discussiontalk "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/discussion/talk"
	mediaalbum "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/media/album"
	mediaphoto "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/media/photo"
	notificationnotify_message "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/notification/notify_message"
	notificationnotify_record "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/notification/notify_record"
	notificationnotify_template "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/notification/notify_template"
	siteconfig "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/site/config"
	sitefriend "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/site/friend"
	sitepage "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/site/page"
	statsoverview "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/stats/overview"
	sysloglogin_log "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/syslog/login_log"
	syslogoperation_log "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/syslog/operation_log"
	syslogupload_log "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/syslog/upload_log"
	syslogvisit_log "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/syslog/visit_log"
	"github.com/ve-weiyi/blog-cloud/api/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// ping
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: PingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取接口列表
					Method:  http.MethodGet,
					Path:    "/apis",
					Handler: accessapi.QueryApiListHandler(serverCtx),
				},
				{
					// 创建接口
					Method:  http.MethodPost,
					Path:    "/apis",
					Handler: accessapi.CreateApiHandler(serverCtx),
				},
				{
					// 获取接口详情
					Method:  http.MethodGet,
					Path:    "/apis/:id",
					Handler: accessapi.GetApiHandler(serverCtx),
				},
				{
					// 更新接口
					Method:  http.MethodPut,
					Path:    "/apis/:id",
					Handler: accessapi.UpdateApiHandler(serverCtx),
				},
				{
					// 批量删除接口
					Method:  http.MethodPost,
					Path:    "/apis/batch-delete",
					Handler: accessapi.BatchDeleteApiHandler(serverCtx),
				},
				{
					// 清空接口列表
					Method:  http.MethodPost,
					Path:    "/apis/clean",
					Handler: accessapi.CleanApiHandler(serverCtx),
				},
				{
					// 同步接口列表
					Method:  http.MethodPost,
					Path:    "/apis/sync",
					Handler: accessapi.SyncApiHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取菜单列表
					Method:  http.MethodGet,
					Path:    "/menus",
					Handler: accessmenu.QueryMenuListHandler(serverCtx),
				},
				{
					// 创建菜单
					Method:  http.MethodPost,
					Path:    "/menus",
					Handler: accessmenu.CreateMenuHandler(serverCtx),
				},
				{
					// 获取菜单详情
					Method:  http.MethodGet,
					Path:    "/menus/:id",
					Handler: accessmenu.GetMenuHandler(serverCtx),
				},
				{
					// 更新菜单
					Method:  http.MethodPut,
					Path:    "/menus/:id",
					Handler: accessmenu.UpdateMenuHandler(serverCtx),
				},
				{
					// 批量删除菜单
					Method:  http.MethodPost,
					Path:    "/menus/batch-delete",
					Handler: accessmenu.BatchDeleteMenuHandler(serverCtx),
				},
				{
					// 清空菜单列表
					Method:  http.MethodPost,
					Path:    "/menus/clean",
					Handler: accessmenu.CleanMenuHandler(serverCtx),
				},
				{
					// 同步菜单列表
					Method:  http.MethodPost,
					Path:    "/menus/sync",
					Handler: accessmenu.SyncMenuHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取角色列表
					Method:  http.MethodGet,
					Path:    "/roles",
					Handler: accessrole.QueryRoleListHandler(serverCtx),
				},
				{
					// 创建角色
					Method:  http.MethodPost,
					Path:    "/roles",
					Handler: accessrole.CreateRoleHandler(serverCtx),
				},
				{
					// 获取角色详情
					Method:  http.MethodGet,
					Path:    "/roles/:id",
					Handler: accessrole.GetRoleHandler(serverCtx),
				},
				{
					// 更新角色信息
					Method:  http.MethodPut,
					Path:    "/roles/:id",
					Handler: accessrole.UpdateRoleHandler(serverCtx),
				},
				{
					// 更新角色接口权限
					Method:  http.MethodPut,
					Path:    "/roles/:role_id/apis",
					Handler: accessrole.UpdateRoleApiPermissionsHandler(serverCtx),
				},
				{
					// 更新角色菜单权限
					Method:  http.MethodPut,
					Path:    "/roles/:role_id/menus",
					Handler: accessrole.UpdateRoleMenuPermissionsHandler(serverCtx),
				},
				{
					// 查询角色权限配置
					Method:  http.MethodGet,
					Path:    "/roles/:role_id/permissions",
					Handler: accessrole.GetRolePermissionsHandler(serverCtx),
				},
				{
					// 批量删除角色
					Method:  http.MethodPost,
					Path:    "/roles/batch-delete",
					Handler: accessrole.BatchDeleteRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取验证码
				Method:  http.MethodGet,
				Path:    "/auth/captchas",
				Handler: accountauth.GetCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					// 发送邮箱验证码
					Method:  http.MethodPost,
					Path:    "/auth/email-verification-codes",
					Handler: accountauth.SendEmailCodeHandler(serverCtx),
				},
				{
					// 邮箱验证码登录（仅登录）
					Method:  http.MethodPost,
					Path:    "/auth/login-by-email",
					Handler: accountauth.EmailLoginHandler(serverCtx),
				},
				{
					// 手机验证码登录（自动注册）
					Method:  http.MethodPost,
					Path:    "/auth/login-by-mobile",
					Handler: accountauth.MobileLoginHandler(serverCtx),
				},
				{
					// 密码登录（账号/手机号/邮箱）
					Method:  http.MethodPost,
					Path:    "/auth/login-by-password",
					Handler: accountauth.PasswordLoginHandler(serverCtx),
				},
				{
					// 发送手机验证码
					Method:  http.MethodPost,
					Path:    "/auth/mobile-verification-codes",
					Handler: accountauth.SendMobileCodeHandler(serverCtx),
				},
				{
					// 获取第三方授权URL
					Method:  http.MethodGet,
					Path:    "/auth/oauth/:platform/authorize",
					Handler: accountauth.GetOauthAuthorizeUrlHandler(serverCtx),
				},
				{
					// 第三方登录（自动注册）
					Method:  http.MethodPost,
					Path:    "/auth/oauth/:platform/login",
					Handler: accountauth.OauthLoginHandler(serverCtx),
				},
				{
					// 重置密码
					Method:  http.MethodPost,
					Path:    "/auth/password-resets",
					Handler: accountauth.ResetPasswordHandler(serverCtx),
				},
				{
					// 刷新token
					Method:  http.MethodPost,
					Path:    "/auth/refresh-token",
					Handler: accountauth.RefreshTokenHandler(serverCtx),
				},
				{
					// 邮箱注册
					Method:  http.MethodPost,
					Path:    "/auth/register",
					Handler: accountauth.RegisterHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					// 退出登录（需登录）
					Method:  http.MethodDelete,
					Path:    "/auth/session",
					Handler: accountauth.LogoutHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取游客信息
				Method:  http.MethodGet,
				Path:    "/guests/current",
				Handler: accountguest.GetGuestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取访客列表
					Method:  http.MethodGet,
					Path:    "/guests",
					Handler: accountguest.QueryGuestListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					// 获取用户接口权限
					Method:  http.MethodGet,
					Path:    "/me/apis",
					Handler: accountme.GetMeApisHandler(serverCtx),
				},
				{
					// 修改用户头像
					Method:  http.MethodPut,
					Path:    "/me/avatar",
					Handler: accountme.UpdateMeAvatarHandler(serverCtx),
				},
				{
					// 绑定邮箱
					Method:  http.MethodPost,
					Path:    "/me/bind-email",
					Handler: accountme.BindMeEmailHandler(serverCtx),
				},
				{
					// 绑定手机号
					Method:  http.MethodPost,
					Path:    "/me/bind-mobile",
					Handler: accountme.BindMeMobileHandler(serverCtx),
				},
				{
					// 绑定第三方平台账号
					Method:  http.MethodPost,
					Path:    "/me/bind-third-party",
					Handler: accountme.BindMeThirdPartyHandler(serverCtx),
				},
				{
					// 查询用户登录历史
					Method:  http.MethodGet,
					Path:    "/me/login-logs",
					Handler: accountme.QueryMeLoginLogListHandler(serverCtx),
				},
				{
					// 获取用户菜单权限
					Method:  http.MethodGet,
					Path:    "/me/menus",
					Handler: accountme.GetMeMenusHandler(serverCtx),
				},
				{
					// 修改用户密码
					Method:  http.MethodPut,
					Path:    "/me/password",
					Handler: accountme.UpdateMePasswordHandler(serverCtx),
				},
				{
					// 获取当前用户信息
					Method:  http.MethodGet,
					Path:    "/me/profile",
					Handler: accountme.GetMeHandler(serverCtx),
				},
				{
					// 更新当前用户信息
					Method:  http.MethodPut,
					Path:    "/me/profile",
					Handler: accountme.UpdateMeHandler(serverCtx),
				},
				{
					// 获取用户角色
					Method:  http.MethodGet,
					Path:    "/me/roles",
					Handler: accountme.GetMeRolesHandler(serverCtx),
				},
				{
					// 解绑第三方平台账号
					Method:  http.MethodPost,
					Path:    "/me/unbind-third-party",
					Handler: accountme.UnbindMeThirdPartyHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取用户列表
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: accountuser.QueryUserListHandler(serverCtx),
				},
				{
					// 获取用户详情
					Method:  http.MethodGet,
					Path:    "/users/:user_id",
					Handler: accountuser.GetUserDetailHandler(serverCtx),
				},
				{
					// 更新用户状态
					Method:  http.MethodPatch,
					Path:    "/users/:user_id",
					Handler: accountuser.UpdateUserStatusHandler(serverCtx),
				},
				{
					// 重置用户密码
					Method:  http.MethodPost,
					Path:    "/users/:user_id/reset-password",
					Handler: accountuser.ResetUserPasswordHandler(serverCtx),
				},
				{
					// 更新用户角色
					Method:  http.MethodPut,
					Path:    "/users/:user_id/roles",
					Handler: accountuser.UpdateUserRolesHandler(serverCtx),
				},
				{
					// 获取在线用户列表
					Method:  http.MethodGet,
					Path:    "/users/online",
					Handler: accountuser.GetOnlineUsersHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 上传文件（服务端上传）
					Method:  http.MethodPost,
					Path:    "/files",
					Handler: commonupload.UploadFileHandler(serverCtx),
				},
				{
					// 查询上传文件列表
					Method:  http.MethodGet,
					Path:    "/files",
					Handler: commonupload.QueryFileListHandler(serverCtx),
				},
				{
					// 获取上传凭证（前端直传）
					Method:  http.MethodPost,
					Path:    "/upload-tokens",
					Handler: commonupload.CreateUploadTokenHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
		rest.WithMaxBytes(10485760),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// WebSocket消息
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler: commonwebsocket.WebsocketHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取文章列表
					Method:  http.MethodGet,
					Path:    "/articles",
					Handler: contentarticle.QueryArticleListHandler(serverCtx),
				},
				{
					// 创建文章
					Method:  http.MethodPost,
					Path:    "/articles",
					Handler: contentarticle.CreateArticleHandler(serverCtx),
				},
				{
					// 获取文章详情
					Method:  http.MethodGet,
					Path:    "/articles/:id",
					Handler: contentarticle.GetArticleHandler(serverCtx),
				},
				{
					// 更新文章
					Method:  http.MethodPut,
					Path:    "/articles/:id",
					Handler: contentarticle.UpdateArticleHandler(serverCtx),
				},
				{
					// 删除文章
					Method:  http.MethodDelete,
					Path:    "/articles/:id",
					Handler: contentarticle.DeleteArticleHandler(serverCtx),
				},
				{
					// 部分更新文章（置顶状态 / 删除状态）
					Method:  http.MethodPatch,
					Path:    "/articles/:id",
					Handler: contentarticle.PatchArticleHandler(serverCtx),
				},
				{
					// 导出文章列表
					Method:  http.MethodPost,
					Path:    "/articles/export",
					Handler: contentarticle.ExportArticleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取分类列表
					Method:  http.MethodGet,
					Path:    "/categories",
					Handler: contentcategory.QueryCategoryListHandler(serverCtx),
				},
				{
					// 创建分类
					Method:  http.MethodPost,
					Path:    "/categories",
					Handler: contentcategory.CreateCategoryHandler(serverCtx),
				},
				{
					// 更新分类
					Method:  http.MethodPut,
					Path:    "/categories/:id",
					Handler: contentcategory.UpdateCategoryHandler(serverCtx),
				},
				{
					// 批量删除分类
					Method:  http.MethodPost,
					Path:    "/categories/batch-delete",
					Handler: contentcategory.BatchDeleteCategoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取标签列表
					Method:  http.MethodGet,
					Path:    "/tags",
					Handler: contenttag.QueryTagListHandler(serverCtx),
				},
				{
					// 创建标签
					Method:  http.MethodPost,
					Path:    "/tags",
					Handler: contenttag.CreateTagHandler(serverCtx),
				},
				{
					// 更新标签
					Method:  http.MethodPut,
					Path:    "/tags/:id",
					Handler: contenttag.UpdateTagHandler(serverCtx),
				},
				{
					// 批量删除标签
					Method:  http.MethodPost,
					Path:    "/tags/batch-delete",
					Handler: contenttag.BatchDeleteTagHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取评论列表(后台)
					Method:  http.MethodGet,
					Path:    "/comments",
					Handler: discussioncomment.QueryCommentListHandler(serverCtx),
				},
				{
					// 部分更新评论（批量）
					Method:  http.MethodPatch,
					Path:    "/comments",
					Handler: discussioncomment.PatchCommentsHandler(serverCtx),
				},
				{
					// 批量删除评论
					Method:  http.MethodPost,
					Path:    "/comments/batch-delete",
					Handler: discussioncomment.BatchDeleteCommentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取留言列表
					Method:  http.MethodGet,
					Path:    "/messages",
					Handler: discussionmessage.QueryMessageListHandler(serverCtx),
				},
				{
					// 部分更新留言（批量）
					Method:  http.MethodPatch,
					Path:    "/messages",
					Handler: discussionmessage.PatchMessagesHandler(serverCtx),
				},
				{
					// 批量删除留言
					Method:  http.MethodPost,
					Path:    "/messages/batch-delete",
					Handler: discussionmessage.BatchDeleteMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取说说列表
					Method:  http.MethodGet,
					Path:    "/talks",
					Handler: discussiontalk.QueryTalkListHandler(serverCtx),
				},
				{
					// 创建说说
					Method:  http.MethodPost,
					Path:    "/talks",
					Handler: discussiontalk.CreateTalkHandler(serverCtx),
				},
				{
					// 更新说说
					Method:  http.MethodPut,
					Path:    "/talks/:id",
					Handler: discussiontalk.UpdateTalkHandler(serverCtx),
				},
				{
					// 获取说说详情
					Method:  http.MethodGet,
					Path:    "/talks/:id",
					Handler: discussiontalk.GetTalkHandler(serverCtx),
				},
				{
					// 批量删除说说
					Method:  http.MethodPost,
					Path:    "/talks/batch-delete",
					Handler: discussiontalk.BatchDeleteTalkHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取相册列表
					Method:  http.MethodGet,
					Path:    "/albums",
					Handler: mediaalbum.QueryAlbumListHandler(serverCtx),
				},
				{
					// 创建相册
					Method:  http.MethodPost,
					Path:    "/albums",
					Handler: mediaalbum.CreateAlbumHandler(serverCtx),
				},
				{
					// 获取相册详情
					Method:  http.MethodGet,
					Path:    "/albums/:id",
					Handler: mediaalbum.GetAlbumHandler(serverCtx),
				},
				{
					// 更新相册
					Method:  http.MethodPut,
					Path:    "/albums/:id",
					Handler: mediaalbum.UpdateAlbumHandler(serverCtx),
				},
				{
					// 批量删除相册（移入回收站）
					Method:  http.MethodPost,
					Path:    "/albums/batch-delete",
					Handler: mediaalbum.BatchDeleteAlbumHandler(serverCtx),
				},
				{
					// 批量销毁相册（彻底删除，不可恢复）
					Method:  http.MethodPost,
					Path:    "/albums/batch-destroy",
					Handler: mediaalbum.BatchDestroyAlbumHandler(serverCtx),
				},
				{
					// 批量恢复相册
					Method:  http.MethodPost,
					Path:    "/albums/batch-restore",
					Handler: mediaalbum.BatchRestoreAlbumHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取照片列表
					Method:  http.MethodGet,
					Path:    "/photos",
					Handler: mediaphoto.QueryPhotoListHandler(serverCtx),
				},
				{
					// 创建照片
					Method:  http.MethodPost,
					Path:    "/photos",
					Handler: mediaphoto.CreatePhotoHandler(serverCtx),
				},
				{
					// 更新照片
					Method:  http.MethodPut,
					Path:    "/photos/:id",
					Handler: mediaphoto.UpdatePhotoHandler(serverCtx),
				},
				{
					// 批量删除照片（移入回收站）
					Method:  http.MethodPost,
					Path:    "/photos/batch-delete",
					Handler: mediaphoto.BatchDeletePhotoHandler(serverCtx),
				},
				{
					// 批量销毁照片（彻底删除，不可恢复）
					Method:  http.MethodPost,
					Path:    "/photos/batch-destroy",
					Handler: mediaphoto.BatchDestroyPhotoHandler(serverCtx),
				},
				{
					// 批量恢复照片
					Method:  http.MethodPost,
					Path:    "/photos/batch-restore",
					Handler: mediaphoto.BatchRestorePhotoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取统一通知消息列表
					Method:  http.MethodGet,
					Path:    "/notify-messages",
					Handler: notificationnotify_message.QueryNotifyMessageListHandler(serverCtx),
				},
				{
					// 创建统一通知消息
					Method:  http.MethodPost,
					Path:    "/notify-messages",
					Handler: notificationnotify_message.CreateNotifyMessageHandler(serverCtx),
				},
				{
					// 获取统一通知消息详情
					Method:  http.MethodGet,
					Path:    "/notify-messages/:id",
					Handler: notificationnotify_message.GetNotifyMessageHandler(serverCtx),
				},
				{
					// 更新统一通知消息
					Method:  http.MethodPut,
					Path:    "/notify-messages/:id",
					Handler: notificationnotify_message.UpdateNotifyMessageHandler(serverCtx),
				},
				{
					// 发布统一通知消息
					Method:  http.MethodPost,
					Path:    "/notify-messages/:id/publish",
					Handler: notificationnotify_message.PublishNotifyMessageHandler(serverCtx),
				},
				{
					// 撤回统一通知消息
					Method:  http.MethodPost,
					Path:    "/notify-messages/:id/revoke",
					Handler: notificationnotify_message.RevokeNotifyMessageHandler(serverCtx),
				},
				{
					// 批量删除统一通知消息
					Method:  http.MethodPost,
					Path:    "/notify-messages/batch-delete",
					Handler: notificationnotify_message.BatchDeleteNotifyMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 查询用户 inbox 投递列表
					Method:  http.MethodGet,
					Path:    "/inbox-records",
					Handler: notificationnotify_record.QueryUserInboxRecordListHandler(serverCtx),
				},
				{
					// 标记单条投递记录为已读
					Method:  http.MethodPost,
					Path:    "/inbox-records/:id/mark-read",
					Handler: notificationnotify_record.MarkRecordReadHandler(serverCtx),
				},
				{
					// 批量标记投递记录为已读
					Method:  http.MethodPost,
					Path:    "/inbox-records/batch-mark-read",
					Handler: notificationnotify_record.BatchMarkRecordsReadHandler(serverCtx),
				},
				{
					// 全部标记投递记录为已读
					Method:  http.MethodPost,
					Path:    "/inbox-records/mark-all-read",
					Handler: notificationnotify_record.MarkAllRecordsReadHandler(serverCtx),
				},
				{
					// 获取统一投递记录列表
					Method:  http.MethodGet,
					Path:    "/notify-records",
					Handler: notificationnotify_record.QueryNotifyRecordListHandler(serverCtx),
				},
				{
					// 批量删除投递记录
					Method:  http.MethodPost,
					Path:    "/notify-records/batch-delete",
					Handler: notificationnotify_record.BatchDeleteNotifyRecordHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取通知模板列表
					Method:  http.MethodGet,
					Path:    "/notify-templates",
					Handler: notificationnotify_template.QueryNotifyTemplateListHandler(serverCtx),
				},
				{
					// 创建通知模板
					Method:  http.MethodPost,
					Path:    "/notify-templates",
					Handler: notificationnotify_template.CreateNotifyTemplateHandler(serverCtx),
				},
				{
					// 获取通知模板详情
					Method:  http.MethodGet,
					Path:    "/notify-templates/:id",
					Handler: notificationnotify_template.GetNotifyTemplateHandler(serverCtx),
				},
				{
					// 更新通知模板
					Method:  http.MethodPut,
					Path:    "/notify-templates/:id",
					Handler: notificationnotify_template.UpdateNotifyTemplateHandler(serverCtx),
				},
				{
					// 批量删除通知模板
					Method:  http.MethodPost,
					Path:    "/notify-templates/batch-delete",
					Handler: notificationnotify_template.BatchDeleteNotifyTemplateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取关于我的信息
					Method:  http.MethodGet,
					Path:    "/about-me",
					Handler: siteconfig.GetAboutMeHandler(serverCtx),
				},
				{
					// 更新关于我的信息（请求体与响应共用 AboutMeVO，同上）
					Method:  http.MethodPut,
					Path:    "/about-me",
					Handler: siteconfig.UpdateAboutMeHandler(serverCtx),
				},
				{
					// 获取网站配置
					Method:  http.MethodGet,
					Path:    "/website-config",
					Handler: siteconfig.GetWebsiteConfigHandler(serverCtx),
				},
				{
					// 更新网站配置（请求体与响应共用 WebsiteConfigVO：单例配置对象，无服务端生成字段，二者同构）
					Method:  http.MethodPut,
					Path:    "/website-config",
					Handler: siteconfig.UpdateWebsiteConfigHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取友链列表
					Method:  http.MethodGet,
					Path:    "/friends",
					Handler: sitefriend.QueryFriendListHandler(serverCtx),
				},
				{
					// 创建友链
					Method:  http.MethodPost,
					Path:    "/friends",
					Handler: sitefriend.CreateFriendHandler(serverCtx),
				},
				{
					// 更新友链
					Method:  http.MethodPut,
					Path:    "/friends/:id",
					Handler: sitefriend.UpdateFriendHandler(serverCtx),
				},
				{
					// 批量删除友链
					Method:  http.MethodPost,
					Path:    "/friends/batch-delete",
					Handler: sitefriend.BatchDeleteFriendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取页面列表
					Method:  http.MethodGet,
					Path:    "/pages",
					Handler: sitepage.QueryPageListHandler(serverCtx),
				},
				{
					// 创建页面
					Method:  http.MethodPost,
					Path:    "/pages",
					Handler: sitepage.CreatePageHandler(serverCtx),
				},
				{
					// 更新页面
					Method:  http.MethodPut,
					Path:    "/pages/:id",
					Handler: sitepage.UpdatePageHandler(serverCtx),
				},
				{
					// 批量删除页面
					Method:  http.MethodPost,
					Path:    "/pages/batch-delete",
					Handler: sitepage.BatchDeletePageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取文章分析数据
					Method:  http.MethodGet,
					Path:    "/stats/article",
					Handler: statsoverview.GetArticleStatsHandler(serverCtx),
				},
				{
					// 获取仪表盘统计数据
					Method:  http.MethodGet,
					Path:    "/stats/dashboard",
					Handler: statsoverview.GetDashboardStatsHandler(serverCtx),
				},
				{
					// 获取用户与访客的地区分布
					Method:  http.MethodGet,
					Path:    "/stats/geo",
					Handler: statsoverview.GetGeoStatsHandler(serverCtx),
				},
				{
					// 获取服务器信息
					Method:  http.MethodGet,
					Path:    "/stats/system",
					Handler: statsoverview.GetSystemInfoHandler(serverCtx),
				},
				{
					// 获取访客数据趋势
					Method:  http.MethodGet,
					Path:    "/stats/visit-trend",
					Handler: statsoverview.GetVisitTrendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取登录日志列表
					Method:  http.MethodGet,
					Path:    "/login-logs",
					Handler: sysloglogin_log.QueryLoginLogListHandler(serverCtx),
				},
				{
					// 批量删除登录日志
					Method:  http.MethodPost,
					Path:    "/login-logs/batch-delete",
					Handler: sysloglogin_log.BatchDeleteLoginLogHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取操作日志列表
					Method:  http.MethodGet,
					Path:    "/operation-logs",
					Handler: syslogoperation_log.QueryOperationLogListHandler(serverCtx),
				},
				{
					// 批量删除操作日志
					Method:  http.MethodPost,
					Path:    "/operation-logs/batch-delete",
					Handler: syslogoperation_log.BatchDeleteOperationLogHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取文件日志列表
					Method:  http.MethodGet,
					Path:    "/upload-logs",
					Handler: syslogupload_log.QueryUploadLogListHandler(serverCtx),
				},
				{
					// 批量删除文件日志
					Method:  http.MethodPost,
					Path:    "/upload-logs/batch-delete",
					Handler: syslogupload_log.BatchDeleteUploadLogHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取访问日志列表
					Method:  http.MethodGet,
					Path:    "/visit-logs",
					Handler: syslogvisit_log.QueryVisitLogListHandler(serverCtx),
				},
				{
					// 批量删除访问日志
					Method:  http.MethodPost,
					Path:    "/visit-logs/batch-delete",
					Handler: syslogvisit_log.BatchDeleteVisitLogHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)
}
