// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/zeromicro/go-zero/rest"

	auth2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/account/auth"
	guest2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/account/guest"
	me2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/account/me"
	user2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/account/user"
	upload2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/common/upload"
	commonwebsocket "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/common/websocket"
	article2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/content/article"
	category2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/content/category"
	tag2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/content/tag"
	comment2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/discussion/comment"
	message2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/discussion/message"
	notify_message2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/notification/notify_message"
	notify_record2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/notification/notify_record"
	notify_template2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/notification/notify_template"
	api2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/permission/api"
	menu2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/permission/menu"
	role2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/permission/role"
	album2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/resource/album"
	photo2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/resource/photo"
	friend2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/social/friend"
	talk2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/social/talk"
	login_log2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/syslog/login_log"
	operation_log2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/syslog/operation_log"
	upload_log2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/syslog/upload_log"
	visit_log2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/syslog/visit_log"
	config2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/website/config"
	page2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/website/page"
	stats2 "github.com/ve-weiyi/blog-cloud/api/admin/internal/handler/website/stats"
	"github.com/ve-weiyi/blog-cloud/api/admin/internal/svc"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// ping
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: PingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取验证码
				Method:  http.MethodGet,
				Path:    "/auth/captcha",
				Handler: auth2.GetCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					// 邮箱验证码登录（仅登录）
					Method:  http.MethodPost,
					Path:    "/auth/login/email",
					Handler: auth2.EmailLoginHandler(serverCtx),
				},
				{
					// 手机验证码登录（自动注册）
					Method:  http.MethodPost,
					Path:    "/auth/login/mobile",
					Handler: auth2.MobileLoginHandler(serverCtx),
				},
				{
					// 密码登录（账号/手机号/邮箱）
					Method:  http.MethodPost,
					Path:    "/auth/login/password",
					Handler: auth2.PasswordLoginHandler(serverCtx),
				},
				{
					// 获取第三方授权URL
					Method:  http.MethodGet,
					Path:    "/auth/oauth/:platform/authorize",
					Handler: auth2.GetOauthAuthorizeUrlHandler(serverCtx),
				},
				{
					// 第三方登录（自动注册）
					Method:  http.MethodPost,
					Path:    "/auth/oauth/:platform/login",
					Handler: auth2.OauthLoginHandler(serverCtx),
				},
				{
					// 重置密码
					Method:  http.MethodPost,
					Path:    "/auth/password/reset",
					Handler: auth2.ResetPasswordHandler(serverCtx),
				},
				{
					// 刷新token
					Method:  http.MethodPost,
					Path:    "/auth/refresh-token",
					Handler: auth2.RefreshTokenHandler(serverCtx),
				},
				{
					// 邮箱注册
					Method:  http.MethodPost,
					Path:    "/auth/register/email",
					Handler: auth2.EmailRegisterHandler(serverCtx),
				},
				{
					// 发送邮箱验证码
					Method:  http.MethodPost,
					Path:    "/auth/send/email",
					Handler: auth2.SendEmailCodeHandler(serverCtx),
				},
				{
					// 发送手机验证码
					Method:  http.MethodPost,
					Path:    "/auth/send/mobile",
					Handler: auth2.SendMobileCodeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					// 退出登录（需登录）
					Method:  http.MethodPost,
					Path:    "/auth/logout",
					Handler: auth2.LogoutHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取游客信息
				Method:  http.MethodGet,
				Path:    "/guest/get_guest",
				Handler: guest2.GetGuestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取访客列表
					Method:  http.MethodPost,
					Path:    "/guest/query_guest_list",
					Handler: guest2.QueryGuestListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					// 绑定邮箱
					Method:  http.MethodPost,
					Path:    "/user/me/bind_user_email",
					Handler: me2.BindUserEmailHandler(serverCtx),
				},
				{
					// 绑定手机号
					Method:  http.MethodPost,
					Path:    "/user/me/bind_user_phone",
					Handler: me2.BindUserPhoneHandler(serverCtx),
				},
				{
					// 绑定第三方平台账号
					Method:  http.MethodPost,
					Path:    "/user/me/bind_user_third_party",
					Handler: me2.BindUserThirdPartyHandler(serverCtx),
				},
				{
					// 获取用户接口权限
					Method:  http.MethodGet,
					Path:    "/user/me/get_user_apis",
					Handler: me2.GetUserApisHandler(serverCtx),
				},
				{
					// 获取用户菜单权限
					Method:  http.MethodGet,
					Path:    "/user/me/get_user_menus",
					Handler: me2.GetUserMenusHandler(serverCtx),
				},
				{
					// 获取当前用户信息
					Method:  http.MethodGet,
					Path:    "/user/me/get_user_profile",
					Handler: me2.GetUserProfileHandler(serverCtx),
				},
				{
					// 获取用户角色
					Method:  http.MethodGet,
					Path:    "/user/me/get_user_roles",
					Handler: me2.GetUserRolesHandler(serverCtx),
				},
				{
					// 查询用户登录历史
					Method:  http.MethodPost,
					Path:    "/user/me/query_user_login_history",
					Handler: me2.QueryUserLoginHistoryHandler(serverCtx),
				},
				{
					// 解绑第三方平台账号
					Method:  http.MethodPost,
					Path:    "/user/me/unbind_user_third_party",
					Handler: me2.UnbindUserThirdPartyHandler(serverCtx),
				},
				{
					// 修改用户头像
					Method:  http.MethodPut,
					Path:    "/user/me/update_user_avatar",
					Handler: me2.UpdateUserAvatarHandler(serverCtx),
				},
				{
					// 修改用户密码
					Method:  http.MethodPut,
					Path:    "/user/me/update_user_password",
					Handler: me2.UpdateUserPasswordHandler(serverCtx),
				},
				{
					// 更新当前用户信息
					Method:  http.MethodPut,
					Path:    "/user/me/update_user_profile",
					Handler: me2.UpdateUserProfileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取在线用户列表
					Method:  http.MethodGet,
					Path:    "/user/get_online_users",
					Handler: user2.GetOnlineUsersHandler(serverCtx),
				},
				{
					// 获取用户详情
					Method:  http.MethodGet,
					Path:    "/user/get_user",
					Handler: user2.GetUserDetailHandler(serverCtx),
				},
				{
					// 获取用户列表
					Method:  http.MethodPost,
					Path:    "/user/query_user_list",
					Handler: user2.QueryUserListHandler(serverCtx),
				},
				{
					// 重置用户密码
					Method:  http.MethodPost,
					Path:    "/user/reset_user_password",
					Handler: user2.ResetUserPasswordHandler(serverCtx),
				},
				{
					// 更新用户角色
					Method:  http.MethodPut,
					Path:    "/user/update_user_roles",
					Handler: user2.UpdateUserRolesHandler(serverCtx),
				},
				{
					// 更新用户状态
					Method:  http.MethodPut,
					Path:    "/user/update_user_status",
					Handler: user2.UpdateUserStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取上传凭证（前端直传）
					Method:  http.MethodPost,
					Path:    "/upload/get_upload_token",
					Handler: upload2.GetUploadTokenHandler(serverCtx),
				},
				{
					// 查询上传文件列表
					Method:  http.MethodPost,
					Path:    "/upload/query_file_list",
					Handler: upload2.QueryFileListHandler(serverCtx),
				},
				{
					// 上传文件（服务端上传）
					Method:  http.MethodPost,
					Path:    "/upload/upload_file",
					Handler: upload2.UploadFileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
		rest.WithMaxBytes(10485760),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// WebSocket消息
				Method:  http.MethodGet,
				Path:    "/websocket",
				Handler: commonwebsocket.WebsocketHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 创建文章
					Method:  http.MethodPost,
					Path:    "/article/create_article",
					Handler: article2.CreateArticleHandler(serverCtx),
				},
				{
					// 删除文章
					Method:  http.MethodDelete,
					Path:    "/article/delete_article",
					Handler: article2.DeleteArticleHandler(serverCtx),
				},
				{
					// 导出文章列表
					Method:  http.MethodPost,
					Path:    "/article/export_article",
					Handler: article2.ExportArticleHandler(serverCtx),
				},
				{
					// 获取文章详情
					Method:  http.MethodGet,
					Path:    "/article/get_article",
					Handler: article2.GetArticleHandler(serverCtx),
				},
				{
					// 获取文章列表
					Method:  http.MethodPost,
					Path:    "/article/query_article_list",
					Handler: article2.QueryArticleListHandler(serverCtx),
				},
				{
					// 更新文章
					Method:  http.MethodPut,
					Path:    "/article/update_article",
					Handler: article2.UpdateArticleHandler(serverCtx),
				},
				{
					// 更新文章删除状态
					Method:  http.MethodPut,
					Path:    "/article/update_article_delete",
					Handler: article2.UpdateArticleDeleteHandler(serverCtx),
				},
				{
					// 更新文章置顶状态
					Method:  http.MethodPut,
					Path:    "/article/update_article_top",
					Handler: article2.UpdateArticleTopHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 创建分类
					Method:  http.MethodPost,
					Path:    "/category/create_category",
					Handler: category2.CreateCategoryHandler(serverCtx),
				},
				{
					// 批量删除分类
					Method:  http.MethodDelete,
					Path:    "/category/delete_category",
					Handler: category2.DeleteCategoryHandler(serverCtx),
				},
				{
					// 获取分类列表
					Method:  http.MethodPost,
					Path:    "/category/query_category_list",
					Handler: category2.QueryCategoryListHandler(serverCtx),
				},
				{
					// 更新分类
					Method:  http.MethodPut,
					Path:    "/category/update_category",
					Handler: category2.UpdateCategoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 创建标签
					Method:  http.MethodPost,
					Path:    "/tag/create_tag",
					Handler: tag2.CreateTagHandler(serverCtx),
				},
				{
					// 删除标签
					Method:  http.MethodDelete,
					Path:    "/tag/delete_tag",
					Handler: tag2.DeleteTagHandler(serverCtx),
				},
				{
					// 获取标签列表
					Method:  http.MethodPost,
					Path:    "/tag/query_tag_list",
					Handler: tag2.QueryTagListHandler(serverCtx),
				},
				{
					// 更新标签
					Method:  http.MethodPut,
					Path:    "/tag/update_tag",
					Handler: tag2.UpdateTagHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 批量删除评论
					Method:  http.MethodDelete,
					Path:    "/comment/delete_comment",
					Handler: comment2.DeleteCommentHandler(serverCtx),
				},
				{
					// 获取评论列表(后台)
					Method:  http.MethodPost,
					Path:    "/comment/query_comment_list",
					Handler: comment2.QueryCommentListHandler(serverCtx),
				},
				{
					// 批量更新评论状态
					Method:  http.MethodPut,
					Path:    "/comment/update_comment_status",
					Handler: comment2.UpdateCommentStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 批量删除留言
					Method:  http.MethodDelete,
					Path:    "/message/delete_message",
					Handler: message2.DeleteMessageHandler(serverCtx),
				},
				{
					// 获取留言列表
					Method:  http.MethodPost,
					Path:    "/message/query_message_list",
					Handler: message2.QueryMessageListHandler(serverCtx),
				},
				{
					// 批量更新留言状态
					Method:  http.MethodPut,
					Path:    "/message/update_message_status",
					Handler: message2.UpdateMessageStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 创建统一通知消息
					Method:  http.MethodPost,
					Path:    "/notify_message/create_notify_message",
					Handler: notify_message2.CreateNotifyMessageHandler(serverCtx),
				},
				{
					// 批量删除统一通知消息
					Method:  http.MethodDelete,
					Path:    "/notify_message/delete_notify_message",
					Handler: notify_message2.DeleteNotifyMessageHandler(serverCtx),
				},
				{
					// 获取统一通知消息详情
					Method:  http.MethodGet,
					Path:    "/notify_message/get_notify_message",
					Handler: notify_message2.GetNotifyMessageHandler(serverCtx),
				},
				{
					// 发布统一通知消息
					Method:  http.MethodPost,
					Path:    "/notify_message/publish_notify_message",
					Handler: notify_message2.PublishNotifyMessageHandler(serverCtx),
				},
				{
					// 获取统一通知消息列表
					Method:  http.MethodPost,
					Path:    "/notify_message/query_notify_message_list",
					Handler: notify_message2.QueryNotifyMessageListHandler(serverCtx),
				},
				{
					// 撤回统一通知消息
					Method:  http.MethodPost,
					Path:    "/notify_message/revoke_notify_message",
					Handler: notify_message2.RevokeNotifyMessageHandler(serverCtx),
				},
				{
					// 更新统一通知消息
					Method:  http.MethodPut,
					Path:    "/notify_message/update_notify_message",
					Handler: notify_message2.UpdateNotifyMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 批量标记投递记录为已读
					Method:  http.MethodPost,
					Path:    "/notify_record/batch_mark_records_read",
					Handler: notify_record2.BatchMarkRecordsReadHandler(serverCtx),
				},
				{
					// 批量删除投递记录
					Method:  http.MethodDelete,
					Path:    "/notify_record/delete_notify_record",
					Handler: notify_record2.DeleteNotifyRecordHandler(serverCtx),
				},
				{
					// 全部标记投递记录为已读
					Method:  http.MethodPost,
					Path:    "/notify_record/mark_all_records_read",
					Handler: notify_record2.MarkAllRecordsReadHandler(serverCtx),
				},
				{
					// 标记单条投递记录为已读
					Method:  http.MethodPost,
					Path:    "/notify_record/mark_record_read",
					Handler: notify_record2.MarkRecordReadHandler(serverCtx),
				},
				{
					// 获取统一投递记录列表
					Method:  http.MethodPost,
					Path:    "/notify_record/query_notify_record_list",
					Handler: notify_record2.QueryNotifyRecordListHandler(serverCtx),
				},
				{
					// 查询用户 inbox 投递列表
					Method:  http.MethodPost,
					Path:    "/notify_record/query_user_inbox_record_list",
					Handler: notify_record2.QueryUserInboxRecordListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 创建通知模板
					Method:  http.MethodPost,
					Path:    "/notify_template/create_notify_template",
					Handler: notify_template2.CreateNotifyTemplateHandler(serverCtx),
				},
				{
					// 批量删除通知模板
					Method:  http.MethodDelete,
					Path:    "/notify_template/delete_notify_template",
					Handler: notify_template2.DeleteNotifyTemplateHandler(serverCtx),
				},
				{
					// 获取通知模板详情
					Method:  http.MethodGet,
					Path:    "/notify_template/get_notify_template",
					Handler: notify_template2.GetNotifyTemplateHandler(serverCtx),
				},
				{
					// 获取通知模板列表
					Method:  http.MethodPost,
					Path:    "/notify_template/query_notify_template_list",
					Handler: notify_template2.QueryNotifyTemplateListHandler(serverCtx),
				},
				{
					// 更新通知模板
					Method:  http.MethodPut,
					Path:    "/notify_template/update_notify_template",
					Handler: notify_template2.UpdateNotifyTemplateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 清空接口列表
					Method:  http.MethodPost,
					Path:    "/api/clean_api",
					Handler: api2.CleanApiHandler(serverCtx),
				},
				{
					// 创建接口
					Method:  http.MethodPost,
					Path:    "/api/create_api",
					Handler: api2.CreateApiHandler(serverCtx),
				},
				{
					// 删除接口
					Method:  http.MethodDelete,
					Path:    "/api/delete_api",
					Handler: api2.DeleteApiHandler(serverCtx),
				},
				{
					// 获取接口详情
					Method:  http.MethodGet,
					Path:    "/api/get_api",
					Handler: api2.GetApiHandler(serverCtx),
				},
				{
					// 获取接口列表
					Method:  http.MethodPost,
					Path:    "/api/query_api_list",
					Handler: api2.QueryApiListHandler(serverCtx),
				},
				{
					// 同步接口列表
					Method:  http.MethodPost,
					Path:    "/api/sync_api",
					Handler: api2.SyncApiHandler(serverCtx),
				},
				{
					// 更新接口
					Method:  http.MethodPut,
					Path:    "/api/update_api",
					Handler: api2.UpdateApiHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 清空菜单列表
					Method:  http.MethodPost,
					Path:    "/menu/clean_menu",
					Handler: menu2.CleanMenuHandler(serverCtx),
				},
				{
					// 创建菜单
					Method:  http.MethodPost,
					Path:    "/menu/create_menu",
					Handler: menu2.CreateMenuHandler(serverCtx),
				},
				{
					// 删除菜单
					Method:  http.MethodDelete,
					Path:    "/menu/delete_menu",
					Handler: menu2.DeleteMenuHandler(serverCtx),
				},
				{
					// 获取菜单详情
					Method:  http.MethodGet,
					Path:    "/menu/get_menu",
					Handler: menu2.GetMenuHandler(serverCtx),
				},
				{
					// 获取菜单列表
					Method:  http.MethodPost,
					Path:    "/menu/query_menu_list",
					Handler: menu2.QueryMenuListHandler(serverCtx),
				},
				{
					// 同步菜单列表
					Method:  http.MethodPost,
					Path:    "/menu/sync_menu",
					Handler: menu2.SyncMenuHandler(serverCtx),
				},
				{
					// 更新菜单
					Method:  http.MethodPut,
					Path:    "/menu/update_menu",
					Handler: menu2.UpdateMenuHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 创建角色
					Method:  http.MethodPost,
					Path:    "/role/create_role",
					Handler: role2.CreateRoleHandler(serverCtx),
				},
				{
					// 删除角色
					Method:  http.MethodDelete,
					Path:    "/role/delete_role",
					Handler: role2.DeleteRoleHandler(serverCtx),
				},
				{
					// 获取角色详情
					Method:  http.MethodGet,
					Path:    "/role/get_role",
					Handler: role2.GetRoleHandler(serverCtx),
				},
				{
					// 查询角色权限配置
					Method:  http.MethodGet,
					Path:    "/role/get_role_permissions",
					Handler: role2.GetRolePermissionsHandler(serverCtx),
				},
				{
					// 获取角色列表
					Method:  http.MethodPost,
					Path:    "/role/query_role_list",
					Handler: role2.QueryRoleListHandler(serverCtx),
				},
				{
					// 更新角色信息
					Method:  http.MethodPut,
					Path:    "/role/update_role",
					Handler: role2.UpdateRoleHandler(serverCtx),
				},
				{
					// 更新角色接口权限
					Method:  http.MethodPut,
					Path:    "/role/update_role_api_permissions",
					Handler: role2.UpdateRoleApiPermissionsHandler(serverCtx),
				},
				{
					// 更新角色菜单权限
					Method:  http.MethodPut,
					Path:    "/role/update_role_menu_permissions",
					Handler: role2.UpdateRoleMenuPermissionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 创建相册
					Method:  http.MethodPost,
					Path:    "/album/create_album",
					Handler: album2.CreateAlbumHandler(serverCtx),
				},
				{
					// 批量删除相册
					Method:  http.MethodDelete,
					Path:    "/album/delete_album",
					Handler: album2.DeleteAlbumHandler(serverCtx),
				},
				{
					// 获取相册详情
					Method:  http.MethodGet,
					Path:    "/album/get_album",
					Handler: album2.GetAlbumHandler(serverCtx),
				},
				{
					// 获取相册列表
					Method:  http.MethodPost,
					Path:    "/album/query_album_list",
					Handler: album2.QueryAlbumListHandler(serverCtx),
				},
				{
					// 更新相册
					Method:  http.MethodPut,
					Path:    "/album/update_album",
					Handler: album2.UpdateAlbumHandler(serverCtx),
				},
				{
					// 批量更新相册删除状态
					Method:  http.MethodPut,
					Path:    "/album/update_album_delete",
					Handler: album2.UpdateAlbumDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 创建照片
					Method:  http.MethodPost,
					Path:    "/photo/create_photo",
					Handler: photo2.CreatePhotoHandler(serverCtx),
				},
				{
					// 批量删除照片
					Method:  http.MethodDelete,
					Path:    "/photo/delete_photo",
					Handler: photo2.DeletePhotoHandler(serverCtx),
				},
				{
					// 获取照片列表
					Method:  http.MethodPost,
					Path:    "/photo/query_photo_list",
					Handler: photo2.QueryPhotoListHandler(serverCtx),
				},
				{
					// 更新照片
					Method:  http.MethodPut,
					Path:    "/photo/update_photo",
					Handler: photo2.UpdatePhotoHandler(serverCtx),
				},
				{
					// 批量更新照片删除状态
					Method:  http.MethodPut,
					Path:    "/photo/update_photo_delete",
					Handler: photo2.UpdatePhotoDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 创建友链
					Method:  http.MethodPost,
					Path:    "/friend/create_friend",
					Handler: friend2.CreateFriendHandler(serverCtx),
				},
				{
					// 批量删除友链
					Method:  http.MethodDelete,
					Path:    "/friend/delete_friend",
					Handler: friend2.DeleteFriendHandler(serverCtx),
				},
				{
					// 获取友链列表
					Method:  http.MethodPost,
					Path:    "/friend/query_friend_list",
					Handler: friend2.QueryFriendListHandler(serverCtx),
				},
				{
					// 更新友链
					Method:  http.MethodPut,
					Path:    "/friend/update_friend",
					Handler: friend2.UpdateFriendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 创建说说
					Method:  http.MethodPost,
					Path:    "/talk/create_talk",
					Handler: talk2.CreateTalkHandler(serverCtx),
				},
				{
					// 删除说说
					Method:  http.MethodDelete,
					Path:    "/talk/delete_talk",
					Handler: talk2.DeleteTalkHandler(serverCtx),
				},
				{
					// 获取说说详情
					Method:  http.MethodGet,
					Path:    "/talk/get_talk",
					Handler: talk2.GetTalkHandler(serverCtx),
				},
				{
					// 获取说说列表
					Method:  http.MethodPost,
					Path:    "/talk/query_talk_list",
					Handler: talk2.QueryTalkListHandler(serverCtx),
				},
				{
					// 更新说说
					Method:  http.MethodPut,
					Path:    "/talk/update_talk",
					Handler: talk2.UpdateTalkHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 批量删除登录日志
					Method:  http.MethodDelete,
					Path:    "/login_log/delete_login_log",
					Handler: login_log2.DeleteLoginLogHandler(serverCtx),
				},
				{
					// 获取登录日志列表
					Method:  http.MethodPost,
					Path:    "/login_log/query_login_log_list",
					Handler: login_log2.QueryLoginLogListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 批量删除操作日志
					Method:  http.MethodDelete,
					Path:    "/operation_log/delete_operation_log",
					Handler: operation_log2.DeleteOperationLogHandler(serverCtx),
				},
				{
					// 获取操作日志列表
					Method:  http.MethodPost,
					Path:    "/operation_log/query_operation_log_list",
					Handler: operation_log2.QueryOperationLogListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 批量删除文件日志
					Method:  http.MethodDelete,
					Path:    "/upload_log/delete_upload_log",
					Handler: upload_log2.DeleteUploadLogHandler(serverCtx),
				},
				{
					// 获取文件日志列表
					Method:  http.MethodPost,
					Path:    "/upload_log/query_upload_log_list",
					Handler: upload_log2.QueryUploadLogListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 批量删除访问日志
					Method:  http.MethodDelete,
					Path:    "/visit_log/delete_visit_log",
					Handler: visit_log2.DeleteVisitLogHandler(serverCtx),
				},
				{
					// 获取访问日志列表
					Method:  http.MethodPost,
					Path:    "/visit_log/query_visit_log_list",
					Handler: visit_log2.QueryVisitLogListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取关于我的信息
					Method:  http.MethodGet,
					Path:    "/admin/get_about_me",
					Handler: config2.GetAboutMeHandler(serverCtx),
				},
				{
					// 获取服务器信息
					Method:  http.MethodGet,
					Path:    "/admin/get_system_state",
					Handler: config2.GetSystemStateHandler(serverCtx),
				},
				{
					// 获取网站配置
					Method:  http.MethodGet,
					Path:    "/admin/get_website_config",
					Handler: config2.GetWebsiteConfigHandler(serverCtx),
				},
				{
					// 更新关于我的信息
					Method:  http.MethodPut,
					Path:    "/admin/update_about_me",
					Handler: config2.UpdateAboutMeHandler(serverCtx),
				},
				{
					// 更新网站配置
					Method:  http.MethodPut,
					Path:    "/admin/update_website_config",
					Handler: config2.UpdateWebsiteConfigHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 创建页面
					Method:  http.MethodPost,
					Path:    "/page/create_page",
					Handler: page2.CreatePageHandler(serverCtx),
				},
				{
					// 删除页面
					Method:  http.MethodDelete,
					Path:    "/page/delete_page",
					Handler: page2.DeletePageHandler(serverCtx),
				},
				{
					// 获取页面列表
					Method:  http.MethodPost,
					Path:    "/page/query_page_list",
					Handler: page2.QueryPageListHandler(serverCtx),
				},
				{
					// 更新页面
					Method:  http.MethodPut,
					Path:    "/page/update_page",
					Handler: page2.UpdatePageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth, serverCtx.Permission, serverCtx.OperationLog},
			[]rest.Route{
				{
					// 获取文章分析数据
					Method:  http.MethodGet,
					Path:    "/stats/get_article_analytics",
					Handler: stats2.GetArticleAnalyticsHandler(serverCtx),
				},
				{
					// 获取仪表盘统计数据
					Method:  http.MethodGet,
					Path:    "/stats/get_stats_dashboard",
					Handler: stats2.GetStatsDashboardHandler(serverCtx),
				},
				{
					// 获取用户地理分布
					Method:  http.MethodPost,
					Path:    "/stats/get_user_geo_stats",
					Handler: stats2.GetUserGeoStatsHandler(serverCtx),
				},
				{
					// 获取访客数据趋势
					Method:  http.MethodPost,
					Path:    "/stats/get_visit_trend",
					Handler: stats2.GetVisitTrendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin-api/v1"),
	)
}
