// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: syslog.proto

package syslogservice

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/syslogrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchDeleteLoginLogsRequest      = syslogrpc.BatchDeleteLoginLogsRequest
	BatchDeleteLoginLogsResponse     = syslogrpc.BatchDeleteLoginLogsResponse
	BatchDeleteOperationLogsRequest  = syslogrpc.BatchDeleteOperationLogsRequest
	BatchDeleteOperationLogsResponse = syslogrpc.BatchDeleteOperationLogsResponse
	BatchDeleteUploadLogsRequest     = syslogrpc.BatchDeleteUploadLogsRequest
	BatchDeleteUploadLogsResponse    = syslogrpc.BatchDeleteUploadLogsResponse
	BatchDeleteVisitLogsRequest      = syslogrpc.BatchDeleteVisitLogsRequest
	BatchDeleteVisitLogsResponse     = syslogrpc.BatchDeleteVisitLogsResponse
	CreateLoginLogRequest            = syslogrpc.CreateLoginLogRequest
	CreateLoginLogResponse           = syslogrpc.CreateLoginLogResponse
	CreateOperationLogRequest        = syslogrpc.CreateOperationLogRequest
	CreateOperationLogResponse       = syslogrpc.CreateOperationLogResponse
	CreateUploadLogRequest           = syslogrpc.CreateUploadLogRequest
	CreateUploadLogResponse          = syslogrpc.CreateUploadLogResponse
	CreateVisitLogRequest            = syslogrpc.CreateVisitLogRequest
	CreateVisitLogResponse           = syslogrpc.CreateVisitLogResponse
	ListLoginLogsRequest             = syslogrpc.ListLoginLogsRequest
	ListLoginLogsResponse            = syslogrpc.ListLoginLogsResponse
	ListOperationLogsRequest         = syslogrpc.ListOperationLogsRequest
	ListOperationLogsResponse        = syslogrpc.ListOperationLogsResponse
	ListQuery                        = syslogrpc.ListQuery
	ListResult                       = syslogrpc.ListResult
	ListUploadLogsRequest            = syslogrpc.ListUploadLogsRequest
	ListUploadLogsResponse           = syslogrpc.ListUploadLogsResponse
	ListVisitLogsRequest             = syslogrpc.ListVisitLogsRequest
	ListVisitLogsResponse            = syslogrpc.ListVisitLogsResponse
	LoginLog                         = syslogrpc.LoginLog
	OperationLog                     = syslogrpc.OperationLog
	UploadLog                        = syslogrpc.UploadLog
	VisitLog                         = syslogrpc.VisitLog

	SyslogService interface {
		// 分页查询用户登录日志
		ListLoginLogs(ctx context.Context, in *ListLoginLogsRequest, opts ...grpc.CallOption) (*ListLoginLogsResponse, error)
		// 创建用户登录日志
		CreateLoginLog(ctx context.Context, in *CreateLoginLogRequest, opts ...grpc.CallOption) (*CreateLoginLogResponse, error)
		// 批量删除用户登录日志
		BatchDeleteLoginLogs(ctx context.Context, in *BatchDeleteLoginLogsRequest, opts ...grpc.CallOption) (*BatchDeleteLoginLogsResponse, error)
		// 分页查询操作日志
		ListOperationLogs(ctx context.Context, in *ListOperationLogsRequest, opts ...grpc.CallOption) (*ListOperationLogsResponse, error)
		// 创建操作日志
		CreateOperationLog(ctx context.Context, in *CreateOperationLogRequest, opts ...grpc.CallOption) (*CreateOperationLogResponse, error)
		// 批量删除操作日志
		BatchDeleteOperationLogs(ctx context.Context, in *BatchDeleteOperationLogsRequest, opts ...grpc.CallOption) (*BatchDeleteOperationLogsResponse, error)
		// 分页查询文件上传日志
		ListUploadLogs(ctx context.Context, in *ListUploadLogsRequest, opts ...grpc.CallOption) (*ListUploadLogsResponse, error)
		// 创建文件上传日志
		CreateUploadLog(ctx context.Context, in *CreateUploadLogRequest, opts ...grpc.CallOption) (*CreateUploadLogResponse, error)
		// 批量删除文件上传日志
		BatchDeleteUploadLogs(ctx context.Context, in *BatchDeleteUploadLogsRequest, opts ...grpc.CallOption) (*BatchDeleteUploadLogsResponse, error)
		// 分页查询访问日志
		ListVisitLogs(ctx context.Context, in *ListVisitLogsRequest, opts ...grpc.CallOption) (*ListVisitLogsResponse, error)
		// 创建访问日志
		CreateVisitLog(ctx context.Context, in *CreateVisitLogRequest, opts ...grpc.CallOption) (*CreateVisitLogResponse, error)
		// 批量删除访问日志
		BatchDeleteVisitLogs(ctx context.Context, in *BatchDeleteVisitLogsRequest, opts ...grpc.CallOption) (*BatchDeleteVisitLogsResponse, error)
	}

	defaultSyslogService struct {
		cli zrpc.Client
	}
)

func NewSyslogService(cli zrpc.Client) SyslogService {
	return &defaultSyslogService{
		cli: cli,
	}
}

// 分页查询用户登录日志
func (m *defaultSyslogService) ListLoginLogs(ctx context.Context, in *ListLoginLogsRequest, opts ...grpc.CallOption) (*ListLoginLogsResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.ListLoginLogs(ctx, in, opts...)
}

// 创建用户登录日志
func (m *defaultSyslogService) CreateLoginLog(ctx context.Context, in *CreateLoginLogRequest, opts ...grpc.CallOption) (*CreateLoginLogResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.CreateLoginLog(ctx, in, opts...)
}

// 批量删除用户登录日志
func (m *defaultSyslogService) BatchDeleteLoginLogs(ctx context.Context, in *BatchDeleteLoginLogsRequest, opts ...grpc.CallOption) (*BatchDeleteLoginLogsResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.BatchDeleteLoginLogs(ctx, in, opts...)
}

// 分页查询操作日志
func (m *defaultSyslogService) ListOperationLogs(ctx context.Context, in *ListOperationLogsRequest, opts ...grpc.CallOption) (*ListOperationLogsResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.ListOperationLogs(ctx, in, opts...)
}

// 创建操作日志
func (m *defaultSyslogService) CreateOperationLog(ctx context.Context, in *CreateOperationLogRequest, opts ...grpc.CallOption) (*CreateOperationLogResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.CreateOperationLog(ctx, in, opts...)
}

// 批量删除操作日志
func (m *defaultSyslogService) BatchDeleteOperationLogs(ctx context.Context, in *BatchDeleteOperationLogsRequest, opts ...grpc.CallOption) (*BatchDeleteOperationLogsResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.BatchDeleteOperationLogs(ctx, in, opts...)
}

// 分页查询文件上传日志
func (m *defaultSyslogService) ListUploadLogs(ctx context.Context, in *ListUploadLogsRequest, opts ...grpc.CallOption) (*ListUploadLogsResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.ListUploadLogs(ctx, in, opts...)
}

// 创建文件上传日志
func (m *defaultSyslogService) CreateUploadLog(ctx context.Context, in *CreateUploadLogRequest, opts ...grpc.CallOption) (*CreateUploadLogResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.CreateUploadLog(ctx, in, opts...)
}

// 批量删除文件上传日志
func (m *defaultSyslogService) BatchDeleteUploadLogs(ctx context.Context, in *BatchDeleteUploadLogsRequest, opts ...grpc.CallOption) (*BatchDeleteUploadLogsResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.BatchDeleteUploadLogs(ctx, in, opts...)
}

// 分页查询访问日志
func (m *defaultSyslogService) ListVisitLogs(ctx context.Context, in *ListVisitLogsRequest, opts ...grpc.CallOption) (*ListVisitLogsResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.ListVisitLogs(ctx, in, opts...)
}

// 创建访问日志
func (m *defaultSyslogService) CreateVisitLog(ctx context.Context, in *CreateVisitLogRequest, opts ...grpc.CallOption) (*CreateVisitLogResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.CreateVisitLog(ctx, in, opts...)
}

// 批量删除访问日志
func (m *defaultSyslogService) BatchDeleteVisitLogs(ctx context.Context, in *BatchDeleteVisitLogsRequest, opts ...grpc.CallOption) (*BatchDeleteVisitLogsResponse, error) {
	client := syslogrpc.NewSyslogServiceClient(m.cli.Conn())
	return client.BatchDeleteVisitLogs(ctx, in, opts...)
}
