// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: discussion.proto

package discussionservice

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/discussionrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchDeleteCommentsRequest   = discussionrpc.BatchDeleteCommentsRequest
	BatchDeleteCommentsResponse  = discussionrpc.BatchDeleteCommentsResponse
	BatchDeleteMessagesRequest   = discussionrpc.BatchDeleteMessagesRequest
	BatchDeleteMessagesResponse  = discussionrpc.BatchDeleteMessagesResponse
	BatchDeleteTalksRequest      = discussionrpc.BatchDeleteTalksRequest
	BatchDeleteTalksResponse     = discussionrpc.BatchDeleteTalksResponse
	BatchPatchCommentsRequest    = discussionrpc.BatchPatchCommentsRequest
	BatchPatchCommentsResponse   = discussionrpc.BatchPatchCommentsResponse
	BatchPatchMessagesRequest    = discussionrpc.BatchPatchMessagesRequest
	BatchPatchMessagesResponse   = discussionrpc.BatchPatchMessagesResponse
	Comment                      = discussionrpc.Comment
	CreateCommentRequest         = discussionrpc.CreateCommentRequest
	CreateCommentResponse        = discussionrpc.CreateCommentResponse
	CreateMessageRequest         = discussionrpc.CreateMessageRequest
	CreateMessageResponse        = discussionrpc.CreateMessageResponse
	CreateTalkRequest            = discussionrpc.CreateTalkRequest
	CreateTalkResponse           = discussionrpc.CreateTalkResponse
	GetCommentReplyCountRequest  = discussionrpc.GetCommentReplyCountRequest
	GetCommentReplyCountResponse = discussionrpc.GetCommentReplyCountResponse
	GetCommentRequest            = discussionrpc.GetCommentRequest
	GetCommentResponse           = discussionrpc.GetCommentResponse
	GetMessageRequest            = discussionrpc.GetMessageRequest
	GetMessageResponse           = discussionrpc.GetMessageResponse
	GetTalkRequest               = discussionrpc.GetTalkRequest
	GetTalkResponse              = discussionrpc.GetTalkResponse
	GetUserLikeCommentRequest    = discussionrpc.GetUserLikeCommentRequest
	GetUserLikeCommentResponse   = discussionrpc.GetUserLikeCommentResponse
	GetUserLikeTalkRequest       = discussionrpc.GetUserLikeTalkRequest
	GetUserLikeTalkResponse      = discussionrpc.GetUserLikeTalkResponse
	LikeCommentRequest           = discussionrpc.LikeCommentRequest
	LikeCommentResponse          = discussionrpc.LikeCommentResponse
	LikeTalkRequest              = discussionrpc.LikeTalkRequest
	LikeTalkResponse             = discussionrpc.LikeTalkResponse
	ListCommentRepliesRequest    = discussionrpc.ListCommentRepliesRequest
	ListCommentRepliesResponse   = discussionrpc.ListCommentRepliesResponse
	ListCommentsRequest          = discussionrpc.ListCommentsRequest
	ListCommentsResponse         = discussionrpc.ListCommentsResponse
	ListMessagesRequest          = discussionrpc.ListMessagesRequest
	ListMessagesResponse         = discussionrpc.ListMessagesResponse
	ListQuery                    = discussionrpc.ListQuery
	ListResult                   = discussionrpc.ListResult
	ListTalksRequest             = discussionrpc.ListTalksRequest
	ListTalksResponse            = discussionrpc.ListTalksResponse
	Message                      = discussionrpc.Message
	Talk                         = discussionrpc.Talk
	UpdateCommentRequest         = discussionrpc.UpdateCommentRequest
	UpdateCommentResponse        = discussionrpc.UpdateCommentResponse
	UpdateMessageRequest         = discussionrpc.UpdateMessageRequest
	UpdateMessageResponse        = discussionrpc.UpdateMessageResponse
	UpdateTalkRequest            = discussionrpc.UpdateTalkRequest
	UpdateTalkResponse           = discussionrpc.UpdateTalkResponse

	DiscussionService interface {
		// 查询留言列表
		ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
		// 查询留言
		GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
		// 创建留言
		CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error)
		// 更新留言
		UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error)
		// 批量删除留言
		BatchDeleteMessages(ctx context.Context, in *BatchDeleteMessagesRequest, opts ...grpc.CallOption) (*BatchDeleteMessagesResponse, error)
		// 部分更新留言（批量）
		BatchPatchMessages(ctx context.Context, in *BatchPatchMessagesRequest, opts ...grpc.CallOption) (*BatchPatchMessagesResponse, error)
		// 查询评论列表
		ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
		// 查询评论回复列表
		ListCommentReplies(ctx context.Context, in *ListCommentRepliesRequest, opts ...grpc.CallOption) (*ListCommentRepliesResponse, error)
		// 查询评论
		GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error)
		// 创建评论
		CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
		// 更新评论
		UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error)
		// 批量删除评论
		BatchDeleteComments(ctx context.Context, in *BatchDeleteCommentsRequest, opts ...grpc.CallOption) (*BatchDeleteCommentsResponse, error)
		// 部分更新评论（批量）
		BatchPatchComments(ctx context.Context, in *BatchPatchCommentsRequest, opts ...grpc.CallOption) (*BatchPatchCommentsResponse, error)
		// 查询评论回复数量
		GetCommentReplyCount(ctx context.Context, in *GetCommentReplyCountRequest, opts ...grpc.CallOption) (*GetCommentReplyCountResponse, error)
		// 点赞评论
		LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error)
		// 查询用户点赞的评论
		GetUserLikeComment(ctx context.Context, in *GetUserLikeCommentRequest, opts ...grpc.CallOption) (*GetUserLikeCommentResponse, error)
		// 分页查询说说列表
		ListTalks(ctx context.Context, in *ListTalksRequest, opts ...grpc.CallOption) (*ListTalksResponse, error)
		// 查询说说详情
		GetTalk(ctx context.Context, in *GetTalkRequest, opts ...grpc.CallOption) (*GetTalkResponse, error)
		// 创建说说
		CreateTalk(ctx context.Context, in *CreateTalkRequest, opts ...grpc.CallOption) (*CreateTalkResponse, error)
		// 更新说说
		UpdateTalk(ctx context.Context, in *UpdateTalkRequest, opts ...grpc.CallOption) (*UpdateTalkResponse, error)
		// 批量删除说说
		BatchDeleteTalks(ctx context.Context, in *BatchDeleteTalksRequest, opts ...grpc.CallOption) (*BatchDeleteTalksResponse, error)
		// 点赞说说
		LikeTalk(ctx context.Context, in *LikeTalkRequest, opts ...grpc.CallOption) (*LikeTalkResponse, error)
		// 查询用户点赞的说说
		GetUserLikeTalk(ctx context.Context, in *GetUserLikeTalkRequest, opts ...grpc.CallOption) (*GetUserLikeTalkResponse, error)
	}

	defaultDiscussionService struct {
		cli zrpc.Client
	}
)

func NewDiscussionService(cli zrpc.Client) DiscussionService {
	return &defaultDiscussionService{
		cli: cli,
	}
}

// 查询留言列表
func (m *defaultDiscussionService) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.ListMessages(ctx, in, opts...)
}

// 查询留言
func (m *defaultDiscussionService) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.GetMessage(ctx, in, opts...)
}

// 创建留言
func (m *defaultDiscussionService) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.CreateMessage(ctx, in, opts...)
}

// 更新留言
func (m *defaultDiscussionService) UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.UpdateMessage(ctx, in, opts...)
}

// 批量删除留言
func (m *defaultDiscussionService) BatchDeleteMessages(ctx context.Context, in *BatchDeleteMessagesRequest, opts ...grpc.CallOption) (*BatchDeleteMessagesResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.BatchDeleteMessages(ctx, in, opts...)
}

// 部分更新留言（批量）
func (m *defaultDiscussionService) BatchPatchMessages(ctx context.Context, in *BatchPatchMessagesRequest, opts ...grpc.CallOption) (*BatchPatchMessagesResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.BatchPatchMessages(ctx, in, opts...)
}

// 查询评论列表
func (m *defaultDiscussionService) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.ListComments(ctx, in, opts...)
}

// 查询评论回复列表
func (m *defaultDiscussionService) ListCommentReplies(ctx context.Context, in *ListCommentRepliesRequest, opts ...grpc.CallOption) (*ListCommentRepliesResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.ListCommentReplies(ctx, in, opts...)
}

// 查询评论
func (m *defaultDiscussionService) GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.GetComment(ctx, in, opts...)
}

// 创建评论
func (m *defaultDiscussionService) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

// 更新评论
func (m *defaultDiscussionService) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.UpdateComment(ctx, in, opts...)
}

// 批量删除评论
func (m *defaultDiscussionService) BatchDeleteComments(ctx context.Context, in *BatchDeleteCommentsRequest, opts ...grpc.CallOption) (*BatchDeleteCommentsResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.BatchDeleteComments(ctx, in, opts...)
}

// 部分更新评论（批量）
func (m *defaultDiscussionService) BatchPatchComments(ctx context.Context, in *BatchPatchCommentsRequest, opts ...grpc.CallOption) (*BatchPatchCommentsResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.BatchPatchComments(ctx, in, opts...)
}

// 查询评论回复数量
func (m *defaultDiscussionService) GetCommentReplyCount(ctx context.Context, in *GetCommentReplyCountRequest, opts ...grpc.CallOption) (*GetCommentReplyCountResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.GetCommentReplyCount(ctx, in, opts...)
}

// 点赞评论
func (m *defaultDiscussionService) LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.LikeComment(ctx, in, opts...)
}

// 查询用户点赞的评论
func (m *defaultDiscussionService) GetUserLikeComment(ctx context.Context, in *GetUserLikeCommentRequest, opts ...grpc.CallOption) (*GetUserLikeCommentResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.GetUserLikeComment(ctx, in, opts...)
}

// 分页查询说说列表
func (m *defaultDiscussionService) ListTalks(ctx context.Context, in *ListTalksRequest, opts ...grpc.CallOption) (*ListTalksResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.ListTalks(ctx, in, opts...)
}

// 查询说说详情
func (m *defaultDiscussionService) GetTalk(ctx context.Context, in *GetTalkRequest, opts ...grpc.CallOption) (*GetTalkResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.GetTalk(ctx, in, opts...)
}

// 创建说说
func (m *defaultDiscussionService) CreateTalk(ctx context.Context, in *CreateTalkRequest, opts ...grpc.CallOption) (*CreateTalkResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.CreateTalk(ctx, in, opts...)
}

// 更新说说
func (m *defaultDiscussionService) UpdateTalk(ctx context.Context, in *UpdateTalkRequest, opts ...grpc.CallOption) (*UpdateTalkResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.UpdateTalk(ctx, in, opts...)
}

// 批量删除说说
func (m *defaultDiscussionService) BatchDeleteTalks(ctx context.Context, in *BatchDeleteTalksRequest, opts ...grpc.CallOption) (*BatchDeleteTalksResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.BatchDeleteTalks(ctx, in, opts...)
}

// 点赞说说
func (m *defaultDiscussionService) LikeTalk(ctx context.Context, in *LikeTalkRequest, opts ...grpc.CallOption) (*LikeTalkResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.LikeTalk(ctx, in, opts...)
}

// 查询用户点赞的说说
func (m *defaultDiscussionService) GetUserLikeTalk(ctx context.Context, in *GetUserLikeTalkRequest, opts ...grpc.CallOption) (*GetUserLikeTalkResponse, error) {
	client := discussionrpc.NewDiscussionServiceClient(m.cli.Conn())
	return client.GetUserLikeTalk(ctx, in, opts...)
}
