// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: access.proto

package accessrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AccessService_ListApis_FullMethodName          = "/blog.access.v1.AccessService/ListApis"
	AccessService_CreateApi_FullMethodName         = "/blog.access.v1.AccessService/CreateApi"
	AccessService_UpdateApi_FullMethodName         = "/blog.access.v1.AccessService/UpdateApi"
	AccessService_BatchDeleteApis_FullMethodName   = "/blog.access.v1.AccessService/BatchDeleteApis"
	AccessService_SyncApis_FullMethodName          = "/blog.access.v1.AccessService/SyncApis"
	AccessService_CleanApis_FullMethodName         = "/blog.access.v1.AccessService/CleanApis"
	AccessService_ListMenus_FullMethodName         = "/blog.access.v1.AccessService/ListMenus"
	AccessService_CreateMenu_FullMethodName        = "/blog.access.v1.AccessService/CreateMenu"
	AccessService_UpdateMenu_FullMethodName        = "/blog.access.v1.AccessService/UpdateMenu"
	AccessService_BatchDeleteMenus_FullMethodName  = "/blog.access.v1.AccessService/BatchDeleteMenus"
	AccessService_SyncMenus_FullMethodName         = "/blog.access.v1.AccessService/SyncMenus"
	AccessService_CleanMenus_FullMethodName        = "/blog.access.v1.AccessService/CleanMenus"
	AccessService_ListRoles_FullMethodName         = "/blog.access.v1.AccessService/ListRoles"
	AccessService_CreateRole_FullMethodName        = "/blog.access.v1.AccessService/CreateRole"
	AccessService_UpdateRole_FullMethodName        = "/blog.access.v1.AccessService/UpdateRole"
	AccessService_BatchDeleteRoles_FullMethodName  = "/blog.access.v1.AccessService/BatchDeleteRoles"
	AccessService_UpdateRoleMenu_FullMethodName    = "/blog.access.v1.AccessService/UpdateRoleMenu"
	AccessService_UpdateRoleApi_FullMethodName     = "/blog.access.v1.AccessService/UpdateRoleApi"
	AccessService_GetRoleResource_FullMethodName   = "/blog.access.v1.AccessService/GetRoleResource"
	AccessService_UpdateUserRoles_FullMethodName   = "/blog.access.v1.AccessService/UpdateUserRoles"
	AccessService_GetUserApis_FullMethodName       = "/blog.access.v1.AccessService/GetUserApis"
	AccessService_GetUserMenus_FullMethodName      = "/blog.access.v1.AccessService/GetUserMenus"
	AccessService_ListUserRoles_FullMethodName     = "/blog.access.v1.AccessService/ListUserRoles"
	AccessService_BatchGetUserRoles_FullMethodName = "/blog.access.v1.AccessService/BatchGetUserRoles"
)

// AccessServiceClient is the client API for AccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessServiceClient interface {
	// 分页查询 API 列表
	ListApis(ctx context.Context, in *ListApisRequest, opts ...grpc.CallOption) (*ListApisResponse, error)
	// 创建 API
	CreateApi(ctx context.Context, in *CreateApiRequest, opts ...grpc.CallOption) (*CreateApiResponse, error)
	// 更新 API
	UpdateApi(ctx context.Context, in *UpdateApiRequest, opts ...grpc.CallOption) (*UpdateApiResponse, error)
	// 批量删除 API
	BatchDeleteApis(ctx context.Context, in *BatchDeleteApisRequest, opts ...grpc.CallOption) (*BatchDeleteApisResponse, error)
	// 同步 API
	SyncApis(ctx context.Context, in *SyncApisRequest, opts ...grpc.CallOption) (*SyncApisResponse, error)
	// 清空 API
	CleanApis(ctx context.Context, in *CleanApisRequest, opts ...grpc.CallOption) (*CleanApisResponse, error)
	// 分页查询菜单列表
	ListMenus(ctx context.Context, in *ListMenusRequest, opts ...grpc.CallOption) (*ListMenusResponse, error)
	// 创建菜单
	CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*CreateMenuResponse, error)
	// 更新菜单
	UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*UpdateMenuResponse, error)
	// 批量删除菜单
	BatchDeleteMenus(ctx context.Context, in *BatchDeleteMenusRequest, opts ...grpc.CallOption) (*BatchDeleteMenusResponse, error)
	// 同步菜单
	SyncMenus(ctx context.Context, in *SyncMenusRequest, opts ...grpc.CallOption) (*SyncMenusResponse, error)
	// 清空菜单
	CleanMenus(ctx context.Context, in *CleanMenusRequest, opts ...grpc.CallOption) (*CleanMenusResponse, error)
	// 分页查询角色列表
	ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
	// 创建角色
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error)
	// 更新角色
	UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error)
	// 批量删除角色
	BatchDeleteRoles(ctx context.Context, in *BatchDeleteRolesRequest, opts ...grpc.CallOption) (*BatchDeleteRolesResponse, error)
	// 更新角色菜单资源
	UpdateRoleMenu(ctx context.Context, in *UpdateRoleMenuRequest, opts ...grpc.CallOption) (*UpdateRoleMenuResponse, error)
	// 更新角色 API 资源
	UpdateRoleApi(ctx context.Context, in *UpdateRoleApiRequest, opts ...grpc.CallOption) (*UpdateRoleApiResponse, error)
	// 查询角色资源
	GetRoleResource(ctx context.Context, in *GetRoleResourceRequest, opts ...grpc.CallOption) (*GetRoleResourceResponse, error)
	// 更新用户角色
	UpdateUserRoles(ctx context.Context, in *UpdateUserRolesRequest, opts ...grpc.CallOption) (*UpdateUserRolesResponse, error)
	// 查询用户 API 权限
	GetUserApis(ctx context.Context, in *GetUserApisRequest, opts ...grpc.CallOption) (*GetUserApisResponse, error)
	// 查询用户菜单权限
	GetUserMenus(ctx context.Context, in *GetUserMenusRequest, opts ...grpc.CallOption) (*GetUserMenusResponse, error)
	// 查询用户角色
	ListUserRoles(ctx context.Context, in *ListUserRolesRequest, opts ...grpc.CallOption) (*ListUserRolesResponse, error)
	// 批量查询用户角色
	BatchGetUserRoles(ctx context.Context, in *BatchGetUserRolesRequest, opts ...grpc.CallOption) (*BatchGetUserRolesResponse, error)
}

type accessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessServiceClient(cc grpc.ClientConnInterface) AccessServiceClient {
	return &accessServiceClient{cc}
}

func (c *accessServiceClient) ListApis(ctx context.Context, in *ListApisRequest, opts ...grpc.CallOption) (*ListApisResponse, error) {
	out := new(ListApisResponse)
	err := c.cc.Invoke(ctx, AccessService_ListApis_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) CreateApi(ctx context.Context, in *CreateApiRequest, opts ...grpc.CallOption) (*CreateApiResponse, error) {
	out := new(CreateApiResponse)
	err := c.cc.Invoke(ctx, AccessService_CreateApi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) UpdateApi(ctx context.Context, in *UpdateApiRequest, opts ...grpc.CallOption) (*UpdateApiResponse, error) {
	out := new(UpdateApiResponse)
	err := c.cc.Invoke(ctx, AccessService_UpdateApi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) BatchDeleteApis(ctx context.Context, in *BatchDeleteApisRequest, opts ...grpc.CallOption) (*BatchDeleteApisResponse, error) {
	out := new(BatchDeleteApisResponse)
	err := c.cc.Invoke(ctx, AccessService_BatchDeleteApis_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) SyncApis(ctx context.Context, in *SyncApisRequest, opts ...grpc.CallOption) (*SyncApisResponse, error) {
	out := new(SyncApisResponse)
	err := c.cc.Invoke(ctx, AccessService_SyncApis_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) CleanApis(ctx context.Context, in *CleanApisRequest, opts ...grpc.CallOption) (*CleanApisResponse, error) {
	out := new(CleanApisResponse)
	err := c.cc.Invoke(ctx, AccessService_CleanApis_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) ListMenus(ctx context.Context, in *ListMenusRequest, opts ...grpc.CallOption) (*ListMenusResponse, error) {
	out := new(ListMenusResponse)
	err := c.cc.Invoke(ctx, AccessService_ListMenus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*CreateMenuResponse, error) {
	out := new(CreateMenuResponse)
	err := c.cc.Invoke(ctx, AccessService_CreateMenu_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*UpdateMenuResponse, error) {
	out := new(UpdateMenuResponse)
	err := c.cc.Invoke(ctx, AccessService_UpdateMenu_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) BatchDeleteMenus(ctx context.Context, in *BatchDeleteMenusRequest, opts ...grpc.CallOption) (*BatchDeleteMenusResponse, error) {
	out := new(BatchDeleteMenusResponse)
	err := c.cc.Invoke(ctx, AccessService_BatchDeleteMenus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) SyncMenus(ctx context.Context, in *SyncMenusRequest, opts ...grpc.CallOption) (*SyncMenusResponse, error) {
	out := new(SyncMenusResponse)
	err := c.cc.Invoke(ctx, AccessService_SyncMenus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) CleanMenus(ctx context.Context, in *CleanMenusRequest, opts ...grpc.CallOption) (*CleanMenusResponse, error) {
	out := new(CleanMenusResponse)
	err := c.cc.Invoke(ctx, AccessService_CleanMenus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	out := new(ListRolesResponse)
	err := c.cc.Invoke(ctx, AccessService_ListRoles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error) {
	out := new(CreateRoleResponse)
	err := c.cc.Invoke(ctx, AccessService_CreateRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error) {
	out := new(UpdateRoleResponse)
	err := c.cc.Invoke(ctx, AccessService_UpdateRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) BatchDeleteRoles(ctx context.Context, in *BatchDeleteRolesRequest, opts ...grpc.CallOption) (*BatchDeleteRolesResponse, error) {
	out := new(BatchDeleteRolesResponse)
	err := c.cc.Invoke(ctx, AccessService_BatchDeleteRoles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) UpdateRoleMenu(ctx context.Context, in *UpdateRoleMenuRequest, opts ...grpc.CallOption) (*UpdateRoleMenuResponse, error) {
	out := new(UpdateRoleMenuResponse)
	err := c.cc.Invoke(ctx, AccessService_UpdateRoleMenu_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) UpdateRoleApi(ctx context.Context, in *UpdateRoleApiRequest, opts ...grpc.CallOption) (*UpdateRoleApiResponse, error) {
	out := new(UpdateRoleApiResponse)
	err := c.cc.Invoke(ctx, AccessService_UpdateRoleApi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) GetRoleResource(ctx context.Context, in *GetRoleResourceRequest, opts ...grpc.CallOption) (*GetRoleResourceResponse, error) {
	out := new(GetRoleResourceResponse)
	err := c.cc.Invoke(ctx, AccessService_GetRoleResource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) UpdateUserRoles(ctx context.Context, in *UpdateUserRolesRequest, opts ...grpc.CallOption) (*UpdateUserRolesResponse, error) {
	out := new(UpdateUserRolesResponse)
	err := c.cc.Invoke(ctx, AccessService_UpdateUserRoles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) GetUserApis(ctx context.Context, in *GetUserApisRequest, opts ...grpc.CallOption) (*GetUserApisResponse, error) {
	out := new(GetUserApisResponse)
	err := c.cc.Invoke(ctx, AccessService_GetUserApis_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) GetUserMenus(ctx context.Context, in *GetUserMenusRequest, opts ...grpc.CallOption) (*GetUserMenusResponse, error) {
	out := new(GetUserMenusResponse)
	err := c.cc.Invoke(ctx, AccessService_GetUserMenus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) ListUserRoles(ctx context.Context, in *ListUserRolesRequest, opts ...grpc.CallOption) (*ListUserRolesResponse, error) {
	out := new(ListUserRolesResponse)
	err := c.cc.Invoke(ctx, AccessService_ListUserRoles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) BatchGetUserRoles(ctx context.Context, in *BatchGetUserRolesRequest, opts ...grpc.CallOption) (*BatchGetUserRolesResponse, error) {
	out := new(BatchGetUserRolesResponse)
	err := c.cc.Invoke(ctx, AccessService_BatchGetUserRoles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessServiceServer is the server API for AccessService service.
// All implementations must embed UnimplementedAccessServiceServer
// for forward compatibility
type AccessServiceServer interface {
	// 分页查询 API 列表
	ListApis(context.Context, *ListApisRequest) (*ListApisResponse, error)
	// 创建 API
	CreateApi(context.Context, *CreateApiRequest) (*CreateApiResponse, error)
	// 更新 API
	UpdateApi(context.Context, *UpdateApiRequest) (*UpdateApiResponse, error)
	// 批量删除 API
	BatchDeleteApis(context.Context, *BatchDeleteApisRequest) (*BatchDeleteApisResponse, error)
	// 同步 API
	SyncApis(context.Context, *SyncApisRequest) (*SyncApisResponse, error)
	// 清空 API
	CleanApis(context.Context, *CleanApisRequest) (*CleanApisResponse, error)
	// 分页查询菜单列表
	ListMenus(context.Context, *ListMenusRequest) (*ListMenusResponse, error)
	// 创建菜单
	CreateMenu(context.Context, *CreateMenuRequest) (*CreateMenuResponse, error)
	// 更新菜单
	UpdateMenu(context.Context, *UpdateMenuRequest) (*UpdateMenuResponse, error)
	// 批量删除菜单
	BatchDeleteMenus(context.Context, *BatchDeleteMenusRequest) (*BatchDeleteMenusResponse, error)
	// 同步菜单
	SyncMenus(context.Context, *SyncMenusRequest) (*SyncMenusResponse, error)
	// 清空菜单
	CleanMenus(context.Context, *CleanMenusRequest) (*CleanMenusResponse, error)
	// 分页查询角色列表
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error)
	// 创建角色
	CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleResponse, error)
	// 更新角色
	UpdateRole(context.Context, *UpdateRoleRequest) (*UpdateRoleResponse, error)
	// 批量删除角色
	BatchDeleteRoles(context.Context, *BatchDeleteRolesRequest) (*BatchDeleteRolesResponse, error)
	// 更新角色菜单资源
	UpdateRoleMenu(context.Context, *UpdateRoleMenuRequest) (*UpdateRoleMenuResponse, error)
	// 更新角色 API 资源
	UpdateRoleApi(context.Context, *UpdateRoleApiRequest) (*UpdateRoleApiResponse, error)
	// 查询角色资源
	GetRoleResource(context.Context, *GetRoleResourceRequest) (*GetRoleResourceResponse, error)
	// 更新用户角色
	UpdateUserRoles(context.Context, *UpdateUserRolesRequest) (*UpdateUserRolesResponse, error)
	// 查询用户 API 权限
	GetUserApis(context.Context, *GetUserApisRequest) (*GetUserApisResponse, error)
	// 查询用户菜单权限
	GetUserMenus(context.Context, *GetUserMenusRequest) (*GetUserMenusResponse, error)
	// 查询用户角色
	ListUserRoles(context.Context, *ListUserRolesRequest) (*ListUserRolesResponse, error)
	// 批量查询用户角色
	BatchGetUserRoles(context.Context, *BatchGetUserRolesRequest) (*BatchGetUserRolesResponse, error)
	mustEmbedUnimplementedAccessServiceServer()
}

// UnimplementedAccessServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccessServiceServer struct {
}

func (UnimplementedAccessServiceServer) ListApis(context.Context, *ListApisRequest) (*ListApisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApis not implemented")
}
func (UnimplementedAccessServiceServer) CreateApi(context.Context, *CreateApiRequest) (*CreateApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApi not implemented")
}
func (UnimplementedAccessServiceServer) UpdateApi(context.Context, *UpdateApiRequest) (*UpdateApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApi not implemented")
}
func (UnimplementedAccessServiceServer) BatchDeleteApis(context.Context, *BatchDeleteApisRequest) (*BatchDeleteApisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteApis not implemented")
}
func (UnimplementedAccessServiceServer) SyncApis(context.Context, *SyncApisRequest) (*SyncApisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncApis not implemented")
}
func (UnimplementedAccessServiceServer) CleanApis(context.Context, *CleanApisRequest) (*CleanApisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanApis not implemented")
}
func (UnimplementedAccessServiceServer) ListMenus(context.Context, *ListMenusRequest) (*ListMenusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMenus not implemented")
}
func (UnimplementedAccessServiceServer) CreateMenu(context.Context, *CreateMenuRequest) (*CreateMenuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMenu not implemented")
}
func (UnimplementedAccessServiceServer) UpdateMenu(context.Context, *UpdateMenuRequest) (*UpdateMenuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMenu not implemented")
}
func (UnimplementedAccessServiceServer) BatchDeleteMenus(context.Context, *BatchDeleteMenusRequest) (*BatchDeleteMenusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteMenus not implemented")
}
func (UnimplementedAccessServiceServer) SyncMenus(context.Context, *SyncMenusRequest) (*SyncMenusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncMenus not implemented")
}
func (UnimplementedAccessServiceServer) CleanMenus(context.Context, *CleanMenusRequest) (*CleanMenusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanMenus not implemented")
}
func (UnimplementedAccessServiceServer) ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoles not implemented")
}
func (UnimplementedAccessServiceServer) CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedAccessServiceServer) UpdateRole(context.Context, *UpdateRoleRequest) (*UpdateRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRole not implemented")
}
func (UnimplementedAccessServiceServer) BatchDeleteRoles(context.Context, *BatchDeleteRolesRequest) (*BatchDeleteRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteRoles not implemented")
}
func (UnimplementedAccessServiceServer) UpdateRoleMenu(context.Context, *UpdateRoleMenuRequest) (*UpdateRoleMenuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoleMenu not implemented")
}
func (UnimplementedAccessServiceServer) UpdateRoleApi(context.Context, *UpdateRoleApiRequest) (*UpdateRoleApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoleApi not implemented")
}
func (UnimplementedAccessServiceServer) GetRoleResource(context.Context, *GetRoleResourceRequest) (*GetRoleResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleResource not implemented")
}
func (UnimplementedAccessServiceServer) UpdateUserRoles(context.Context, *UpdateUserRolesRequest) (*UpdateUserRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserRoles not implemented")
}
func (UnimplementedAccessServiceServer) GetUserApis(context.Context, *GetUserApisRequest) (*GetUserApisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserApis not implemented")
}
func (UnimplementedAccessServiceServer) GetUserMenus(context.Context, *GetUserMenusRequest) (*GetUserMenusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMenus not implemented")
}
func (UnimplementedAccessServiceServer) ListUserRoles(context.Context, *ListUserRolesRequest) (*ListUserRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserRoles not implemented")
}
func (UnimplementedAccessServiceServer) BatchGetUserRoles(context.Context, *BatchGetUserRolesRequest) (*BatchGetUserRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetUserRoles not implemented")
}
func (UnimplementedAccessServiceServer) mustEmbedUnimplementedAccessServiceServer() {}

// UnsafeAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessServiceServer will
// result in compilation errors.
type UnsafeAccessServiceServer interface {
	mustEmbedUnimplementedAccessServiceServer()
}

func RegisterAccessServiceServer(s grpc.ServiceRegistrar, srv AccessServiceServer) {
	s.RegisterService(&AccessService_ServiceDesc, srv)
}

func _AccessService_ListApis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).ListApis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_ListApis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).ListApis(ctx, req.(*ListApisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_CreateApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CreateApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CreateApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CreateApi(ctx, req.(*CreateApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_UpdateApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).UpdateApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_UpdateApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).UpdateApi(ctx, req.(*UpdateApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_BatchDeleteApis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteApisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).BatchDeleteApis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_BatchDeleteApis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).BatchDeleteApis(ctx, req.(*BatchDeleteApisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_SyncApis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncApisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).SyncApis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_SyncApis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).SyncApis(ctx, req.(*SyncApisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_CleanApis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanApisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CleanApis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CleanApis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CleanApis(ctx, req.(*CleanApisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_ListMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMenusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).ListMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_ListMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).ListMenus(ctx, req.(*ListMenusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_CreateMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CreateMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CreateMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CreateMenu(ctx, req.(*CreateMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_UpdateMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).UpdateMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_UpdateMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).UpdateMenu(ctx, req.(*UpdateMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_BatchDeleteMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteMenusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).BatchDeleteMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_BatchDeleteMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).BatchDeleteMenus(ctx, req.(*BatchDeleteMenusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_SyncMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMenusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).SyncMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_SyncMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).SyncMenus(ctx, req.(*SyncMenusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_CleanMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanMenusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CleanMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CleanMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CleanMenus(ctx, req.(*CleanMenusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_ListRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).ListRoles(ctx, req.(*ListRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_UpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).UpdateRole(ctx, req.(*UpdateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_BatchDeleteRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).BatchDeleteRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_BatchDeleteRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).BatchDeleteRoles(ctx, req.(*BatchDeleteRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_UpdateRoleMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).UpdateRoleMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_UpdateRoleMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).UpdateRoleMenu(ctx, req.(*UpdateRoleMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_UpdateRoleApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).UpdateRoleApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_UpdateRoleApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).UpdateRoleApi(ctx, req.(*UpdateRoleApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_GetRoleResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).GetRoleResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_GetRoleResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).GetRoleResource(ctx, req.(*GetRoleResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_UpdateUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).UpdateUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_UpdateUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).UpdateUserRoles(ctx, req.(*UpdateUserRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_GetUserApis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserApisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).GetUserApis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_GetUserApis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).GetUserApis(ctx, req.(*GetUserApisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_GetUserMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMenusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).GetUserMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_GetUserMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).GetUserMenus(ctx, req.(*GetUserMenusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_ListUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).ListUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_ListUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).ListUserRoles(ctx, req.(*ListUserRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_BatchGetUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetUserRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).BatchGetUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_BatchGetUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).BatchGetUserRoles(ctx, req.(*BatchGetUserRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessService_ServiceDesc is the grpc.ServiceDesc for AccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.access.v1.AccessService",
	HandlerType: (*AccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApis",
			Handler:    _AccessService_ListApis_Handler,
		},
		{
			MethodName: "CreateApi",
			Handler:    _AccessService_CreateApi_Handler,
		},
		{
			MethodName: "UpdateApi",
			Handler:    _AccessService_UpdateApi_Handler,
		},
		{
			MethodName: "BatchDeleteApis",
			Handler:    _AccessService_BatchDeleteApis_Handler,
		},
		{
			MethodName: "SyncApis",
			Handler:    _AccessService_SyncApis_Handler,
		},
		{
			MethodName: "CleanApis",
			Handler:    _AccessService_CleanApis_Handler,
		},
		{
			MethodName: "ListMenus",
			Handler:    _AccessService_ListMenus_Handler,
		},
		{
			MethodName: "CreateMenu",
			Handler:    _AccessService_CreateMenu_Handler,
		},
		{
			MethodName: "UpdateMenu",
			Handler:    _AccessService_UpdateMenu_Handler,
		},
		{
			MethodName: "BatchDeleteMenus",
			Handler:    _AccessService_BatchDeleteMenus_Handler,
		},
		{
			MethodName: "SyncMenus",
			Handler:    _AccessService_SyncMenus_Handler,
		},
		{
			MethodName: "CleanMenus",
			Handler:    _AccessService_CleanMenus_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _AccessService_ListRoles_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _AccessService_CreateRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _AccessService_UpdateRole_Handler,
		},
		{
			MethodName: "BatchDeleteRoles",
			Handler:    _AccessService_BatchDeleteRoles_Handler,
		},
		{
			MethodName: "UpdateRoleMenu",
			Handler:    _AccessService_UpdateRoleMenu_Handler,
		},
		{
			MethodName: "UpdateRoleApi",
			Handler:    _AccessService_UpdateRoleApi_Handler,
		},
		{
			MethodName: "GetRoleResource",
			Handler:    _AccessService_GetRoleResource_Handler,
		},
		{
			MethodName: "UpdateUserRoles",
			Handler:    _AccessService_UpdateUserRoles_Handler,
		},
		{
			MethodName: "GetUserApis",
			Handler:    _AccessService_GetUserApis_Handler,
		},
		{
			MethodName: "GetUserMenus",
			Handler:    _AccessService_GetUserMenus_Handler,
		},
		{
			MethodName: "ListUserRoles",
			Handler:    _AccessService_ListUserRoles_Handler,
		},
		{
			MethodName: "BatchGetUserRoles",
			Handler:    _AccessService_BatchGetUserRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access.proto",
}
