// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package server

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/logic/userservice"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/userrpc"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/svc"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	userrpc.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// 分页查询用户列表
func (s *UserServiceServer) ListUsers(ctx context.Context, in *userrpc.ListUsersRequest) (*userrpc.ListUsersResponse, error) {
	l := userservicelogic.NewListUsersLogic(ctx, s.svcCtx)
	return l.ListUsers(in)
}

// 查询用户详情
func (s *UserServiceServer) GetUser(ctx context.Context, in *userrpc.GetUserRequest) (*userrpc.GetUserResponse, error) {
	l := userservicelogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// 更新用户状态
func (s *UserServiceServer) PatchUser(ctx context.Context, in *userrpc.PatchUserRequest) (*userrpc.PatchUserResponse, error) {
	l := userservicelogic.NewPatchUserLogic(ctx, s.svcCtx)
	return l.PatchUser(in)
}

// 重置用户密码
func (s *UserServiceServer) ResetUserPassword(ctx context.Context, in *userrpc.ResetUserPasswordRequest) (*userrpc.ResetUserPasswordResponse, error) {
	l := userservicelogic.NewResetUserPasswordLogic(ctx, s.svcCtx)
	return l.ResetUserPassword(in)
}

// 获取当前用户详细资料
func (s *UserServiceServer) GetMe(ctx context.Context, in *userrpc.GetMeRequest) (*userrpc.GetMeResponse, error) {
	l := userservicelogic.NewGetMeLogic(ctx, s.svcCtx)
	return l.GetMe(in)
}

// 更新当前用户基础信息
func (s *UserServiceServer) UpdateMe(ctx context.Context, in *userrpc.UpdateMeRequest) (*userrpc.UpdateMeResponse, error) {
	l := userservicelogic.NewUpdateMeLogic(ctx, s.svcCtx)
	return l.UpdateMe(in)
}

// 更新当前用户头像
func (s *UserServiceServer) UpdateMeAvatar(ctx context.Context, in *userrpc.UpdateMeAvatarRequest) (*userrpc.UpdateMeAvatarResponse, error) {
	l := userservicelogic.NewUpdateMeAvatarLogic(ctx, s.svcCtx)
	return l.UpdateMeAvatar(in)
}

// 更新当前用户密码
func (s *UserServiceServer) UpdateMePassword(ctx context.Context, in *userrpc.UpdateMePasswordRequest) (*userrpc.UpdateMePasswordResponse, error) {
	l := userservicelogic.NewUpdateMePasswordLogic(ctx, s.svcCtx)
	return l.UpdateMePassword(in)
}

// 绑定当前用户邮箱
func (s *UserServiceServer) BindMeEmail(ctx context.Context, in *userrpc.BindMeEmailRequest) (*userrpc.BindMeEmailResponse, error) {
	l := userservicelogic.NewBindMeEmailLogic(ctx, s.svcCtx)
	return l.BindMeEmail(in)
}

// 绑定当前用户手机号
func (s *UserServiceServer) BindMeMobile(ctx context.Context, in *userrpc.BindMeMobileRequest) (*userrpc.BindMeMobileResponse, error) {
	l := userservicelogic.NewBindMeMobileLogic(ctx, s.svcCtx)
	return l.BindMeMobile(in)
}

// 绑定当前用户第三方平台
func (s *UserServiceServer) BindMeThirdParty(ctx context.Context, in *userrpc.BindMeThirdPartyRequest) (*userrpc.BindMeThirdPartyResponse, error) {
	l := userservicelogic.NewBindMeThirdPartyLogic(ctx, s.svcCtx)
	return l.BindMeThirdParty(in)
}

// 解绑当前用户第三方平台
func (s *UserServiceServer) UnbindMeThirdParty(ctx context.Context, in *userrpc.UnbindMeThirdPartyRequest) (*userrpc.UnbindMeThirdPartyResponse, error) {
	l := userservicelogic.NewUnbindMeThirdPartyLogic(ctx, s.svcCtx)
	return l.UnbindMeThirdParty(in)
}

// 停用账号（进入冷静期）
func (s *UserServiceServer) DeactivateAccount(ctx context.Context, in *userrpc.DeactivateAccountRequest) (*userrpc.DeactivateAccountResponse, error) {
	l := userservicelogic.NewDeactivateAccountLogic(ctx, s.svcCtx)
	return l.DeactivateAccount(in)
}

// 恢复账号（冷静期内）
func (s *UserServiceServer) ReactivateAccount(ctx context.Context, in *userrpc.ReactivateAccountRequest) (*userrpc.ReactivateAccountResponse, error) {
	l := userservicelogic.NewReactivateAccountLogic(ctx, s.svcCtx)
	return l.ReactivateAccount(in)
}
