// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: access.proto

package server

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/logic/accessservice"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/accessrpc"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/svc"
)

type AccessServiceServer struct {
	svcCtx *svc.ServiceContext
	accessrpc.UnimplementedAccessServiceServer
}

func NewAccessServiceServer(svcCtx *svc.ServiceContext) *AccessServiceServer {
	return &AccessServiceServer{
		svcCtx: svcCtx,
	}
}

// 分页查询 API 列表
func (s *AccessServiceServer) ListApis(ctx context.Context, in *accessrpc.ListApisRequest) (*accessrpc.ListApisResponse, error) {
	l := accessservicelogic.NewListApisLogic(ctx, s.svcCtx)
	return l.ListApis(in)
}

// 创建 API
func (s *AccessServiceServer) CreateApi(ctx context.Context, in *accessrpc.CreateApiRequest) (*accessrpc.CreateApiResponse, error) {
	l := accessservicelogic.NewCreateApiLogic(ctx, s.svcCtx)
	return l.CreateApi(in)
}

// 更新 API
func (s *AccessServiceServer) UpdateApi(ctx context.Context, in *accessrpc.UpdateApiRequest) (*accessrpc.UpdateApiResponse, error) {
	l := accessservicelogic.NewUpdateApiLogic(ctx, s.svcCtx)
	return l.UpdateApi(in)
}

// 批量删除 API
func (s *AccessServiceServer) BatchDeleteApis(ctx context.Context, in *accessrpc.BatchDeleteApisRequest) (*accessrpc.BatchDeleteApisResponse, error) {
	l := accessservicelogic.NewBatchDeleteApisLogic(ctx, s.svcCtx)
	return l.BatchDeleteApis(in)
}

// 同步 API
func (s *AccessServiceServer) SyncApis(ctx context.Context, in *accessrpc.SyncApisRequest) (*accessrpc.SyncApisResponse, error) {
	l := accessservicelogic.NewSyncApisLogic(ctx, s.svcCtx)
	return l.SyncApis(in)
}

// 清空 API
func (s *AccessServiceServer) CleanApis(ctx context.Context, in *accessrpc.CleanApisRequest) (*accessrpc.CleanApisResponse, error) {
	l := accessservicelogic.NewCleanApisLogic(ctx, s.svcCtx)
	return l.CleanApis(in)
}

// 分页查询菜单列表
func (s *AccessServiceServer) ListMenus(ctx context.Context, in *accessrpc.ListMenusRequest) (*accessrpc.ListMenusResponse, error) {
	l := accessservicelogic.NewListMenusLogic(ctx, s.svcCtx)
	return l.ListMenus(in)
}

// 创建菜单
func (s *AccessServiceServer) CreateMenu(ctx context.Context, in *accessrpc.CreateMenuRequest) (*accessrpc.CreateMenuResponse, error) {
	l := accessservicelogic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

// 更新菜单
func (s *AccessServiceServer) UpdateMenu(ctx context.Context, in *accessrpc.UpdateMenuRequest) (*accessrpc.UpdateMenuResponse, error) {
	l := accessservicelogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

// 批量删除菜单
func (s *AccessServiceServer) BatchDeleteMenus(ctx context.Context, in *accessrpc.BatchDeleteMenusRequest) (*accessrpc.BatchDeleteMenusResponse, error) {
	l := accessservicelogic.NewBatchDeleteMenusLogic(ctx, s.svcCtx)
	return l.BatchDeleteMenus(in)
}

// 同步菜单
func (s *AccessServiceServer) SyncMenus(ctx context.Context, in *accessrpc.SyncMenusRequest) (*accessrpc.SyncMenusResponse, error) {
	l := accessservicelogic.NewSyncMenusLogic(ctx, s.svcCtx)
	return l.SyncMenus(in)
}

// 清空菜单
func (s *AccessServiceServer) CleanMenus(ctx context.Context, in *accessrpc.CleanMenusRequest) (*accessrpc.CleanMenusResponse, error) {
	l := accessservicelogic.NewCleanMenusLogic(ctx, s.svcCtx)
	return l.CleanMenus(in)
}

// 分页查询角色列表
func (s *AccessServiceServer) ListRoles(ctx context.Context, in *accessrpc.ListRolesRequest) (*accessrpc.ListRolesResponse, error) {
	l := accessservicelogic.NewListRolesLogic(ctx, s.svcCtx)
	return l.ListRoles(in)
}

// 创建角色
func (s *AccessServiceServer) CreateRole(ctx context.Context, in *accessrpc.CreateRoleRequest) (*accessrpc.CreateRoleResponse, error) {
	l := accessservicelogic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

// 更新角色
func (s *AccessServiceServer) UpdateRole(ctx context.Context, in *accessrpc.UpdateRoleRequest) (*accessrpc.UpdateRoleResponse, error) {
	l := accessservicelogic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

// 批量删除角色
func (s *AccessServiceServer) BatchDeleteRoles(ctx context.Context, in *accessrpc.BatchDeleteRolesRequest) (*accessrpc.BatchDeleteRolesResponse, error) {
	l := accessservicelogic.NewBatchDeleteRolesLogic(ctx, s.svcCtx)
	return l.BatchDeleteRoles(in)
}

// 更新角色菜单资源
func (s *AccessServiceServer) UpdateRoleMenu(ctx context.Context, in *accessrpc.UpdateRoleMenuRequest) (*accessrpc.UpdateRoleMenuResponse, error) {
	l := accessservicelogic.NewUpdateRoleMenuLogic(ctx, s.svcCtx)
	return l.UpdateRoleMenu(in)
}

// 更新角色 API 资源
func (s *AccessServiceServer) UpdateRoleApi(ctx context.Context, in *accessrpc.UpdateRoleApiRequest) (*accessrpc.UpdateRoleApiResponse, error) {
	l := accessservicelogic.NewUpdateRoleApiLogic(ctx, s.svcCtx)
	return l.UpdateRoleApi(in)
}

// 查询角色资源
func (s *AccessServiceServer) GetRoleResource(ctx context.Context, in *accessrpc.GetRoleResourceRequest) (*accessrpc.GetRoleResourceResponse, error) {
	l := accessservicelogic.NewGetRoleResourceLogic(ctx, s.svcCtx)
	return l.GetRoleResource(in)
}

// 更新用户角色
func (s *AccessServiceServer) UpdateUserRoles(ctx context.Context, in *accessrpc.UpdateUserRolesRequest) (*accessrpc.UpdateUserRolesResponse, error) {
	l := accessservicelogic.NewUpdateUserRolesLogic(ctx, s.svcCtx)
	return l.UpdateUserRoles(in)
}

// 查询用户 API 权限
func (s *AccessServiceServer) GetUserApis(ctx context.Context, in *accessrpc.GetUserApisRequest) (*accessrpc.GetUserApisResponse, error) {
	l := accessservicelogic.NewGetUserApisLogic(ctx, s.svcCtx)
	return l.GetUserApis(in)
}

// 查询用户菜单权限
func (s *AccessServiceServer) GetUserMenus(ctx context.Context, in *accessrpc.GetUserMenusRequest) (*accessrpc.GetUserMenusResponse, error) {
	l := accessservicelogic.NewGetUserMenusLogic(ctx, s.svcCtx)
	return l.GetUserMenus(in)
}

// 查询用户角色
func (s *AccessServiceServer) ListUserRoles(ctx context.Context, in *accessrpc.ListUserRolesRequest) (*accessrpc.ListUserRolesResponse, error) {
	l := accessservicelogic.NewListUserRolesLogic(ctx, s.svcCtx)
	return l.ListUserRoles(in)
}

// 批量查询用户角色
func (s *AccessServiceServer) BatchGetUserRoles(ctx context.Context, in *accessrpc.BatchGetUserRolesRequest) (*accessrpc.BatchGetUserRolesResponse, error) {
	l := accessservicelogic.NewBatchGetUserRolesLogic(ctx, s.svcCtx)
	return l.BatchGetUserRoles(in)
}
