// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateCommentReq struct {
	TopicId        int64  `json:"topic_id,optional"`
	ParentId       int64  `json:"parent_id,optional"`
	ReplyId        int64  `json:"reply_id,optional"`
	ReplyUserId    string `json:"reply_user_id,optional"`
	CommentContent string `json:"comment_content"`
	Status         int64  `json:"status,optional"`
	Type           int64  `json:"type"`
}

type LikeCommentReq struct {
	CommentId int64 `path:"id"`
}

type QueryCommentListReq struct {
	ListQuery
	TopicId  *int64 `json:"topic_id,optional"`
	ParentId *int64 `json:"parent_id,optional"`
	Type     *int64 `json:"type,optional"`
}

type QueryCommentReplyListReq struct {
	CommentId int64 `path:"comment_id"`
	ListQuery
	TopicId *int64 `json:"topic_id,optional"`
	Type    *int64 `json:"type,optional"`
}

type UpdateCommentReq struct {
	CommentId      int64  `path:"id"`
	ReplyUserId    string `json:"reply_user_id,optional"`
	CommentContent string `json:"comment_content"`
	Status         int64  `json:"status,optional"`
}
