// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: media.proto

package mediarpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MediaService_ListPhotos_FullMethodName         = "/blog.media.v1.MediaService/ListPhotos"
	MediaService_CreatePhoto_FullMethodName        = "/blog.media.v1.MediaService/CreatePhoto"
	MediaService_UpdatePhoto_FullMethodName        = "/blog.media.v1.MediaService/UpdatePhoto"
	MediaService_BatchPatchPhotos_FullMethodName   = "/blog.media.v1.MediaService/BatchPatchPhotos"
	MediaService_BatchDestroyPhotos_FullMethodName = "/blog.media.v1.MediaService/BatchDestroyPhotos"
	MediaService_ListAlbums_FullMethodName         = "/blog.media.v1.MediaService/ListAlbums"
	MediaService_GetAlbum_FullMethodName           = "/blog.media.v1.MediaService/GetAlbum"
	MediaService_CreateAlbum_FullMethodName        = "/blog.media.v1.MediaService/CreateAlbum"
	MediaService_UpdateAlbum_FullMethodName        = "/blog.media.v1.MediaService/UpdateAlbum"
	MediaService_BatchPatchAlbums_FullMethodName   = "/blog.media.v1.MediaService/BatchPatchAlbums"
	MediaService_BatchDestroyAlbums_FullMethodName = "/blog.media.v1.MediaService/BatchDestroyAlbums"
)

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaServiceClient interface {
	// 分页查询照片列表
	ListPhotos(ctx context.Context, in *ListPhotosRequest, opts ...grpc.CallOption) (*ListPhotosResponse, error)
	// 创建照片
	CreatePhoto(ctx context.Context, in *CreatePhotoRequest, opts ...grpc.CallOption) (*CreatePhotoResponse, error)
	// 更新照片
	UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*UpdatePhotoResponse, error)
	// 部分更新照片
	BatchPatchPhotos(ctx context.Context, in *BatchPatchPhotosRequest, opts ...grpc.CallOption) (*BatchPatchPhotosResponse, error)
	// 批量销毁照片（彻底删除，不可恢复）
	BatchDestroyPhotos(ctx context.Context, in *BatchDestroyPhotosRequest, opts ...grpc.CallOption) (*BatchDestroyPhotosResponse, error)
	// 分页查询相册列表
	ListAlbums(ctx context.Context, in *ListAlbumsRequest, opts ...grpc.CallOption) (*ListAlbumsResponse, error)
	// 查询相册详情
	GetAlbum(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*GetAlbumResponse, error)
	// 创建相册
	CreateAlbum(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*CreateAlbumResponse, error)
	// 更新相册
	UpdateAlbum(ctx context.Context, in *UpdateAlbumRequest, opts ...grpc.CallOption) (*UpdateAlbumResponse, error)
	// 部分更新相册
	BatchPatchAlbums(ctx context.Context, in *BatchPatchAlbumsRequest, opts ...grpc.CallOption) (*BatchPatchAlbumsResponse, error)
	// 批量销毁相册（彻底删除，不可恢复）
	BatchDestroyAlbums(ctx context.Context, in *BatchDestroyAlbumsRequest, opts ...grpc.CallOption) (*BatchDestroyAlbumsResponse, error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) ListPhotos(ctx context.Context, in *ListPhotosRequest, opts ...grpc.CallOption) (*ListPhotosResponse, error) {
	out := new(ListPhotosResponse)
	err := c.cc.Invoke(ctx, MediaService_ListPhotos_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) CreatePhoto(ctx context.Context, in *CreatePhotoRequest, opts ...grpc.CallOption) (*CreatePhotoResponse, error) {
	out := new(CreatePhotoResponse)
	err := c.cc.Invoke(ctx, MediaService_CreatePhoto_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*UpdatePhotoResponse, error) {
	out := new(UpdatePhotoResponse)
	err := c.cc.Invoke(ctx, MediaService_UpdatePhoto_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) BatchPatchPhotos(ctx context.Context, in *BatchPatchPhotosRequest, opts ...grpc.CallOption) (*BatchPatchPhotosResponse, error) {
	out := new(BatchPatchPhotosResponse)
	err := c.cc.Invoke(ctx, MediaService_BatchPatchPhotos_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) BatchDestroyPhotos(ctx context.Context, in *BatchDestroyPhotosRequest, opts ...grpc.CallOption) (*BatchDestroyPhotosResponse, error) {
	out := new(BatchDestroyPhotosResponse)
	err := c.cc.Invoke(ctx, MediaService_BatchDestroyPhotos_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) ListAlbums(ctx context.Context, in *ListAlbumsRequest, opts ...grpc.CallOption) (*ListAlbumsResponse, error) {
	out := new(ListAlbumsResponse)
	err := c.cc.Invoke(ctx, MediaService_ListAlbums_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetAlbum(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*GetAlbumResponse, error) {
	out := new(GetAlbumResponse)
	err := c.cc.Invoke(ctx, MediaService_GetAlbum_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) CreateAlbum(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*CreateAlbumResponse, error) {
	out := new(CreateAlbumResponse)
	err := c.cc.Invoke(ctx, MediaService_CreateAlbum_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) UpdateAlbum(ctx context.Context, in *UpdateAlbumRequest, opts ...grpc.CallOption) (*UpdateAlbumResponse, error) {
	out := new(UpdateAlbumResponse)
	err := c.cc.Invoke(ctx, MediaService_UpdateAlbum_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) BatchPatchAlbums(ctx context.Context, in *BatchPatchAlbumsRequest, opts ...grpc.CallOption) (*BatchPatchAlbumsResponse, error) {
	out := new(BatchPatchAlbumsResponse)
	err := c.cc.Invoke(ctx, MediaService_BatchPatchAlbums_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) BatchDestroyAlbums(ctx context.Context, in *BatchDestroyAlbumsRequest, opts ...grpc.CallOption) (*BatchDestroyAlbumsResponse, error) {
	out := new(BatchDestroyAlbumsResponse)
	err := c.cc.Invoke(ctx, MediaService_BatchDestroyAlbums_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServiceServer is the server API for MediaService service.
// All implementations must embed UnimplementedMediaServiceServer
// for forward compatibility
type MediaServiceServer interface {
	// 分页查询照片列表
	ListPhotos(context.Context, *ListPhotosRequest) (*ListPhotosResponse, error)
	// 创建照片
	CreatePhoto(context.Context, *CreatePhotoRequest) (*CreatePhotoResponse, error)
	// 更新照片
	UpdatePhoto(context.Context, *UpdatePhotoRequest) (*UpdatePhotoResponse, error)
	// 部分更新照片
	BatchPatchPhotos(context.Context, *BatchPatchPhotosRequest) (*BatchPatchPhotosResponse, error)
	// 批量销毁照片（彻底删除，不可恢复）
	BatchDestroyPhotos(context.Context, *BatchDestroyPhotosRequest) (*BatchDestroyPhotosResponse, error)
	// 分页查询相册列表
	ListAlbums(context.Context, *ListAlbumsRequest) (*ListAlbumsResponse, error)
	// 查询相册详情
	GetAlbum(context.Context, *GetAlbumRequest) (*GetAlbumResponse, error)
	// 创建相册
	CreateAlbum(context.Context, *CreateAlbumRequest) (*CreateAlbumResponse, error)
	// 更新相册
	UpdateAlbum(context.Context, *UpdateAlbumRequest) (*UpdateAlbumResponse, error)
	// 部分更新相册
	BatchPatchAlbums(context.Context, *BatchPatchAlbumsRequest) (*BatchPatchAlbumsResponse, error)
	// 批量销毁相册（彻底删除，不可恢复）
	BatchDestroyAlbums(context.Context, *BatchDestroyAlbumsRequest) (*BatchDestroyAlbumsResponse, error)
	mustEmbedUnimplementedMediaServiceServer()
}

// UnimplementedMediaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMediaServiceServer struct {
}

func (UnimplementedMediaServiceServer) ListPhotos(context.Context, *ListPhotosRequest) (*ListPhotosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPhotos not implemented")
}
func (UnimplementedMediaServiceServer) CreatePhoto(context.Context, *CreatePhotoRequest) (*CreatePhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePhoto not implemented")
}
func (UnimplementedMediaServiceServer) UpdatePhoto(context.Context, *UpdatePhotoRequest) (*UpdatePhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePhoto not implemented")
}
func (UnimplementedMediaServiceServer) BatchPatchPhotos(context.Context, *BatchPatchPhotosRequest) (*BatchPatchPhotosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPatchPhotos not implemented")
}
func (UnimplementedMediaServiceServer) BatchDestroyPhotos(context.Context, *BatchDestroyPhotosRequest) (*BatchDestroyPhotosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDestroyPhotos not implemented")
}
func (UnimplementedMediaServiceServer) ListAlbums(context.Context, *ListAlbumsRequest) (*ListAlbumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlbums not implemented")
}
func (UnimplementedMediaServiceServer) GetAlbum(context.Context, *GetAlbumRequest) (*GetAlbumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlbum not implemented")
}
func (UnimplementedMediaServiceServer) CreateAlbum(context.Context, *CreateAlbumRequest) (*CreateAlbumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlbum not implemented")
}
func (UnimplementedMediaServiceServer) UpdateAlbum(context.Context, *UpdateAlbumRequest) (*UpdateAlbumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAlbum not implemented")
}
func (UnimplementedMediaServiceServer) BatchPatchAlbums(context.Context, *BatchPatchAlbumsRequest) (*BatchPatchAlbumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPatchAlbums not implemented")
}
func (UnimplementedMediaServiceServer) BatchDestroyAlbums(context.Context, *BatchDestroyAlbumsRequest) (*BatchDestroyAlbumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDestroyAlbums not implemented")
}
func (UnimplementedMediaServiceServer) mustEmbedUnimplementedMediaServiceServer() {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_ListPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).ListPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_ListPhotos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).ListPhotos(ctx, req.(*ListPhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_CreatePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).CreatePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_CreatePhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).CreatePhoto(ctx, req.(*CreatePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_UpdatePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).UpdatePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_UpdatePhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).UpdatePhoto(ctx, req.(*UpdatePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_BatchPatchPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPatchPhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).BatchPatchPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_BatchPatchPhotos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).BatchPatchPhotos(ctx, req.(*BatchPatchPhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_BatchDestroyPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDestroyPhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).BatchDestroyPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_BatchDestroyPhotos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).BatchDestroyPhotos(ctx, req.(*BatchDestroyPhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_ListAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).ListAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_ListAlbums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).ListAlbums(ctx, req.(*ListAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetAlbum(ctx, req.(*GetAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_CreateAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).CreateAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_CreateAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).CreateAlbum(ctx, req.(*CreateAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_UpdateAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).UpdateAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_UpdateAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).UpdateAlbum(ctx, req.(*UpdateAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_BatchPatchAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPatchAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).BatchPatchAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_BatchPatchAlbums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).BatchPatchAlbums(ctx, req.(*BatchPatchAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_BatchDestroyAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDestroyAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).BatchDestroyAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_BatchDestroyAlbums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).BatchDestroyAlbums(ctx, req.(*BatchDestroyAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.media.v1.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPhotos",
			Handler:    _MediaService_ListPhotos_Handler,
		},
		{
			MethodName: "CreatePhoto",
			Handler:    _MediaService_CreatePhoto_Handler,
		},
		{
			MethodName: "UpdatePhoto",
			Handler:    _MediaService_UpdatePhoto_Handler,
		},
		{
			MethodName: "BatchPatchPhotos",
			Handler:    _MediaService_BatchPatchPhotos_Handler,
		},
		{
			MethodName: "BatchDestroyPhotos",
			Handler:    _MediaService_BatchDestroyPhotos_Handler,
		},
		{
			MethodName: "ListAlbums",
			Handler:    _MediaService_ListAlbums_Handler,
		},
		{
			MethodName: "GetAlbum",
			Handler:    _MediaService_GetAlbum_Handler,
		},
		{
			MethodName: "CreateAlbum",
			Handler:    _MediaService_CreateAlbum_Handler,
		},
		{
			MethodName: "UpdateAlbum",
			Handler:    _MediaService_UpdateAlbum_Handler,
		},
		{
			MethodName: "BatchPatchAlbums",
			Handler:    _MediaService_BatchPatchAlbums_Handler,
		},
		{
			MethodName: "BatchDestroyAlbums",
			Handler:    _MediaService_BatchDestroyAlbums_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "media.proto",
}
