// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: stats.proto

package server

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/logic/statsservice"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/statsrpc"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/svc"
)

type StatsServiceServer struct {
	svcCtx *svc.ServiceContext
	statsrpc.UnimplementedStatsServiceServer
}

func NewStatsServiceServer(svcCtx *svc.ServiceContext) *StatsServiceServer {
	return &StatsServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取仪表盘统计数据
func (s *StatsServiceServer) GetDashboardStats(ctx context.Context, in *statsrpc.GetDashboardStatsRequest) (*statsrpc.GetDashboardStatsResponse, error) {
	l := statsservicelogic.NewGetDashboardStatsLogic(ctx, s.svcCtx)
	return l.GetDashboardStats(in)
}

// 获取文章分析数据
func (s *StatsServiceServer) GetArticleStats(ctx context.Context, in *statsrpc.GetArticleStatsRequest) (*statsrpc.GetArticleStatsResponse, error) {
	l := statsservicelogic.NewGetArticleStatsLogic(ctx, s.svcCtx)
	return l.GetArticleStats(in)
}

// 获取每日统计趋势
func (s *StatsServiceServer) GetStatsTrend(ctx context.Context, in *statsrpc.GetStatsTrendRequest) (*statsrpc.GetStatsTrendResponse, error) {
	l := statsservicelogic.NewGetStatsTrendLogic(ctx, s.svcCtx)
	return l.GetStatsTrend(in)
}

// 获取用户与访客的地区分布
func (s *StatsServiceServer) GetGeoStats(ctx context.Context, in *statsrpc.GetGeoStatsRequest) (*statsrpc.GetGeoStatsResponse, error) {
	l := statsservicelogic.NewGetGeoStatsLogic(ctx, s.svcCtx)
	return l.GetGeoStats(in)
}
