// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: content.proto

package server

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/logic/contentservice"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/contentrpc"
	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/svc"
)

type ContentServiceServer struct {
	svcCtx *svc.ServiceContext
	contentrpc.UnimplementedContentServiceServer
}

func NewContentServiceServer(svcCtx *svc.ServiceContext) *ContentServiceServer {
	return &ContentServiceServer{
		svcCtx: svcCtx,
	}
}

// 分页查询文章列表
func (s *ContentServiceServer) ListArticles(ctx context.Context, in *contentrpc.ListArticlesRequest) (*contentrpc.ListArticlesResponse, error) {
	l := contentservicelogic.NewListArticlesLogic(ctx, s.svcCtx)
	return l.ListArticles(in)
}

// 分页查询文章预览列表
func (s *ContentServiceServer) ListArticlePreviews(ctx context.Context, in *contentrpc.ListArticlePreviewsRequest) (*contentrpc.ListArticlePreviewsResponse, error) {
	l := contentservicelogic.NewListArticlePreviewsLogic(ctx, s.svcCtx)
	return l.ListArticlePreviews(in)
}

// 查询文章详情
func (s *ContentServiceServer) GetArticle(ctx context.Context, in *contentrpc.GetArticleRequest) (*contentrpc.GetArticleResponse, error) {
	l := contentservicelogic.NewGetArticleLogic(ctx, s.svcCtx)
	return l.GetArticle(in)
}

// 查询关联文章
func (s *ContentServiceServer) GetArticleRelation(ctx context.Context, in *contentrpc.GetArticleRelationRequest) (*contentrpc.GetArticleRelationResponse, error) {
	l := contentservicelogic.NewGetArticleRelationLogic(ctx, s.svcCtx)
	return l.GetArticleRelation(in)
}

// 创建文章
func (s *ContentServiceServer) CreateArticle(ctx context.Context, in *contentrpc.CreateArticleRequest) (*contentrpc.CreateArticleResponse, error) {
	l := contentservicelogic.NewCreateArticleLogic(ctx, s.svcCtx)
	return l.CreateArticle(in)
}

// 更新文章
func (s *ContentServiceServer) UpdateArticle(ctx context.Context, in *contentrpc.UpdateArticleRequest) (*contentrpc.UpdateArticleResponse, error) {
	l := contentservicelogic.NewUpdateArticleLogic(ctx, s.svcCtx)
	return l.UpdateArticle(in)
}

// 部分更新文章
func (s *ContentServiceServer) PatchArticle(ctx context.Context, in *contentrpc.PatchArticleRequest) (*contentrpc.PatchArticleResponse, error) {
	l := contentservicelogic.NewPatchArticleLogic(ctx, s.svcCtx)
	return l.PatchArticle(in)
}

// 批量删除文章
func (s *ContentServiceServer) BatchDeleteArticles(ctx context.Context, in *contentrpc.BatchDeleteArticlesRequest) (*contentrpc.BatchDeleteArticlesResponse, error) {
	l := contentservicelogic.NewBatchDeleteArticlesLogic(ctx, s.svcCtx)
	return l.BatchDeleteArticles(in)
}

// 增加文章浏览量
func (s *ContentServiceServer) IncrementArticleView(ctx context.Context, in *contentrpc.IncrementArticleViewRequest) (*contentrpc.IncrementArticleViewResponse, error) {
	l := contentservicelogic.NewIncrementArticleViewLogic(ctx, s.svcCtx)
	return l.IncrementArticleView(in)
}

// 点赞文章
func (s *ContentServiceServer) LikeArticle(ctx context.Context, in *contentrpc.LikeArticleRequest) (*contentrpc.LikeArticleResponse, error) {
	l := contentservicelogic.NewLikeArticleLogic(ctx, s.svcCtx)
	return l.LikeArticle(in)
}

// 查询用户点赞的文章
func (s *ContentServiceServer) GetUserLikeArticle(ctx context.Context, in *contentrpc.GetUserLikeArticleRequest) (*contentrpc.GetUserLikeArticleResponse, error) {
	l := contentservicelogic.NewGetUserLikeArticleLogic(ctx, s.svcCtx)
	return l.GetUserLikeArticle(in)
}

// 分页查询分类列表
func (s *ContentServiceServer) ListCategories(ctx context.Context, in *contentrpc.ListCategoriesRequest) (*contentrpc.ListCategoriesResponse, error) {
	l := contentservicelogic.NewListCategoriesLogic(ctx, s.svcCtx)
	return l.ListCategories(in)
}

// 查询分类详情
func (s *ContentServiceServer) GetCategory(ctx context.Context, in *contentrpc.GetCategoryRequest) (*contentrpc.GetCategoryResponse, error) {
	l := contentservicelogic.NewGetCategoryLogic(ctx, s.svcCtx)
	return l.GetCategory(in)
}

// 创建分类
func (s *ContentServiceServer) CreateCategory(ctx context.Context, in *contentrpc.CreateCategoryRequest) (*contentrpc.CreateCategoryResponse, error) {
	l := contentservicelogic.NewCreateCategoryLogic(ctx, s.svcCtx)
	return l.CreateCategory(in)
}

// 更新分类
func (s *ContentServiceServer) UpdateCategory(ctx context.Context, in *contentrpc.UpdateCategoryRequest) (*contentrpc.UpdateCategoryResponse, error) {
	l := contentservicelogic.NewUpdateCategoryLogic(ctx, s.svcCtx)
	return l.UpdateCategory(in)
}

// 批量删除分类
func (s *ContentServiceServer) BatchDeleteCategories(ctx context.Context, in *contentrpc.BatchDeleteCategoriesRequest) (*contentrpc.BatchDeleteCategoriesResponse, error) {
	l := contentservicelogic.NewBatchDeleteCategoriesLogic(ctx, s.svcCtx)
	return l.BatchDeleteCategories(in)
}

// 分页查询标签列表
func (s *ContentServiceServer) ListTags(ctx context.Context, in *contentrpc.ListTagsRequest) (*contentrpc.ListTagsResponse, error) {
	l := contentservicelogic.NewListTagsLogic(ctx, s.svcCtx)
	return l.ListTags(in)
}

// 查询标签详情
func (s *ContentServiceServer) GetTag(ctx context.Context, in *contentrpc.GetTagRequest) (*contentrpc.GetTagResponse, error) {
	l := contentservicelogic.NewGetTagLogic(ctx, s.svcCtx)
	return l.GetTag(in)
}

// 创建标签
func (s *ContentServiceServer) CreateTag(ctx context.Context, in *contentrpc.CreateTagRequest) (*contentrpc.CreateTagResponse, error) {
	l := contentservicelogic.NewCreateTagLogic(ctx, s.svcCtx)
	return l.CreateTag(in)
}

// 更新标签
func (s *ContentServiceServer) UpdateTag(ctx context.Context, in *contentrpc.UpdateTagRequest) (*contentrpc.UpdateTagResponse, error) {
	l := contentservicelogic.NewUpdateTagLogic(ctx, s.svcCtx)
	return l.UpdateTag(in)
}

// 批量删除标签
func (s *ContentServiceServer) BatchDeleteTags(ctx context.Context, in *contentrpc.BatchDeleteTagsRequest) (*contentrpc.BatchDeleteTagsResponse, error) {
	l := contentservicelogic.NewBatchDeleteTagsLogic(ctx, s.svcCtx)
	return l.BatchDeleteTags(in)
}
