// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: content.proto

package contentservice

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/contentrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Article                       = contentrpc.Article
	ArticleCategory               = contentrpc.ArticleCategory
	ArticlePreview                = contentrpc.ArticlePreview
	ArticleTag                    = contentrpc.ArticleTag
	BatchDeleteArticlesRequest    = contentrpc.BatchDeleteArticlesRequest
	BatchDeleteArticlesResponse   = contentrpc.BatchDeleteArticlesResponse
	BatchDeleteCategoriesRequest  = contentrpc.BatchDeleteCategoriesRequest
	BatchDeleteCategoriesResponse = contentrpc.BatchDeleteCategoriesResponse
	BatchDeleteTagsRequest        = contentrpc.BatchDeleteTagsRequest
	BatchDeleteTagsResponse       = contentrpc.BatchDeleteTagsResponse
	Category                      = contentrpc.Category
	CreateArticleRequest          = contentrpc.CreateArticleRequest
	CreateArticleResponse         = contentrpc.CreateArticleResponse
	CreateCategoryRequest         = contentrpc.CreateCategoryRequest
	CreateCategoryResponse        = contentrpc.CreateCategoryResponse
	CreateTagRequest              = contentrpc.CreateTagRequest
	CreateTagResponse             = contentrpc.CreateTagResponse
	GetArticleRelationRequest     = contentrpc.GetArticleRelationRequest
	GetArticleRelationResponse    = contentrpc.GetArticleRelationResponse
	GetArticleRequest             = contentrpc.GetArticleRequest
	GetArticleResponse            = contentrpc.GetArticleResponse
	GetCategoryRequest            = contentrpc.GetCategoryRequest
	GetCategoryResponse           = contentrpc.GetCategoryResponse
	GetTagRequest                 = contentrpc.GetTagRequest
	GetTagResponse                = contentrpc.GetTagResponse
	GetUserLikeArticleRequest     = contentrpc.GetUserLikeArticleRequest
	GetUserLikeArticleResponse    = contentrpc.GetUserLikeArticleResponse
	IncrementArticleViewRequest   = contentrpc.IncrementArticleViewRequest
	IncrementArticleViewResponse  = contentrpc.IncrementArticleViewResponse
	LikeArticleRequest            = contentrpc.LikeArticleRequest
	LikeArticleResponse           = contentrpc.LikeArticleResponse
	ListArticlePreviewsRequest    = contentrpc.ListArticlePreviewsRequest
	ListArticlePreviewsResponse   = contentrpc.ListArticlePreviewsResponse
	ListArticlesRequest           = contentrpc.ListArticlesRequest
	ListArticlesResponse          = contentrpc.ListArticlesResponse
	ListCategoriesRequest         = contentrpc.ListCategoriesRequest
	ListCategoriesResponse        = contentrpc.ListCategoriesResponse
	ListQuery                     = contentrpc.ListQuery
	ListResult                    = contentrpc.ListResult
	ListTagsRequest               = contentrpc.ListTagsRequest
	ListTagsResponse              = contentrpc.ListTagsResponse
	PatchArticleRequest           = contentrpc.PatchArticleRequest
	PatchArticleResponse          = contentrpc.PatchArticleResponse
	Tag                           = contentrpc.Tag
	UpdateArticleRequest          = contentrpc.UpdateArticleRequest
	UpdateArticleResponse         = contentrpc.UpdateArticleResponse
	UpdateCategoryRequest         = contentrpc.UpdateCategoryRequest
	UpdateCategoryResponse        = contentrpc.UpdateCategoryResponse
	UpdateTagRequest              = contentrpc.UpdateTagRequest
	UpdateTagResponse             = contentrpc.UpdateTagResponse

	ContentService interface {
		// 分页查询文章列表
		ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error)
		// 分页查询文章预览列表
		ListArticlePreviews(ctx context.Context, in *ListArticlePreviewsRequest, opts ...grpc.CallOption) (*ListArticlePreviewsResponse, error)
		// 查询文章详情
		GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error)
		// 查询关联文章
		GetArticleRelation(ctx context.Context, in *GetArticleRelationRequest, opts ...grpc.CallOption) (*GetArticleRelationResponse, error)
		// 创建文章
		CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*CreateArticleResponse, error)
		// 更新文章
		UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error)
		// 部分更新文章
		PatchArticle(ctx context.Context, in *PatchArticleRequest, opts ...grpc.CallOption) (*PatchArticleResponse, error)
		// 批量删除文章
		BatchDeleteArticles(ctx context.Context, in *BatchDeleteArticlesRequest, opts ...grpc.CallOption) (*BatchDeleteArticlesResponse, error)
		// 增加文章浏览量
		IncrementArticleView(ctx context.Context, in *IncrementArticleViewRequest, opts ...grpc.CallOption) (*IncrementArticleViewResponse, error)
		// 点赞文章
		LikeArticle(ctx context.Context, in *LikeArticleRequest, opts ...grpc.CallOption) (*LikeArticleResponse, error)
		// 查询用户点赞的文章
		GetUserLikeArticle(ctx context.Context, in *GetUserLikeArticleRequest, opts ...grpc.CallOption) (*GetUserLikeArticleResponse, error)
		// 分页查询分类列表
		ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
		// 查询分类详情
		GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error)
		// 创建分类
		CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
		// 更新分类
		UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
		// 批量删除分类
		BatchDeleteCategories(ctx context.Context, in *BatchDeleteCategoriesRequest, opts ...grpc.CallOption) (*BatchDeleteCategoriesResponse, error)
		// 分页查询标签列表
		ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
		// 查询标签详情
		GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*GetTagResponse, error)
		// 创建标签
		CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
		// 更新标签
		UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error)
		// 批量删除标签
		BatchDeleteTags(ctx context.Context, in *BatchDeleteTagsRequest, opts ...grpc.CallOption) (*BatchDeleteTagsResponse, error)
	}

	defaultContentService struct {
		cli zrpc.Client
	}
)

func NewContentService(cli zrpc.Client) ContentService {
	return &defaultContentService{
		cli: cli,
	}
}

// 分页查询文章列表
func (m *defaultContentService) ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.ListArticles(ctx, in, opts...)
}

// 分页查询文章预览列表
func (m *defaultContentService) ListArticlePreviews(ctx context.Context, in *ListArticlePreviewsRequest, opts ...grpc.CallOption) (*ListArticlePreviewsResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.ListArticlePreviews(ctx, in, opts...)
}

// 查询文章详情
func (m *defaultContentService) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.GetArticle(ctx, in, opts...)
}

// 查询关联文章
func (m *defaultContentService) GetArticleRelation(ctx context.Context, in *GetArticleRelationRequest, opts ...grpc.CallOption) (*GetArticleRelationResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.GetArticleRelation(ctx, in, opts...)
}

// 创建文章
func (m *defaultContentService) CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*CreateArticleResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.CreateArticle(ctx, in, opts...)
}

// 更新文章
func (m *defaultContentService) UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.UpdateArticle(ctx, in, opts...)
}

// 部分更新文章
func (m *defaultContentService) PatchArticle(ctx context.Context, in *PatchArticleRequest, opts ...grpc.CallOption) (*PatchArticleResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.PatchArticle(ctx, in, opts...)
}

// 批量删除文章
func (m *defaultContentService) BatchDeleteArticles(ctx context.Context, in *BatchDeleteArticlesRequest, opts ...grpc.CallOption) (*BatchDeleteArticlesResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.BatchDeleteArticles(ctx, in, opts...)
}

// 增加文章浏览量
func (m *defaultContentService) IncrementArticleView(ctx context.Context, in *IncrementArticleViewRequest, opts ...grpc.CallOption) (*IncrementArticleViewResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.IncrementArticleView(ctx, in, opts...)
}

// 点赞文章
func (m *defaultContentService) LikeArticle(ctx context.Context, in *LikeArticleRequest, opts ...grpc.CallOption) (*LikeArticleResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.LikeArticle(ctx, in, opts...)
}

// 查询用户点赞的文章
func (m *defaultContentService) GetUserLikeArticle(ctx context.Context, in *GetUserLikeArticleRequest, opts ...grpc.CallOption) (*GetUserLikeArticleResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.GetUserLikeArticle(ctx, in, opts...)
}

// 分页查询分类列表
func (m *defaultContentService) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.ListCategories(ctx, in, opts...)
}

// 查询分类详情
func (m *defaultContentService) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.GetCategory(ctx, in, opts...)
}

// 创建分类
func (m *defaultContentService) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.CreateCategory(ctx, in, opts...)
}

// 更新分类
func (m *defaultContentService) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.UpdateCategory(ctx, in, opts...)
}

// 批量删除分类
func (m *defaultContentService) BatchDeleteCategories(ctx context.Context, in *BatchDeleteCategoriesRequest, opts ...grpc.CallOption) (*BatchDeleteCategoriesResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.BatchDeleteCategories(ctx, in, opts...)
}

// 分页查询标签列表
func (m *defaultContentService) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.ListTags(ctx, in, opts...)
}

// 查询标签详情
func (m *defaultContentService) GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*GetTagResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.GetTag(ctx, in, opts...)
}

// 创建标签
func (m *defaultContentService) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.CreateTag(ctx, in, opts...)
}

// 更新标签
func (m *defaultContentService) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.UpdateTag(ctx, in, opts...)
}

// 批量删除标签
func (m *defaultContentService) BatchDeleteTags(ctx context.Context, in *BatchDeleteTagsRequest, opts ...grpc.CallOption) (*BatchDeleteTagsResponse, error) {
	client := contentrpc.NewContentServiceClient(m.cli.Conn())
	return client.BatchDeleteTags(ctx, in, opts...)
}
