// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	accountauth "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/account/auth"
	accountguest "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/account/guest"
	accountme "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/account/me"
	commonupload "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/common/upload"
	commonwebsocket "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/common/websocket"
	contentarticle "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/content/article"
	contentcategory "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/content/category"
	contenttag "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/content/tag"
	discussioncomment "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/discussion/comment"
	discussionmessage "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/discussion/message"
	discussiontalk "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/discussion/talk"
	mediaalbum "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/media/album"
	mediaphoto "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/media/photo"
	siteconfig "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/site/config"
	sitefriend "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/site/friend"
	sitehome "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/site/home"
	sitepage "github.com/ve-weiyi/blog-cloud/api/app/internal/handler/site/page"
	"github.com/ve-weiyi/blog-cloud/api/app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 健康检查
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: PingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取验证码
				Method:  http.MethodGet,
				Path:    "/auth/captchas",
				Handler: accountauth.GetCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					// 发送邮箱验证码
					Method:  http.MethodPost,
					Path:    "/auth/email-verification-codes",
					Handler: accountauth.SendEmailCodeHandler(serverCtx),
				},
				{
					// 邮箱验证码登录（仅登录）
					Method:  http.MethodPost,
					Path:    "/auth/login-by-email",
					Handler: accountauth.EmailLoginHandler(serverCtx),
				},
				{
					// 手机验证码登录（自动注册）
					Method:  http.MethodPost,
					Path:    "/auth/login-by-mobile",
					Handler: accountauth.MobileLoginHandler(serverCtx),
				},
				{
					// 密码登录（账号/手机号/邮箱）
					Method:  http.MethodPost,
					Path:    "/auth/login-by-password",
					Handler: accountauth.PasswordLoginHandler(serverCtx),
				},
				{
					// 发送手机验证码
					Method:  http.MethodPost,
					Path:    "/auth/mobile-verification-codes",
					Handler: accountauth.SendMobileCodeHandler(serverCtx),
				},
				{
					// 获取第三方授权URL
					Method:  http.MethodGet,
					Path:    "/auth/oauth/:platform/authorize",
					Handler: accountauth.GetOauthAuthorizeUrlHandler(serverCtx),
				},
				{
					// 第三方登录（自动注册）
					Method:  http.MethodPost,
					Path:    "/auth/oauth/:platform/login",
					Handler: accountauth.OauthLoginHandler(serverCtx),
				},
				{
					// 重置密码
					Method:  http.MethodPost,
					Path:    "/auth/password-resets",
					Handler: accountauth.ResetPasswordHandler(serverCtx),
				},
				{
					// 刷新token
					Method:  http.MethodPost,
					Path:    "/auth/refresh-token",
					Handler: accountauth.RefreshTokenHandler(serverCtx),
				},
				{
					// 邮箱注册
					Method:  http.MethodPost,
					Path:    "/auth/register",
					Handler: accountauth.RegisterHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					// 退出登录（需登录）
					Method:  http.MethodDelete,
					Path:    "/auth/session",
					Handler: accountauth.LogoutHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取游客信息
				Method:  http.MethodGet,
				Path:    "/guests/current",
				Handler: accountguest.GetGuestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					// 绑定邮箱
					Method:  http.MethodPost,
					Path:    "/me/bind-email",
					Handler: accountme.BindMeEmailHandler(serverCtx),
				},
				{
					// 绑定手机号
					Method:  http.MethodPost,
					Path:    "/me/bind-mobile",
					Handler: accountme.BindMeMobileHandler(serverCtx),
				},
				{
					// 绑定第三方平台账号
					Method:  http.MethodPost,
					Path:    "/me/bind-third-party",
					Handler: accountme.BindMeThirdPartyHandler(serverCtx),
				},
				{
					// 停用账号（进入冷静期）
					Method:  http.MethodPost,
					Path:    "/me/deactivate",
					Handler: accountme.DeactivateAccountHandler(serverCtx),
				},
				{
					// 获取用户点赞集合
					Method:  http.MethodGet,
					Path:    "/me/likes",
					Handler: accountme.GetMeLikeHandler(serverCtx),
				},
				{
					// 获取当前用户信息
					Method:  http.MethodGet,
					Path:    "/me/profile",
					Handler: accountme.GetMeHandler(serverCtx),
				},
				{
					// 更新当前用户信息
					Method:  http.MethodPut,
					Path:    "/me/profile",
					Handler: accountme.UpdateMeHandler(serverCtx),
				},
				{
					// 恢复账号（冷静期内）
					Method:  http.MethodPost,
					Path:    "/me/reactivate",
					Handler: accountme.ReactivateAccountHandler(serverCtx),
				},
				{
					// 解绑第三方平台账号
					Method:  http.MethodPost,
					Path:    "/me/unbind-third-party",
					Handler: accountme.UnbindMeThirdPartyHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					// 上传文件（服务端上传）
					Method:  http.MethodPost,
					Path:    "/files",
					Handler: commonupload.UploadFileHandler(serverCtx),
				},
				{
					// 获取上传凭证（前端直传）
					Method:  http.MethodPost,
					Path:    "/upload-tokens",
					Handler: commonupload.CreateUploadTokenHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
		rest.WithMaxBytes(10485760),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// WebSocket消息
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler: commonwebsocket.WebsocketHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取文章列表
				Method:  http.MethodGet,
				Path:    "/articles",
				Handler: contentarticle.QueryArticleListHandler(serverCtx),
			},
			{
				// 获取文章详情
				Method:  http.MethodGet,
				Path:    "/articles/:id",
				Handler: contentarticle.GetArticleHandler(serverCtx),
			},
			{
				// 获取归档文章列表
				Method:  http.MethodGet,
				Path:    "/articles/archived",
				Handler: contentarticle.QueryArchivedArticleListHandler(serverCtx),
			},
			{
				// 获取推荐文章列表
				Method:  http.MethodGet,
				Path:    "/articles/recommended",
				Handler: contentarticle.QueryRecommendArticleListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					// 点赞文章
					Method:  http.MethodPost,
					Path:    "/articles/:id/like",
					Handler: contentarticle.LikeArticleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取分类列表
				Method:  http.MethodGet,
				Path:    "/categories",
				Handler: contentcategory.QueryCategoryListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取标签列表
				Method:  http.MethodGet,
				Path:    "/tags",
				Handler: contenttag.QueryTagListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取评论列表
				Method:  http.MethodGet,
				Path:    "/comments",
				Handler: discussioncomment.QueryCommentListHandler(serverCtx),
			},
			{
				// 获取评论回复列表
				Method:  http.MethodGet,
				Path:    "/comments/:comment_id/replies",
				Handler: discussioncomment.QueryCommentReplyListHandler(serverCtx),
			},
			{
				// 获取最新评论列表
				Method:  http.MethodGet,
				Path:    "/comments/recent",
				Handler: discussioncomment.QueryRecentCommentListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					// 创建评论
					Method:  http.MethodPost,
					Path:    "/comments",
					Handler: discussioncomment.CreateCommentHandler(serverCtx),
				},
				{
					// 更新评论
					Method:  http.MethodPut,
					Path:    "/comments/:id",
					Handler: discussioncomment.UpdateCommentHandler(serverCtx),
				},
				{
					// 点赞评论
					Method:  http.MethodPost,
					Path:    "/comments/:id/like",
					Handler: discussioncomment.LikeCommentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取留言列表
				Method:  http.MethodGet,
				Path:    "/messages",
				Handler: discussionmessage.QueryMessageListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					// 创建留言
					Method:  http.MethodPost,
					Path:    "/messages",
					Handler: discussionmessage.CreateMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取说说列表
				Method:  http.MethodGet,
				Path:    "/talks",
				Handler: discussiontalk.QueryTalkListHandler(serverCtx),
			},
			{
				// 获取说说详情
				Method:  http.MethodGet,
				Path:    "/talks/:id",
				Handler: discussiontalk.GetTalkHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					// 点赞说说
					Method:  http.MethodPost,
					Path:    "/talks/:id/like",
					Handler: discussiontalk.LikeTalkHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取相册列表
				Method:  http.MethodGet,
				Path:    "/albums",
				Handler: mediaalbum.QueryAlbumListHandler(serverCtx),
			},
			{
				// 获取相册详情
				Method:  http.MethodGet,
				Path:    "/albums/:id",
				Handler: mediaalbum.GetAlbumHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取相册下的照片列表
				Method:  http.MethodGet,
				Path:    "/albums/:album_id/photos",
				Handler: mediaphoto.QueryAlbumPhotoListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取关于我的信息
				Method:  http.MethodGet,
				Path:    "/about-me",
				Handler: siteconfig.GetAboutMeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取友链列表
				Method:  http.MethodGet,
				Path:    "/friends",
				Handler: sitefriend.QueryFriendListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取博客前台首页信息
				Method:  http.MethodGet,
				Path:    "/home",
				Handler: sitehome.GetBlogHomeInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取页面列表
				Method:  http.MethodGet,
				Path:    "/pages",
				Handler: sitepage.QueryPageListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
