// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: stats.proto

package statsrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StatsService_GetDashboardStats_FullMethodName = "/blog.stats.v1.StatsService/GetDashboardStats"
	StatsService_GetArticleStats_FullMethodName   = "/blog.stats.v1.StatsService/GetArticleStats"
	StatsService_GetStatsTrend_FullMethodName     = "/blog.stats.v1.StatsService/GetStatsTrend"
	StatsService_GetGeoStats_FullMethodName       = "/blog.stats.v1.StatsService/GetGeoStats"
)

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	// 获取仪表盘统计数据
	GetDashboardStats(ctx context.Context, in *GetDashboardStatsRequest, opts ...grpc.CallOption) (*GetDashboardStatsResponse, error)
	// 获取文章分析数据
	GetArticleStats(ctx context.Context, in *GetArticleStatsRequest, opts ...grpc.CallOption) (*GetArticleStatsResponse, error)
	// 获取每日统计趋势
	GetStatsTrend(ctx context.Context, in *GetStatsTrendRequest, opts ...grpc.CallOption) (*GetStatsTrendResponse, error)
	// 获取用户与访客的地区分布
	GetGeoStats(ctx context.Context, in *GetGeoStatsRequest, opts ...grpc.CallOption) (*GetGeoStatsResponse, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) GetDashboardStats(ctx context.Context, in *GetDashboardStatsRequest, opts ...grpc.CallOption) (*GetDashboardStatsResponse, error) {
	out := new(GetDashboardStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetDashboardStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetArticleStats(ctx context.Context, in *GetArticleStatsRequest, opts ...grpc.CallOption) (*GetArticleStatsResponse, error) {
	out := new(GetArticleStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetArticleStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetStatsTrend(ctx context.Context, in *GetStatsTrendRequest, opts ...grpc.CallOption) (*GetStatsTrendResponse, error) {
	out := new(GetStatsTrendResponse)
	err := c.cc.Invoke(ctx, StatsService_GetStatsTrend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetGeoStats(ctx context.Context, in *GetGeoStatsRequest, opts ...grpc.CallOption) (*GetGeoStatsResponse, error) {
	out := new(GetGeoStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetGeoStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility
type StatsServiceServer interface {
	// 获取仪表盘统计数据
	GetDashboardStats(context.Context, *GetDashboardStatsRequest) (*GetDashboardStatsResponse, error)
	// 获取文章分析数据
	GetArticleStats(context.Context, *GetArticleStatsRequest) (*GetArticleStatsResponse, error)
	// 获取每日统计趋势
	GetStatsTrend(context.Context, *GetStatsTrendRequest) (*GetStatsTrendResponse, error)
	// 获取用户与访客的地区分布
	GetGeoStats(context.Context, *GetGeoStatsRequest) (*GetGeoStatsResponse, error)
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatsServiceServer struct {
}

func (UnimplementedStatsServiceServer) GetDashboardStats(context.Context, *GetDashboardStatsRequest) (*GetDashboardStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardStats not implemented")
}
func (UnimplementedStatsServiceServer) GetArticleStats(context.Context, *GetArticleStatsRequest) (*GetArticleStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleStats not implemented")
}
func (UnimplementedStatsServiceServer) GetStatsTrend(context.Context, *GetStatsTrendRequest) (*GetStatsTrendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatsTrend not implemented")
}
func (UnimplementedStatsServiceServer) GetGeoStats(context.Context, *GetGeoStatsRequest) (*GetGeoStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeoStats not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_GetDashboardStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetDashboardStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetDashboardStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetDashboardStats(ctx, req.(*GetDashboardStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetArticleStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetArticleStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetArticleStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetArticleStats(ctx, req.(*GetArticleStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetStatsTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetStatsTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetStatsTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetStatsTrend(ctx, req.(*GetStatsTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetGeoStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGeoStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetGeoStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetGeoStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetGeoStats(ctx, req.(*GetGeoStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.stats.v1.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboardStats",
			Handler:    _StatsService_GetDashboardStats_Handler,
		},
		{
			MethodName: "GetArticleStats",
			Handler:    _StatsService_GetArticleStats_Handler,
		},
		{
			MethodName: "GetStatsTrend",
			Handler:    _StatsService_GetStatsTrend_Handler,
		},
		{
			MethodName: "GetGeoStats",
			Handler:    _StatsService_GetGeoStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}
