// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: notification.proto

package notificationrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NotificationService_ListNotifyTemplates_FullMethodName        = "/blog.notification.v1.NotificationService/ListNotifyTemplates"
	NotificationService_GetNotifyTemplate_FullMethodName          = "/blog.notification.v1.NotificationService/GetNotifyTemplate"
	NotificationService_CreateNotifyTemplate_FullMethodName       = "/blog.notification.v1.NotificationService/CreateNotifyTemplate"
	NotificationService_UpdateNotifyTemplate_FullMethodName       = "/blog.notification.v1.NotificationService/UpdateNotifyTemplate"
	NotificationService_BatchDeleteNotifyTemplates_FullMethodName = "/blog.notification.v1.NotificationService/BatchDeleteNotifyTemplates"
	NotificationService_ListNotifyMessages_FullMethodName         = "/blog.notification.v1.NotificationService/ListNotifyMessages"
	NotificationService_GetNotifyMessage_FullMethodName           = "/blog.notification.v1.NotificationService/GetNotifyMessage"
	NotificationService_CreateNotifyMessage_FullMethodName        = "/blog.notification.v1.NotificationService/CreateNotifyMessage"
	NotificationService_UpdateNotifyMessage_FullMethodName        = "/blog.notification.v1.NotificationService/UpdateNotifyMessage"
	NotificationService_BatchDeleteNotifyMessages_FullMethodName  = "/blog.notification.v1.NotificationService/BatchDeleteNotifyMessages"
	NotificationService_PublishNotifyMessage_FullMethodName       = "/blog.notification.v1.NotificationService/PublishNotifyMessage"
	NotificationService_RevokeNotifyMessage_FullMethodName        = "/blog.notification.v1.NotificationService/RevokeNotifyMessage"
	NotificationService_ListNotifyRecords_FullMethodName          = "/blog.notification.v1.NotificationService/ListNotifyRecords"
	NotificationService_BatchDeleteNotifyRecords_FullMethodName   = "/blog.notification.v1.NotificationService/BatchDeleteNotifyRecords"
	NotificationService_ListUserInboxRecords_FullMethodName       = "/blog.notification.v1.NotificationService/ListUserInboxRecords"
	NotificationService_MarkRecordRead_FullMethodName             = "/blog.notification.v1.NotificationService/MarkRecordRead"
	NotificationService_BatchMarkRecordsRead_FullMethodName       = "/blog.notification.v1.NotificationService/BatchMarkRecordsRead"
	NotificationService_MarkAllRecordsRead_FullMethodName         = "/blog.notification.v1.NotificationService/MarkAllRecordsRead"
	NotificationService_SendMobileCode_FullMethodName             = "/blog.notification.v1.NotificationService/SendMobileCode"
	NotificationService_VerifyMobileCode_FullMethodName           = "/blog.notification.v1.NotificationService/VerifyMobileCode"
	NotificationService_SendEmailCode_FullMethodName              = "/blog.notification.v1.NotificationService/SendEmailCode"
	NotificationService_VerifyEmailCode_FullMethodName            = "/blog.notification.v1.NotificationService/VerifyEmailCode"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	// 分页查询通知模板列表
	ListNotifyTemplates(ctx context.Context, in *ListNotifyTemplatesRequest, opts ...grpc.CallOption) (*ListNotifyTemplatesResponse, error)
	// 查询通知模板详情
	GetNotifyTemplate(ctx context.Context, in *GetNotifyTemplateRequest, opts ...grpc.CallOption) (*GetNotifyTemplateResponse, error)
	// 创建通知模板
	CreateNotifyTemplate(ctx context.Context, in *CreateNotifyTemplateRequest, opts ...grpc.CallOption) (*CreateNotifyTemplateResponse, error)
	// 更新通知模板
	UpdateNotifyTemplate(ctx context.Context, in *UpdateNotifyTemplateRequest, opts ...grpc.CallOption) (*UpdateNotifyTemplateResponse, error)
	// 批量删除通知模板
	BatchDeleteNotifyTemplates(ctx context.Context, in *BatchDeleteNotifyTemplatesRequest, opts ...grpc.CallOption) (*BatchDeleteNotifyTemplatesResponse, error)
	// 分页查询通知消息列表
	ListNotifyMessages(ctx context.Context, in *ListNotifyMessagesRequest, opts ...grpc.CallOption) (*ListNotifyMessagesResponse, error)
	// 查询通知消息详情
	GetNotifyMessage(ctx context.Context, in *GetNotifyMessageRequest, opts ...grpc.CallOption) (*GetNotifyMessageResponse, error)
	// 创建通知消息
	CreateNotifyMessage(ctx context.Context, in *CreateNotifyMessageRequest, opts ...grpc.CallOption) (*CreateNotifyMessageResponse, error)
	// 更新通知消息
	UpdateNotifyMessage(ctx context.Context, in *UpdateNotifyMessageRequest, opts ...grpc.CallOption) (*UpdateNotifyMessageResponse, error)
	// 批量删除通知消息
	BatchDeleteNotifyMessages(ctx context.Context, in *BatchDeleteNotifyMessagesRequest, opts ...grpc.CallOption) (*BatchDeleteNotifyMessagesResponse, error)
	// 发布通知消息
	PublishNotifyMessage(ctx context.Context, in *PublishNotifyMessageRequest, opts ...grpc.CallOption) (*PublishNotifyMessageResponse, error)
	// 撤销通知消息
	RevokeNotifyMessage(ctx context.Context, in *RevokeNotifyMessageRequest, opts ...grpc.CallOption) (*RevokeNotifyMessageResponse, error)
	// 分页查询投递记录列表
	ListNotifyRecords(ctx context.Context, in *ListNotifyRecordsRequest, opts ...grpc.CallOption) (*ListNotifyRecordsResponse, error)
	// 批量删除投递记录
	BatchDeleteNotifyRecords(ctx context.Context, in *BatchDeleteNotifyRecordsRequest, opts ...grpc.CallOption) (*BatchDeleteNotifyRecordsResponse, error)
	// 查询用户 inbox 投递列表
	ListUserInboxRecords(ctx context.Context, in *ListUserInboxRecordsRequest, opts ...grpc.CallOption) (*ListUserInboxRecordsResponse, error)
	// 标记单条 inbox 已读
	MarkRecordRead(ctx context.Context, in *MarkRecordReadRequest, opts ...grpc.CallOption) (*MarkRecordReadResponse, error)
	// 批量标记 inbox 已读
	BatchMarkRecordsRead(ctx context.Context, in *BatchMarkRecordsReadRequest, opts ...grpc.CallOption) (*BatchMarkRecordsReadResponse, error)
	// 全部标记 inbox 已读
	MarkAllRecordsRead(ctx context.Context, in *MarkAllRecordsReadRequest, opts ...grpc.CallOption) (*MarkAllRecordsReadResponse, error)
	// 发送手机验证码
	SendMobileCode(ctx context.Context, in *SendMobileCodeRequest, opts ...grpc.CallOption) (*SendMobileCodeResponse, error)
	// 校验手机验证码
	VerifyMobileCode(ctx context.Context, in *VerifyMobileCodeRequest, opts ...grpc.CallOption) (*VerifyMobileCodeResponse, error)
	// 发送邮箱验证码
	SendEmailCode(ctx context.Context, in *SendEmailCodeRequest, opts ...grpc.CallOption) (*SendEmailCodeResponse, error)
	// 校验邮箱验证码
	VerifyEmailCode(ctx context.Context, in *VerifyEmailCodeRequest, opts ...grpc.CallOption) (*VerifyEmailCodeResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) ListNotifyTemplates(ctx context.Context, in *ListNotifyTemplatesRequest, opts ...grpc.CallOption) (*ListNotifyTemplatesResponse, error) {
	out := new(ListNotifyTemplatesResponse)
	err := c.cc.Invoke(ctx, NotificationService_ListNotifyTemplates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetNotifyTemplate(ctx context.Context, in *GetNotifyTemplateRequest, opts ...grpc.CallOption) (*GetNotifyTemplateResponse, error) {
	out := new(GetNotifyTemplateResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetNotifyTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateNotifyTemplate(ctx context.Context, in *CreateNotifyTemplateRequest, opts ...grpc.CallOption) (*CreateNotifyTemplateResponse, error) {
	out := new(CreateNotifyTemplateResponse)
	err := c.cc.Invoke(ctx, NotificationService_CreateNotifyTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateNotifyTemplate(ctx context.Context, in *UpdateNotifyTemplateRequest, opts ...grpc.CallOption) (*UpdateNotifyTemplateResponse, error) {
	out := new(UpdateNotifyTemplateResponse)
	err := c.cc.Invoke(ctx, NotificationService_UpdateNotifyTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) BatchDeleteNotifyTemplates(ctx context.Context, in *BatchDeleteNotifyTemplatesRequest, opts ...grpc.CallOption) (*BatchDeleteNotifyTemplatesResponse, error) {
	out := new(BatchDeleteNotifyTemplatesResponse)
	err := c.cc.Invoke(ctx, NotificationService_BatchDeleteNotifyTemplates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ListNotifyMessages(ctx context.Context, in *ListNotifyMessagesRequest, opts ...grpc.CallOption) (*ListNotifyMessagesResponse, error) {
	out := new(ListNotifyMessagesResponse)
	err := c.cc.Invoke(ctx, NotificationService_ListNotifyMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetNotifyMessage(ctx context.Context, in *GetNotifyMessageRequest, opts ...grpc.CallOption) (*GetNotifyMessageResponse, error) {
	out := new(GetNotifyMessageResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetNotifyMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateNotifyMessage(ctx context.Context, in *CreateNotifyMessageRequest, opts ...grpc.CallOption) (*CreateNotifyMessageResponse, error) {
	out := new(CreateNotifyMessageResponse)
	err := c.cc.Invoke(ctx, NotificationService_CreateNotifyMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateNotifyMessage(ctx context.Context, in *UpdateNotifyMessageRequest, opts ...grpc.CallOption) (*UpdateNotifyMessageResponse, error) {
	out := new(UpdateNotifyMessageResponse)
	err := c.cc.Invoke(ctx, NotificationService_UpdateNotifyMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) BatchDeleteNotifyMessages(ctx context.Context, in *BatchDeleteNotifyMessagesRequest, opts ...grpc.CallOption) (*BatchDeleteNotifyMessagesResponse, error) {
	out := new(BatchDeleteNotifyMessagesResponse)
	err := c.cc.Invoke(ctx, NotificationService_BatchDeleteNotifyMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) PublishNotifyMessage(ctx context.Context, in *PublishNotifyMessageRequest, opts ...grpc.CallOption) (*PublishNotifyMessageResponse, error) {
	out := new(PublishNotifyMessageResponse)
	err := c.cc.Invoke(ctx, NotificationService_PublishNotifyMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) RevokeNotifyMessage(ctx context.Context, in *RevokeNotifyMessageRequest, opts ...grpc.CallOption) (*RevokeNotifyMessageResponse, error) {
	out := new(RevokeNotifyMessageResponse)
	err := c.cc.Invoke(ctx, NotificationService_RevokeNotifyMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ListNotifyRecords(ctx context.Context, in *ListNotifyRecordsRequest, opts ...grpc.CallOption) (*ListNotifyRecordsResponse, error) {
	out := new(ListNotifyRecordsResponse)
	err := c.cc.Invoke(ctx, NotificationService_ListNotifyRecords_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) BatchDeleteNotifyRecords(ctx context.Context, in *BatchDeleteNotifyRecordsRequest, opts ...grpc.CallOption) (*BatchDeleteNotifyRecordsResponse, error) {
	out := new(BatchDeleteNotifyRecordsResponse)
	err := c.cc.Invoke(ctx, NotificationService_BatchDeleteNotifyRecords_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ListUserInboxRecords(ctx context.Context, in *ListUserInboxRecordsRequest, opts ...grpc.CallOption) (*ListUserInboxRecordsResponse, error) {
	out := new(ListUserInboxRecordsResponse)
	err := c.cc.Invoke(ctx, NotificationService_ListUserInboxRecords_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkRecordRead(ctx context.Context, in *MarkRecordReadRequest, opts ...grpc.CallOption) (*MarkRecordReadResponse, error) {
	out := new(MarkRecordReadResponse)
	err := c.cc.Invoke(ctx, NotificationService_MarkRecordRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) BatchMarkRecordsRead(ctx context.Context, in *BatchMarkRecordsReadRequest, opts ...grpc.CallOption) (*BatchMarkRecordsReadResponse, error) {
	out := new(BatchMarkRecordsReadResponse)
	err := c.cc.Invoke(ctx, NotificationService_BatchMarkRecordsRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkAllRecordsRead(ctx context.Context, in *MarkAllRecordsReadRequest, opts ...grpc.CallOption) (*MarkAllRecordsReadResponse, error) {
	out := new(MarkAllRecordsReadResponse)
	err := c.cc.Invoke(ctx, NotificationService_MarkAllRecordsRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendMobileCode(ctx context.Context, in *SendMobileCodeRequest, opts ...grpc.CallOption) (*SendMobileCodeResponse, error) {
	out := new(SendMobileCodeResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendMobileCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) VerifyMobileCode(ctx context.Context, in *VerifyMobileCodeRequest, opts ...grpc.CallOption) (*VerifyMobileCodeResponse, error) {
	out := new(VerifyMobileCodeResponse)
	err := c.cc.Invoke(ctx, NotificationService_VerifyMobileCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendEmailCode(ctx context.Context, in *SendEmailCodeRequest, opts ...grpc.CallOption) (*SendEmailCodeResponse, error) {
	out := new(SendEmailCodeResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendEmailCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) VerifyEmailCode(ctx context.Context, in *VerifyEmailCodeRequest, opts ...grpc.CallOption) (*VerifyEmailCodeResponse, error) {
	out := new(VerifyEmailCodeResponse)
	err := c.cc.Invoke(ctx, NotificationService_VerifyEmailCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility
type NotificationServiceServer interface {
	// 分页查询通知模板列表
	ListNotifyTemplates(context.Context, *ListNotifyTemplatesRequest) (*ListNotifyTemplatesResponse, error)
	// 查询通知模板详情
	GetNotifyTemplate(context.Context, *GetNotifyTemplateRequest) (*GetNotifyTemplateResponse, error)
	// 创建通知模板
	CreateNotifyTemplate(context.Context, *CreateNotifyTemplateRequest) (*CreateNotifyTemplateResponse, error)
	// 更新通知模板
	UpdateNotifyTemplate(context.Context, *UpdateNotifyTemplateRequest) (*UpdateNotifyTemplateResponse, error)
	// 批量删除通知模板
	BatchDeleteNotifyTemplates(context.Context, *BatchDeleteNotifyTemplatesRequest) (*BatchDeleteNotifyTemplatesResponse, error)
	// 分页查询通知消息列表
	ListNotifyMessages(context.Context, *ListNotifyMessagesRequest) (*ListNotifyMessagesResponse, error)
	// 查询通知消息详情
	GetNotifyMessage(context.Context, *GetNotifyMessageRequest) (*GetNotifyMessageResponse, error)
	// 创建通知消息
	CreateNotifyMessage(context.Context, *CreateNotifyMessageRequest) (*CreateNotifyMessageResponse, error)
	// 更新通知消息
	UpdateNotifyMessage(context.Context, *UpdateNotifyMessageRequest) (*UpdateNotifyMessageResponse, error)
	// 批量删除通知消息
	BatchDeleteNotifyMessages(context.Context, *BatchDeleteNotifyMessagesRequest) (*BatchDeleteNotifyMessagesResponse, error)
	// 发布通知消息
	PublishNotifyMessage(context.Context, *PublishNotifyMessageRequest) (*PublishNotifyMessageResponse, error)
	// 撤销通知消息
	RevokeNotifyMessage(context.Context, *RevokeNotifyMessageRequest) (*RevokeNotifyMessageResponse, error)
	// 分页查询投递记录列表
	ListNotifyRecords(context.Context, *ListNotifyRecordsRequest) (*ListNotifyRecordsResponse, error)
	// 批量删除投递记录
	BatchDeleteNotifyRecords(context.Context, *BatchDeleteNotifyRecordsRequest) (*BatchDeleteNotifyRecordsResponse, error)
	// 查询用户 inbox 投递列表
	ListUserInboxRecords(context.Context, *ListUserInboxRecordsRequest) (*ListUserInboxRecordsResponse, error)
	// 标记单条 inbox 已读
	MarkRecordRead(context.Context, *MarkRecordReadRequest) (*MarkRecordReadResponse, error)
	// 批量标记 inbox 已读
	BatchMarkRecordsRead(context.Context, *BatchMarkRecordsReadRequest) (*BatchMarkRecordsReadResponse, error)
	// 全部标记 inbox 已读
	MarkAllRecordsRead(context.Context, *MarkAllRecordsReadRequest) (*MarkAllRecordsReadResponse, error)
	// 发送手机验证码
	SendMobileCode(context.Context, *SendMobileCodeRequest) (*SendMobileCodeResponse, error)
	// 校验手机验证码
	VerifyMobileCode(context.Context, *VerifyMobileCodeRequest) (*VerifyMobileCodeResponse, error)
	// 发送邮箱验证码
	SendEmailCode(context.Context, *SendEmailCodeRequest) (*SendEmailCodeResponse, error)
	// 校验邮箱验证码
	VerifyEmailCode(context.Context, *VerifyEmailCodeRequest) (*VerifyEmailCodeResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) ListNotifyTemplates(context.Context, *ListNotifyTemplatesRequest) (*ListNotifyTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotifyTemplates not implemented")
}
func (UnimplementedNotificationServiceServer) GetNotifyTemplate(context.Context, *GetNotifyTemplateRequest) (*GetNotifyTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotifyTemplate not implemented")
}
func (UnimplementedNotificationServiceServer) CreateNotifyTemplate(context.Context, *CreateNotifyTemplateRequest) (*CreateNotifyTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotifyTemplate not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateNotifyTemplate(context.Context, *UpdateNotifyTemplateRequest) (*UpdateNotifyTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotifyTemplate not implemented")
}
func (UnimplementedNotificationServiceServer) BatchDeleteNotifyTemplates(context.Context, *BatchDeleteNotifyTemplatesRequest) (*BatchDeleteNotifyTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteNotifyTemplates not implemented")
}
func (UnimplementedNotificationServiceServer) ListNotifyMessages(context.Context, *ListNotifyMessagesRequest) (*ListNotifyMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotifyMessages not implemented")
}
func (UnimplementedNotificationServiceServer) GetNotifyMessage(context.Context, *GetNotifyMessageRequest) (*GetNotifyMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotifyMessage not implemented")
}
func (UnimplementedNotificationServiceServer) CreateNotifyMessage(context.Context, *CreateNotifyMessageRequest) (*CreateNotifyMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotifyMessage not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateNotifyMessage(context.Context, *UpdateNotifyMessageRequest) (*UpdateNotifyMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotifyMessage not implemented")
}
func (UnimplementedNotificationServiceServer) BatchDeleteNotifyMessages(context.Context, *BatchDeleteNotifyMessagesRequest) (*BatchDeleteNotifyMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteNotifyMessages not implemented")
}
func (UnimplementedNotificationServiceServer) PublishNotifyMessage(context.Context, *PublishNotifyMessageRequest) (*PublishNotifyMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishNotifyMessage not implemented")
}
func (UnimplementedNotificationServiceServer) RevokeNotifyMessage(context.Context, *RevokeNotifyMessageRequest) (*RevokeNotifyMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeNotifyMessage not implemented")
}
func (UnimplementedNotificationServiceServer) ListNotifyRecords(context.Context, *ListNotifyRecordsRequest) (*ListNotifyRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotifyRecords not implemented")
}
func (UnimplementedNotificationServiceServer) BatchDeleteNotifyRecords(context.Context, *BatchDeleteNotifyRecordsRequest) (*BatchDeleteNotifyRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteNotifyRecords not implemented")
}
func (UnimplementedNotificationServiceServer) ListUserInboxRecords(context.Context, *ListUserInboxRecordsRequest) (*ListUserInboxRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserInboxRecords not implemented")
}
func (UnimplementedNotificationServiceServer) MarkRecordRead(context.Context, *MarkRecordReadRequest) (*MarkRecordReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkRecordRead not implemented")
}
func (UnimplementedNotificationServiceServer) BatchMarkRecordsRead(context.Context, *BatchMarkRecordsReadRequest) (*BatchMarkRecordsReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchMarkRecordsRead not implemented")
}
func (UnimplementedNotificationServiceServer) MarkAllRecordsRead(context.Context, *MarkAllRecordsReadRequest) (*MarkAllRecordsReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkAllRecordsRead not implemented")
}
func (UnimplementedNotificationServiceServer) SendMobileCode(context.Context, *SendMobileCodeRequest) (*SendMobileCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMobileCode not implemented")
}
func (UnimplementedNotificationServiceServer) VerifyMobileCode(context.Context, *VerifyMobileCodeRequest) (*VerifyMobileCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyMobileCode not implemented")
}
func (UnimplementedNotificationServiceServer) SendEmailCode(context.Context, *SendEmailCodeRequest) (*SendEmailCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailCode not implemented")
}
func (UnimplementedNotificationServiceServer) VerifyEmailCode(context.Context, *VerifyEmailCodeRequest) (*VerifyEmailCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEmailCode not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_ListNotifyTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotifyTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListNotifyTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ListNotifyTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListNotifyTemplates(ctx, req.(*ListNotifyTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetNotifyTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotifyTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotifyTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetNotifyTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotifyTemplate(ctx, req.(*GetNotifyTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateNotifyTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotifyTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNotifyTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNotifyTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNotifyTemplate(ctx, req.(*CreateNotifyTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateNotifyTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotifyTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateNotifyTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UpdateNotifyTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateNotifyTemplate(ctx, req.(*UpdateNotifyTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_BatchDeleteNotifyTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteNotifyTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).BatchDeleteNotifyTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_BatchDeleteNotifyTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).BatchDeleteNotifyTemplates(ctx, req.(*BatchDeleteNotifyTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ListNotifyMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotifyMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListNotifyMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ListNotifyMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListNotifyMessages(ctx, req.(*ListNotifyMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetNotifyMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotifyMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotifyMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetNotifyMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotifyMessage(ctx, req.(*GetNotifyMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateNotifyMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotifyMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNotifyMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNotifyMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNotifyMessage(ctx, req.(*CreateNotifyMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateNotifyMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotifyMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateNotifyMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UpdateNotifyMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateNotifyMessage(ctx, req.(*UpdateNotifyMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_BatchDeleteNotifyMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteNotifyMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).BatchDeleteNotifyMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_BatchDeleteNotifyMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).BatchDeleteNotifyMessages(ctx, req.(*BatchDeleteNotifyMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_PublishNotifyMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishNotifyMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).PublishNotifyMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_PublishNotifyMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).PublishNotifyMessage(ctx, req.(*PublishNotifyMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_RevokeNotifyMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeNotifyMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).RevokeNotifyMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_RevokeNotifyMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).RevokeNotifyMessage(ctx, req.(*RevokeNotifyMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ListNotifyRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotifyRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListNotifyRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ListNotifyRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListNotifyRecords(ctx, req.(*ListNotifyRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_BatchDeleteNotifyRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteNotifyRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).BatchDeleteNotifyRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_BatchDeleteNotifyRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).BatchDeleteNotifyRecords(ctx, req.(*BatchDeleteNotifyRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ListUserInboxRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserInboxRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListUserInboxRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ListUserInboxRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListUserInboxRecords(ctx, req.(*ListUserInboxRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkRecordRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkRecordReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkRecordRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MarkRecordRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkRecordRead(ctx, req.(*MarkRecordReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_BatchMarkRecordsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchMarkRecordsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).BatchMarkRecordsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_BatchMarkRecordsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).BatchMarkRecordsRead(ctx, req.(*BatchMarkRecordsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkAllRecordsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllRecordsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkAllRecordsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MarkAllRecordsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkAllRecordsRead(ctx, req.(*MarkAllRecordsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendMobileCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMobileCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendMobileCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendMobileCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendMobileCode(ctx, req.(*SendMobileCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_VerifyMobileCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyMobileCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).VerifyMobileCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_VerifyMobileCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).VerifyMobileCode(ctx, req.(*VerifyMobileCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendEmailCode(ctx, req.(*SendEmailCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_VerifyEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).VerifyEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_VerifyEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).VerifyEmailCode(ctx, req.(*VerifyEmailCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.notification.v1.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNotifyTemplates",
			Handler:    _NotificationService_ListNotifyTemplates_Handler,
		},
		{
			MethodName: "GetNotifyTemplate",
			Handler:    _NotificationService_GetNotifyTemplate_Handler,
		},
		{
			MethodName: "CreateNotifyTemplate",
			Handler:    _NotificationService_CreateNotifyTemplate_Handler,
		},
		{
			MethodName: "UpdateNotifyTemplate",
			Handler:    _NotificationService_UpdateNotifyTemplate_Handler,
		},
		{
			MethodName: "BatchDeleteNotifyTemplates",
			Handler:    _NotificationService_BatchDeleteNotifyTemplates_Handler,
		},
		{
			MethodName: "ListNotifyMessages",
			Handler:    _NotificationService_ListNotifyMessages_Handler,
		},
		{
			MethodName: "GetNotifyMessage",
			Handler:    _NotificationService_GetNotifyMessage_Handler,
		},
		{
			MethodName: "CreateNotifyMessage",
			Handler:    _NotificationService_CreateNotifyMessage_Handler,
		},
		{
			MethodName: "UpdateNotifyMessage",
			Handler:    _NotificationService_UpdateNotifyMessage_Handler,
		},
		{
			MethodName: "BatchDeleteNotifyMessages",
			Handler:    _NotificationService_BatchDeleteNotifyMessages_Handler,
		},
		{
			MethodName: "PublishNotifyMessage",
			Handler:    _NotificationService_PublishNotifyMessage_Handler,
		},
		{
			MethodName: "RevokeNotifyMessage",
			Handler:    _NotificationService_RevokeNotifyMessage_Handler,
		},
		{
			MethodName: "ListNotifyRecords",
			Handler:    _NotificationService_ListNotifyRecords_Handler,
		},
		{
			MethodName: "BatchDeleteNotifyRecords",
			Handler:    _NotificationService_BatchDeleteNotifyRecords_Handler,
		},
		{
			MethodName: "ListUserInboxRecords",
			Handler:    _NotificationService_ListUserInboxRecords_Handler,
		},
		{
			MethodName: "MarkRecordRead",
			Handler:    _NotificationService_MarkRecordRead_Handler,
		},
		{
			MethodName: "BatchMarkRecordsRead",
			Handler:    _NotificationService_BatchMarkRecordsRead_Handler,
		},
		{
			MethodName: "MarkAllRecordsRead",
			Handler:    _NotificationService_MarkAllRecordsRead_Handler,
		},
		{
			MethodName: "SendMobileCode",
			Handler:    _NotificationService_SendMobileCode_Handler,
		},
		{
			MethodName: "VerifyMobileCode",
			Handler:    _NotificationService_VerifyMobileCode_Handler,
		},
		{
			MethodName: "SendEmailCode",
			Handler:    _NotificationService_SendEmailCode_Handler,
		},
		{
			MethodName: "VerifyEmailCode",
			Handler:    _NotificationService_VerifyEmailCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
