// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: media.proto

package mediaservice

import (
	"context"

	"github.com/ve-weiyi/blog-cloud/rpc/blog/internal/pb/mediarpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Album                      = mediarpc.Album
	BatchDestroyAlbumsRequest  = mediarpc.BatchDestroyAlbumsRequest
	BatchDestroyAlbumsResponse = mediarpc.BatchDestroyAlbumsResponse
	BatchDestroyPhotosRequest  = mediarpc.BatchDestroyPhotosRequest
	BatchDestroyPhotosResponse = mediarpc.BatchDestroyPhotosResponse
	BatchPatchAlbumsRequest    = mediarpc.BatchPatchAlbumsRequest
	BatchPatchAlbumsResponse   = mediarpc.BatchPatchAlbumsResponse
	BatchPatchPhotosRequest    = mediarpc.BatchPatchPhotosRequest
	BatchPatchPhotosResponse   = mediarpc.BatchPatchPhotosResponse
	CreateAlbumRequest         = mediarpc.CreateAlbumRequest
	CreateAlbumResponse        = mediarpc.CreateAlbumResponse
	CreatePhotoRequest         = mediarpc.CreatePhotoRequest
	CreatePhotoResponse        = mediarpc.CreatePhotoResponse
	GetAlbumRequest            = mediarpc.GetAlbumRequest
	GetAlbumResponse           = mediarpc.GetAlbumResponse
	ListAlbumsRequest          = mediarpc.ListAlbumsRequest
	ListAlbumsResponse         = mediarpc.ListAlbumsResponse
	ListPhotosRequest          = mediarpc.ListPhotosRequest
	ListPhotosResponse         = mediarpc.ListPhotosResponse
	ListQuery                  = mediarpc.ListQuery
	ListResult                 = mediarpc.ListResult
	Photo                      = mediarpc.Photo
	UpdateAlbumRequest         = mediarpc.UpdateAlbumRequest
	UpdateAlbumResponse        = mediarpc.UpdateAlbumResponse
	UpdatePhotoRequest         = mediarpc.UpdatePhotoRequest
	UpdatePhotoResponse        = mediarpc.UpdatePhotoResponse

	MediaService interface {
		// 分页查询照片列表
		ListPhotos(ctx context.Context, in *ListPhotosRequest, opts ...grpc.CallOption) (*ListPhotosResponse, error)
		// 创建照片
		CreatePhoto(ctx context.Context, in *CreatePhotoRequest, opts ...grpc.CallOption) (*CreatePhotoResponse, error)
		// 更新照片
		UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*UpdatePhotoResponse, error)
		// 部分更新照片
		BatchPatchPhotos(ctx context.Context, in *BatchPatchPhotosRequest, opts ...grpc.CallOption) (*BatchPatchPhotosResponse, error)
		// 批量销毁照片（彻底删除，不可恢复）
		BatchDestroyPhotos(ctx context.Context, in *BatchDestroyPhotosRequest, opts ...grpc.CallOption) (*BatchDestroyPhotosResponse, error)
		// 分页查询相册列表
		ListAlbums(ctx context.Context, in *ListAlbumsRequest, opts ...grpc.CallOption) (*ListAlbumsResponse, error)
		// 查询相册详情
		GetAlbum(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*GetAlbumResponse, error)
		// 创建相册
		CreateAlbum(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*CreateAlbumResponse, error)
		// 更新相册
		UpdateAlbum(ctx context.Context, in *UpdateAlbumRequest, opts ...grpc.CallOption) (*UpdateAlbumResponse, error)
		// 部分更新相册
		BatchPatchAlbums(ctx context.Context, in *BatchPatchAlbumsRequest, opts ...grpc.CallOption) (*BatchPatchAlbumsResponse, error)
		// 批量销毁相册（彻底删除，不可恢复）
		BatchDestroyAlbums(ctx context.Context, in *BatchDestroyAlbumsRequest, opts ...grpc.CallOption) (*BatchDestroyAlbumsResponse, error)
	}

	defaultMediaService struct {
		cli zrpc.Client
	}
)

func NewMediaService(cli zrpc.Client) MediaService {
	return &defaultMediaService{
		cli: cli,
	}
}

// 分页查询照片列表
func (m *defaultMediaService) ListPhotos(ctx context.Context, in *ListPhotosRequest, opts ...grpc.CallOption) (*ListPhotosResponse, error) {
	client := mediarpc.NewMediaServiceClient(m.cli.Conn())
	return client.ListPhotos(ctx, in, opts...)
}

// 创建照片
func (m *defaultMediaService) CreatePhoto(ctx context.Context, in *CreatePhotoRequest, opts ...grpc.CallOption) (*CreatePhotoResponse, error) {
	client := mediarpc.NewMediaServiceClient(m.cli.Conn())
	return client.CreatePhoto(ctx, in, opts...)
}

// 更新照片
func (m *defaultMediaService) UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*UpdatePhotoResponse, error) {
	client := mediarpc.NewMediaServiceClient(m.cli.Conn())
	return client.UpdatePhoto(ctx, in, opts...)
}

// 部分更新照片
func (m *defaultMediaService) BatchPatchPhotos(ctx context.Context, in *BatchPatchPhotosRequest, opts ...grpc.CallOption) (*BatchPatchPhotosResponse, error) {
	client := mediarpc.NewMediaServiceClient(m.cli.Conn())
	return client.BatchPatchPhotos(ctx, in, opts...)
}

// 批量销毁照片（彻底删除，不可恢复）
func (m *defaultMediaService) BatchDestroyPhotos(ctx context.Context, in *BatchDestroyPhotosRequest, opts ...grpc.CallOption) (*BatchDestroyPhotosResponse, error) {
	client := mediarpc.NewMediaServiceClient(m.cli.Conn())
	return client.BatchDestroyPhotos(ctx, in, opts...)
}

// 分页查询相册列表
func (m *defaultMediaService) ListAlbums(ctx context.Context, in *ListAlbumsRequest, opts ...grpc.CallOption) (*ListAlbumsResponse, error) {
	client := mediarpc.NewMediaServiceClient(m.cli.Conn())
	return client.ListAlbums(ctx, in, opts...)
}

// 查询相册详情
func (m *defaultMediaService) GetAlbum(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*GetAlbumResponse, error) {
	client := mediarpc.NewMediaServiceClient(m.cli.Conn())
	return client.GetAlbum(ctx, in, opts...)
}

// 创建相册
func (m *defaultMediaService) CreateAlbum(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*CreateAlbumResponse, error) {
	client := mediarpc.NewMediaServiceClient(m.cli.Conn())
	return client.CreateAlbum(ctx, in, opts...)
}

// 更新相册
func (m *defaultMediaService) UpdateAlbum(ctx context.Context, in *UpdateAlbumRequest, opts ...grpc.CallOption) (*UpdateAlbumResponse, error) {
	client := mediarpc.NewMediaServiceClient(m.cli.Conn())
	return client.UpdateAlbum(ctx, in, opts...)
}

// 部分更新相册
func (m *defaultMediaService) BatchPatchAlbums(ctx context.Context, in *BatchPatchAlbumsRequest, opts ...grpc.CallOption) (*BatchPatchAlbumsResponse, error) {
	client := mediarpc.NewMediaServiceClient(m.cli.Conn())
	return client.BatchPatchAlbums(ctx, in, opts...)
}

// 批量销毁相册（彻底删除，不可恢复）
func (m *defaultMediaService) BatchDestroyAlbums(ctx context.Context, in *BatchDestroyAlbumsRequest, opts ...grpc.CallOption) (*BatchDestroyAlbumsResponse, error) {
	client := mediarpc.NewMediaServiceClient(m.cli.Conn())
	return client.BatchDestroyAlbums(ctx, in, opts...)
}
